// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package translationsmock

import (
	"sync"
)

var (
	lockTranslationsMockFormatted       sync.RWMutex
	lockTranslationsMockFormattedPlural sync.RWMutex
	lockTranslationsMockPlural          sync.RWMutex
	lockTranslationsMockSingular        sync.RWMutex
)

// TranslationsMock is a mock implementation of Translations.
//
//     func TestSomethingThatUsesTranslations(t *testing.T) {
//
//         // make and configure a mocked Translations
//         mockedTranslations := &TranslationsMock{
//             FormattedFunc: func(languageID uint16, key string) string {
// 	               panic("mock out the Formatted method")
//             },
//             FormattedPluralFunc: func(languageID uint16, key string) string {
// 	               panic("mock out the FormattedPlural method")
//             },
//             PluralFunc: func(languageID uint16, key string) string {
// 	               panic("mock out the Plural method")
//             },
//             SingularFunc: func(languageID uint16, key string) string {
// 	               panic("mock out the Singular method")
//             },
//         }
//
//         // use mockedTranslations in code that requires Translations
//         // and then make assertions.
//
//     }
type TranslationsMock struct {
	// FormattedFunc mocks the Formatted method.
	FormattedFunc func(languageID uint16, key string) string

	// FormattedPluralFunc mocks the FormattedPlural method.
	FormattedPluralFunc func(languageID uint16, key string) string

	// PluralFunc mocks the Plural method.
	PluralFunc func(languageID uint16, key string) string

	// SingularFunc mocks the Singular method.
	SingularFunc func(languageID uint16, key string) string

	// calls tracks calls to the methods.
	calls struct {
		// Formatted holds details about calls to the Formatted method.
		Formatted []struct {
			// LanguageID is the languageID argument value.
			LanguageID uint16
			// Key is the key argument value.
			Key string
		}
		// FormattedPlural holds details about calls to the FormattedPlural method.
		FormattedPlural []struct {
			// LanguageID is the languageID argument value.
			LanguageID uint16
			// Key is the key argument value.
			Key string
		}
		// Plural holds details about calls to the Plural method.
		Plural []struct {
			// LanguageID is the languageID argument value.
			LanguageID uint16
			// Key is the key argument value.
			Key string
		}
		// Singular holds details about calls to the Singular method.
		Singular []struct {
			// LanguageID is the languageID argument value.
			LanguageID uint16
			// Key is the key argument value.
			Key string
		}
	}
}

// Formatted calls FormattedFunc.
func (mock *TranslationsMock) Formatted(languageID uint16, key string) string {
	if mock.FormattedFunc == nil {
		panic("TranslationsMock.FormattedFunc: method is nil but Translations.Formatted was just called")
	}
	callInfo := struct {
		LanguageID uint16
		Key        string
	}{
		LanguageID: languageID,
		Key:        key,
	}
	lockTranslationsMockFormatted.Lock()
	mock.calls.Formatted = append(mock.calls.Formatted, callInfo)
	lockTranslationsMockFormatted.Unlock()
	return mock.FormattedFunc(languageID, key)
}

// FormattedCalls gets all the calls that were made to Formatted.
// Check the length with:
//     len(mockedTranslations.FormattedCalls())
func (mock *TranslationsMock) FormattedCalls() []struct {
	LanguageID uint16
	Key        string
} {
	var calls []struct {
		LanguageID uint16
		Key        string
	}
	lockTranslationsMockFormatted.RLock()
	calls = mock.calls.Formatted
	lockTranslationsMockFormatted.RUnlock()
	return calls
}

// FormattedPlural calls FormattedPluralFunc.
func (mock *TranslationsMock) FormattedPlural(languageID uint16, key string) string {
	if mock.FormattedPluralFunc == nil {
		panic("TranslationsMock.FormattedPluralFunc: method is nil but Translations.FormattedPlural was just called")
	}
	callInfo := struct {
		LanguageID uint16
		Key        string
	}{
		LanguageID: languageID,
		Key:        key,
	}
	lockTranslationsMockFormattedPlural.Lock()
	mock.calls.FormattedPlural = append(mock.calls.FormattedPlural, callInfo)
	lockTranslationsMockFormattedPlural.Unlock()
	return mock.FormattedPluralFunc(languageID, key)
}

// FormattedPluralCalls gets all the calls that were made to FormattedPlural.
// Check the length with:
//     len(mockedTranslations.FormattedPluralCalls())
func (mock *TranslationsMock) FormattedPluralCalls() []struct {
	LanguageID uint16
	Key        string
} {
	var calls []struct {
		LanguageID uint16
		Key        string
	}
	lockTranslationsMockFormattedPlural.RLock()
	calls = mock.calls.FormattedPlural
	lockTranslationsMockFormattedPlural.RUnlock()
	return calls
}

// Plural calls PluralFunc.
func (mock *TranslationsMock) Plural(languageID uint16, key string) string {
	if mock.PluralFunc == nil {
		panic("TranslationsMock.PluralFunc: method is nil but Translations.Plural was just called")
	}
	callInfo := struct {
		LanguageID uint16
		Key        string
	}{
		LanguageID: languageID,
		Key:        key,
	}
	lockTranslationsMockPlural.Lock()
	mock.calls.Plural = append(mock.calls.Plural, callInfo)
	lockTranslationsMockPlural.Unlock()
	return mock.PluralFunc(languageID, key)
}

// PluralCalls gets all the calls that were made to Plural.
// Check the length with:
//     len(mockedTranslations.PluralCalls())
func (mock *TranslationsMock) PluralCalls() []struct {
	LanguageID uint16
	Key        string
} {
	var calls []struct {
		LanguageID uint16
		Key        string
	}
	lockTranslationsMockPlural.RLock()
	calls = mock.calls.Plural
	lockTranslationsMockPlural.RUnlock()
	return calls
}

// Singular calls SingularFunc.
func (mock *TranslationsMock) Singular(languageID uint16, key string) string {
	if mock.SingularFunc == nil {
		panic("TranslationsMock.SingularFunc: method is nil but Translations.Singular was just called")
	}
	callInfo := struct {
		LanguageID uint16
		Key        string
	}{
		LanguageID: languageID,
		Key:        key,
	}
	lockTranslationsMockSingular.Lock()
	mock.calls.Singular = append(mock.calls.Singular, callInfo)
	lockTranslationsMockSingular.Unlock()
	return mock.SingularFunc(languageID, key)
}

// SingularCalls gets all the calls that were made to Singular.
// Check the length with:
//     len(mockedTranslations.SingularCalls())
func (mock *TranslationsMock) SingularCalls() []struct {
	LanguageID uint16
	Key        string
} {
	var calls []struct {
		LanguageID uint16
		Key        string
	}
	lockTranslationsMockSingular.RLock()
	calls = mock.calls.Singular
	lockTranslationsMockSingular.RUnlock()
	return calls
}
