// Code generated by qtc from "post.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line forum/post/post.qtpl:1
package post

//line forum/post/post.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line forum/post/post.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line forum/post/post.qtpl:1
func (page *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line forum/post/post.qtpl:1
	qw422016.E().S(*page.post.Title())
//line forum/post/post.qtpl:1
}

//line forum/post/post.qtpl:1
func (page *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line forum/post/post.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line forum/post/post.qtpl:1
	page.StreamTitle(qw422016)
//line forum/post/post.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line forum/post/post.qtpl:1
}

//line forum/post/post.qtpl:1
func (page *Page) Title() string {
//line forum/post/post.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line forum/post/post.qtpl:1
	page.WriteTitle(qb422016)
//line forum/post/post.qtpl:1
	qs422016 := string(qb422016.B)
//line forum/post/post.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line forum/post/post.qtpl:1
	return qs422016
//line forum/post/post.qtpl:1
}

//line forum/post/post.qtpl:3
func (page *Page) StreamContent(qw422016 *qt422016.Writer) {
//line forum/post/post.qtpl:3
	qw422016.N().S(`<div class="content"><div><h1>`)
//line forum/post/post.qtpl:6
	qw422016.E().S(*page.post.Title())
//line forum/post/post.qtpl:6
	qw422016.N().S(`</h1><p>`)
//line forum/post/post.qtpl:7
	qw422016.E().S(page.rendererService.CreatedBy(page.post, page.language.ID()))
//line forum/post/post.qtpl:7
	qw422016.N().S(`</p>`)
//line forum/post/post.qtpl:8
	if page.IsLoggedIn() && page.user.ID() == page.post.CreatedByID() {
//line forum/post/post.qtpl:8
		qw422016.N().S(`<p><a href="/ForumPost/Delete/`)
//line forum/post/post.qtpl:10
		qw422016.E().S(page.post.ID())
//line forum/post/post.qtpl:10
		qw422016.N().S(`">`)
//line forum/post/post.qtpl:11
		qw422016.E().S(page.Translate("delete"))
//line forum/post/post.qtpl:11
		qw422016.N().S(`</a></p>`)
//line forum/post/post.qtpl:14
	}
//line forum/post/post.qtpl:14
	qw422016.N().S(`<p>`)
//line forum/post/post.qtpl:16
	qw422016.E().S(page.post.Message())
//line forum/post/post.qtpl:16
	qw422016.N().S(`</p></div>`)
//line forum/post/post.qtpl:19
	if len(page.replies) > 0 {
//line forum/post/post.qtpl:19
		qw422016.N().S(`<h2>`)
//line forum/post/post.qtpl:20
		qw422016.E().S(page.TranslatePlural("reply"))
//line forum/post/post.qtpl:20
		qw422016.N().S(`</h2>`)
//line forum/post/post.qtpl:21
		for k := range page.replies {
//line forum/post/post.qtpl:21
			qw422016.N().S(`<div><p>`)
//line forum/post/post.qtpl:24
			if page.replies[k].Title() != nil {
//line forum/post/post.qtpl:25
				qw422016.E().S(*page.replies[k].Title())
//line forum/post/post.qtpl:26
			}
//line forum/post/post.qtpl:26
			qw422016.N().S(`</p><p>`)
//line forum/post/post.qtpl:28
			qw422016.E().S(page.rendererService.CreatedBy(page.replies[k], page.language.ID()))
//line forum/post/post.qtpl:28
			qw422016.N().S(`</p></div>`)
//line forum/post/post.qtpl:30
		}
//line forum/post/post.qtpl:31
	}
//line forum/post/post.qtpl:31
	qw422016.N().S(`</div>`)
//line forum/post/post.qtpl:33
}

//line forum/post/post.qtpl:33
func (page *Page) WriteContent(qq422016 qtio422016.Writer) {
//line forum/post/post.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line forum/post/post.qtpl:33
	page.StreamContent(qw422016)
//line forum/post/post.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line forum/post/post.qtpl:33
}

//line forum/post/post.qtpl:33
func (page *Page) Content() string {
//line forum/post/post.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line forum/post/post.qtpl:33
	page.WriteContent(qb422016)
//line forum/post/post.qtpl:33
	qs422016 := string(qb422016.B)
//line forum/post/post.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line forum/post/post.qtpl:33
	return qs422016
//line forum/post/post.qtpl:33
}
