// Code generated by espal-store-synthesizer. DO NOT EDIT.
package blogpost

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ CommentEntity = &Comment{}

type CommentEntity interface {
	database.Model
	BlogPostID() string
	SetBlogPostID(blogPostID string)
	Title() *string
	SetTitle(title *string)
	Message() string
	SetMessage(message string)
}

// ID returns id.
func (c *Comment) ID() string {
	return c.id
}

// CreatedByID returns createdByID.
func (c *Comment) CreatedByID() string {
	return c.createdByID
}

// SetCreatedByID sets the createdByID.
func (c *Comment) SetCreatedByID(createdByID string) {
	c.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (c *Comment) UpdatedByID() *string {
	return c.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (c *Comment) SetUpdatedByID(updatedByID *string) {
	c.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (c *Comment) CreatedAt() time.Time {
	return c.createdAt
}

// SetCreatedAt sets the createdAt.
func (c *Comment) SetCreatedAt(createdAt time.Time) {
	c.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (c *Comment) UpdatedAt() *time.Time {
	return c.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (c *Comment) SetUpdatedAt(updatedAt *time.Time) {
	c.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (c *Comment) CreatedByFirstName() *string {
	return c.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (c *Comment) SetCreatedByFirstName(createdByFirstName *string) {
	c.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (c *Comment) CreatedBySurname() *string {
	return c.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (c *Comment) SetCreatedBySurname(createdBySurname *string) {
	c.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (c *Comment) UpdatedByFirstName() *string {
	return c.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (c *Comment) SetUpdatedByFirstName(updatedByFirstName *string) {
	c.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (c *Comment) UpdatedBySurname() *string {
	return c.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (c *Comment) SetUpdatedBySurname(updatedBySurname *string) {
	c.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (c *Comment) IsUpdated() bool {
	return c.updatedByID != nil
}

// BlogPostID returns blogPostID.
func (c *Comment) BlogPostID() string {
	return c.blogPostID
}

// SetBlogPostID sets the blogPostID.
func (c *Comment) SetBlogPostID(blogPostID string) {
	c.blogPostID = blogPostID
}

// Title returns title.
func (c *Comment) Title() *string {
	return c.title
}

// SetTitle sets the title.
func (c *Comment) SetTitle(title *string) {
	c.title = title
}

// Message returns message.
func (c *Comment) Message() string {
	return c.message
}

// SetMessage sets the message.
func (c *Comment) SetMessage(message string) {
	c.message = message
}

func newComment() *Comment {
	return &Comment{}
}

// New returns a new instance of CommentEntity.
func NewCommentEntity() CommentEntity {
	return newComment()
}
