// Code generated by espal-store-synthesizer. DO NOT EDIT.
package blogpost

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ SectionEntity = &Section{}

type SectionEntity interface {
	database.Model
	Active() bool
	SetActive(active bool)
	Sorting() uint
	SetSorting(sorting uint)
	ParentID() *string
	SetParentID(parentID *string)
}

// ID returns id.
func (s *Section) ID() string {
	return s.id
}

// CreatedByID returns createdByID.
func (s *Section) CreatedByID() string {
	return s.createdByID
}

// SetCreatedByID sets the createdByID.
func (s *Section) SetCreatedByID(createdByID string) {
	s.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (s *Section) UpdatedByID() *string {
	return s.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (s *Section) SetUpdatedByID(updatedByID *string) {
	s.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (s *Section) CreatedAt() time.Time {
	return s.createdAt
}

// SetCreatedAt sets the createdAt.
func (s *Section) SetCreatedAt(createdAt time.Time) {
	s.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (s *Section) UpdatedAt() *time.Time {
	return s.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (s *Section) SetUpdatedAt(updatedAt *time.Time) {
	s.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (s *Section) CreatedByFirstName() *string {
	return s.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (s *Section) SetCreatedByFirstName(createdByFirstName *string) {
	s.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (s *Section) CreatedBySurname() *string {
	return s.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (s *Section) SetCreatedBySurname(createdBySurname *string) {
	s.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (s *Section) UpdatedByFirstName() *string {
	return s.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (s *Section) SetUpdatedByFirstName(updatedByFirstName *string) {
	s.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (s *Section) UpdatedBySurname() *string {
	return s.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (s *Section) SetUpdatedBySurname(updatedBySurname *string) {
	s.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (s *Section) IsUpdated() bool {
	return s.updatedByID != nil
}

// Active returns active.
func (s *Section) Active() bool {
	return s.active
}

// SetActive sets the active.
func (s *Section) SetActive(active bool) {
	s.active = active
}

// Sorting returns sorting.
func (s *Section) Sorting() uint {
	return s.sorting
}

// SetSorting sets the sorting.
func (s *Section) SetSorting(sorting uint) {
	s.sorting = sorting
}

// ParentID returns parentID.
func (s *Section) ParentID() *string {
	return s.parentID
}

// SetParentID sets the parentID.
func (s *Section) SetParentID(parentID *string) {
	s.parentID = parentID
}

func newSection() *Section {
	return &Section{}
}

// New returns a new instance of SectionEntity.
func NewSectionEntity() SectionEntity {
	return newSection()
}
