// Code generated by espal-store-synthesizer. DO NOT EDIT.
package newsarticle

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ NewsArticleEntity = &NewsArticle{}

type NewsArticleEntity interface {
	database.Model
	Active() bool
	SetActive(active bool)
	Sorting() uint
	SetSorting(sorting uint)
	SectionID() *string
	SetSectionID(sectionID *string)
	ApprovedByID() *string
	SetApprovedByID(approvedByID *string)
	ApprovedDate() *time.Time
	SetApprovedDate(approvedDate *time.Time)
	PublishDate() *time.Time
	SetPublishDate(publishDate *time.Time)
	ExpirationDate() *time.Time
	SetExpirationDate(expirationDate *time.Time)
	Comments() *string
	SetComments(comments *string)
}

// ID returns id.
func (n *NewsArticle) ID() string {
	return n.id
}

// CreatedByID returns createdByID.
func (n *NewsArticle) CreatedByID() string {
	return n.createdByID
}

// SetCreatedByID sets the createdByID.
func (n *NewsArticle) SetCreatedByID(createdByID string) {
	n.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (n *NewsArticle) UpdatedByID() *string {
	return n.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (n *NewsArticle) SetUpdatedByID(updatedByID *string) {
	n.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (n *NewsArticle) CreatedAt() time.Time {
	return n.createdAt
}

// SetCreatedAt sets the createdAt.
func (n *NewsArticle) SetCreatedAt(createdAt time.Time) {
	n.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (n *NewsArticle) UpdatedAt() *time.Time {
	return n.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (n *NewsArticle) SetUpdatedAt(updatedAt *time.Time) {
	n.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (n *NewsArticle) CreatedByFirstName() *string {
	return n.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (n *NewsArticle) SetCreatedByFirstName(createdByFirstName *string) {
	n.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (n *NewsArticle) CreatedBySurname() *string {
	return n.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (n *NewsArticle) SetCreatedBySurname(createdBySurname *string) {
	n.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (n *NewsArticle) UpdatedByFirstName() *string {
	return n.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (n *NewsArticle) SetUpdatedByFirstName(updatedByFirstName *string) {
	n.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (n *NewsArticle) UpdatedBySurname() *string {
	return n.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (n *NewsArticle) SetUpdatedBySurname(updatedBySurname *string) {
	n.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (n *NewsArticle) IsUpdated() bool {
	return n.updatedByID != nil
}

// Active returns active.
func (n *NewsArticle) Active() bool {
	return n.active
}

// SetActive sets the active.
func (n *NewsArticle) SetActive(active bool) {
	n.active = active
}

// Sorting returns sorting.
func (n *NewsArticle) Sorting() uint {
	return n.sorting
}

// SetSorting sets the sorting.
func (n *NewsArticle) SetSorting(sorting uint) {
	n.sorting = sorting
}

// SectionID returns sectionID.
func (n *NewsArticle) SectionID() *string {
	return n.sectionID
}

// SetSectionID sets the sectionID.
func (n *NewsArticle) SetSectionID(sectionID *string) {
	n.sectionID = sectionID
}

// ApprovedByID returns approvedByID.
func (n *NewsArticle) ApprovedByID() *string {
	return n.approvedByID
}

// SetApprovedByID sets the approvedByID.
func (n *NewsArticle) SetApprovedByID(approvedByID *string) {
	n.approvedByID = approvedByID
}

// ApprovedDate returns approvedDate.
func (n *NewsArticle) ApprovedDate() *time.Time {
	return n.approvedDate
}

// SetApprovedDate sets the approvedDate.
func (n *NewsArticle) SetApprovedDate(approvedDate *time.Time) {
	n.approvedDate = approvedDate
}

// PublishDate returns publishDate.
func (n *NewsArticle) PublishDate() *time.Time {
	return n.publishDate
}

// SetPublishDate sets the publishDate.
func (n *NewsArticle) SetPublishDate(publishDate *time.Time) {
	n.publishDate = publishDate
}

// ExpirationDate returns expirationDate.
func (n *NewsArticle) ExpirationDate() *time.Time {
	return n.expirationDate
}

// SetExpirationDate sets the expirationDate.
func (n *NewsArticle) SetExpirationDate(expirationDate *time.Time) {
	n.expirationDate = expirationDate
}

// Comments returns comments.
func (n *NewsArticle) Comments() *string {
	return n.comments
}

// SetComments sets the comments.
func (n *NewsArticle) SetComments(comments *string) {
	n.comments = comments
}

func newNewsArticle() *NewsArticle {
	return &NewsArticle{}
}

// New returns a new instance of NewsArticleEntity.
func NewNewsArticleEntity() NewsArticleEntity {
	return newNewsArticle()
}
