// Code generated by espal-store-synthesizer. DO NOT EDIT.
package deliverymethod

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ DeliveryMethodEntity = &DeliveryMethod{}

type DeliveryMethodEntity interface {
	database.Model
	Price() float64
	SetPrice(price float64)
}

// TableName returns the table name that belongs to the current model.
func (deliveryMethod *DeliveryMethod) TableName() string {
	return "DeliveryMethod"
}

// TableAlias returns the unique resolved table alias for use in queries.
func (deliveryMethod *DeliveryMethod) TableAlias() string {
	return "dme"
}

// ID returns id.
func (deliveryMethod *DeliveryMethod) ID() string {
	return deliveryMethod.id
}

// CreatedByID returns createdByID.
func (deliveryMethod *DeliveryMethod) CreatedByID() string {
	return deliveryMethod.createdByID
}

// SetCreatedByID sets the createdByID.
func (deliveryMethod *DeliveryMethod) SetCreatedByID(createdByID string) {
	deliveryMethod.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (deliveryMethod *DeliveryMethod) UpdatedByID() *string {
	return deliveryMethod.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (deliveryMethod *DeliveryMethod) SetUpdatedByID(updatedByID *string) {
	deliveryMethod.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (deliveryMethod *DeliveryMethod) CreatedAt() time.Time {
	return deliveryMethod.createdAt
}

// SetCreatedAt sets the createdAt.
func (deliveryMethod *DeliveryMethod) SetCreatedAt(createdAt time.Time) {
	deliveryMethod.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (deliveryMethod *DeliveryMethod) UpdatedAt() *time.Time {
	return deliveryMethod.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (deliveryMethod *DeliveryMethod) SetUpdatedAt(updatedAt *time.Time) {
	deliveryMethod.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (deliveryMethod *DeliveryMethod) CreatedByFirstName() *string {
	return deliveryMethod.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (deliveryMethod *DeliveryMethod) SetCreatedByFirstName(createdByFirstName *string) {
	deliveryMethod.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (deliveryMethod *DeliveryMethod) CreatedBySurname() *string {
	return deliveryMethod.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (deliveryMethod *DeliveryMethod) SetCreatedBySurname(createdBySurname *string) {
	deliveryMethod.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (deliveryMethod *DeliveryMethod) UpdatedByFirstName() *string {
	return deliveryMethod.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (deliveryMethod *DeliveryMethod) SetUpdatedByFirstName(updatedByFirstName *string) {
	deliveryMethod.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (deliveryMethod *DeliveryMethod) UpdatedBySurname() *string {
	return deliveryMethod.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (deliveryMethod *DeliveryMethod) SetUpdatedBySurname(updatedBySurname *string) {
	deliveryMethod.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (deliveryMethod *DeliveryMethod) IsUpdated() bool {
	return deliveryMethod.updatedByID != nil
}

// Price returns price.
func (deliveryMethod *DeliveryMethod) Price() float64 {
	return deliveryMethod.price
}

// SetPrice sets the price.
func (deliveryMethod *DeliveryMethod) SetPrice(price float64) {
	deliveryMethod.price = price
}

func newDeliveryMethod() *DeliveryMethod {
	return &DeliveryMethod{}
}

// New returns a new instance of DeliveryMethodEntity.
func NewDeliveryMethodEntity() DeliveryMethodEntity {
	return newDeliveryMethod()
}
