// Code generated by espal-store-synthesizer. DO NOT EDIT.
package deliverymethod_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/deliverymethod"
)

func TestDeliveryMethodTable(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	if d.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestDeliveryMethodTableAlias(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	if d.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestDeliveryMethodIsUpdated(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	d.IsUpdated()
}

func TestDeliveryMethodID(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	d.ID()
}

func TestDeliveryMethodCreatedByID(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := "testValue"
	d.SetCreatedByID(testValue)
	if testValue != d.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodUpdatedByID(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := "testValue"
	d.SetUpdatedByID(&testValue)
	if &testValue != d.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodCreatedAt(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := time.Now()
	d.SetCreatedAt(testValue)
	if testValue != d.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodUpdatedAt(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := time.Now()
	d.SetUpdatedAt(&testValue)
	if &testValue != d.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodCreatedByFirstName(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := "testValue"
	d.SetCreatedByFirstName(&testValue)
	if &testValue != d.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodCreatedBySurname(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := "testValue"
	d.SetCreatedBySurname(&testValue)
	if &testValue != d.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodUpdatedByFirstName(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := "testValue"
	d.SetUpdatedByFirstName(&testValue)
	if &testValue != d.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodUpdatedBySurname(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := "testValue"
	d.SetUpdatedBySurname(&testValue)
	if &testValue != d.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestDeliveryMethodPrice(t *testing.T) {
	d := deliverymethod.NewDeliveryMethodEntity()
	testValue := 6.28
	d.SetPrice(testValue)
	if testValue != d.Price() {
		t.Fatal("Getter did not return the Set value")
	}
}
