run:
  concurrency: 4
  timeout: 60s
  issues-exit-code: 25
linters-settings:
  nakedret:
    max-func-lines: 40
  gocritic:
    disabled-checks:
      - regexpMust
  funlen:
    lines: 120
    statements: 55
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
    - path: data\.go
      linters:
        - gochecknoglobals
    - linters:
      - gochecknoglobals
      text: "randomStringSrc"
    - linters:
      - godot
      source: "@synthesize"
    # - linters:
    #   - whitespace
    #   source: "stripspace"
linters:
  enable:
    - bodyclose
    - golint
    - stylecheck
    # - gosec # TODO :: The concat queries really need to be fixed, and also quoted
    - interfacer
    - unconvert
    - goconst
    # - gocognit # TODO :: Cleanup
    - asciicheck
    - gofmt
    - goimports
    - depguard # This probably needs custom configuration
    - misspell
    - unparam
    - gochecknoinits
    # - whitespace # The exclude rules for .qtpl aren't working..
    - goprintffuncname
    # - gomnd # TODO :: Cleanup
    # - goerr113 # TODO :: Cleanup
    - gomodguard # This probably needs custom configuration
    - testpackage
    # - nestif # TODO :: Cleanup
    - nolintlint
    - gocyclo
    - lll
    - dogsled
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - funlen
    - godot
    - gochecknoglobals
    - rowserrcheck # It already checks the extra error

    # Unused (mutliple reasons):
    # - dupl # We intentionally use duplicated code in places
    # - maligned # These changes are very small (might be fun for some tweaking later)
    # - godox # Maybe be handy to quickly find TODO's, but might as well just use search
    # - wsl # Too aggressive
