run:
  concurrency: 4
  timeout: 60s
  issues-exit-code: 25
linters-settings:
  nakedret:
    max-func-lines: 40
  gocritic:
    disabled-checks:
      - regexpMust
  funlen:
    lines: 120
    statements: 55
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goerr113
        - gochecknoglobals
    - path: data\.go
      linters:
        - gochecknoglobals
    - linters:
      - gochecknoglobals
      text: "randomStringSrc"
    - linters:
      - godot
      source: "@synthesize"
    - linters:
      - nolintlint
      text: ":gomnd"
    - linters:
      - goerr113
      text: "use errors\\.Is\\(\\) instead" # This recommends native errors, but we use juju
    - linters:
      - gomnd
      source: "Field.SetM(in|ax)(Length|Year)"
linters:
  enable:
    - bodyclose
    - golint
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - goconst
    - gofmt
    - goimports
    # - gocognit # TODO :: Cleanup
    - asciicheck
    - depguard # This probably needs custom configuration
    - misspell
    - unparam
    - gochecknoinits
    - goprintffuncname
    - gomnd
    - goerr113
    - gomodguard # This probably needs custom configuration
    - testpackage
    # - nestif # TODO :: Cleanup
    - nolintlint
    - gocyclo
    - lll
    - dogsled
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - funlen
    - godot
    - gochecknoglobals
    - rowserrcheck

    # Unused (mutliple reasons):
    # - whitespace # The exclude rules for .qtpl aren't working..
    # - dupl # We intentionally use duplicated code in places
    # - maligned # These changes are very small (might be fun for some tweaking later)
    # - godox # Maybe be handy to quickly find TODO's, but might as well just use search
    # - wsl # Too aggressive
