// Code generated by espal-store-synthesizer. DO NOT EDIT.
package cart_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/cart"
)

func TestRuleTable(t *testing.T) {
	rule := cart.NewRuleEntity()
	if rule.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestRuleTableAlias(t *testing.T) {
	rule := cart.NewRuleEntity()
	if rule.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestRuleIsUpdated(t *testing.T) {
	rule := cart.NewRuleEntity()
	rule.IsUpdated()
}

func TestRuleID(t *testing.T) {
	rule := cart.NewRuleEntity()
	rule.ID()
}

func TestRuleCreatedByID(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := "testValue"
	rule.SetCreatedByID(testValue)
	if testValue != rule.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestRuleUpdatedByID(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := "testValue"
	rule.SetUpdatedByID(&testValue)
	if &testValue != rule.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestRuleCreatedAt(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := time.Now()
	rule.SetCreatedAt(testValue)
	if testValue != rule.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestRuleUpdatedAt(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := time.Now()
	rule.SetUpdatedAt(&testValue)
	if &testValue != rule.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestRuleCreatedByFirstName(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := "testValue"
	rule.SetCreatedByFirstName(&testValue)
	if &testValue != rule.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestRuleCreatedBySurname(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := "testValue"
	rule.SetCreatedBySurname(&testValue)
	if &testValue != rule.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestRuleUpdatedByFirstName(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := "testValue"
	rule.SetUpdatedByFirstName(&testValue)
	if &testValue != rule.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestRuleUpdatedBySurname(t *testing.T) {
	rule := cart.NewRuleEntity()
	testValue := "testValue"
	rule.SetUpdatedBySurname(&testValue)
	if &testValue != rule.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}
