package countries

// nolint:gomnd
var data = map[string]Country{
	"AU": {id: 36, code: "AU", englishName: "Australia"},
	"TD": {id: 148, code: "TD", englishName: "Chad"},
	"KN": {id: 659, code: "KN", englishName: "Saint Kitts and Nevis"},
	"DM": {id: 212, code: "DM", englishName: "Dominica"},
	"TN": {id: 788, code: "TN", englishName: "Tunisia"},
	"OM": {id: 512, code: "OM", englishName: "Oman"},
	"RO": {id: 642, code: "RO", englishName: "Romania"},
	"TZ": {id: 834, code: "TZ", englishName: "United Republic of Tanzania"},
	"MW": {id: 454, code: "MW", englishName: "Malawi"},
	"ME": {id: 499, code: "ME", englishName: "Montenegro"},
	"UA": {id: 804, code: "UA", englishName: "Ukraine"},
	"VG": {id: 92, code: "VG", englishName: "British Virgin Islands"},
	"NI": {id: 558, code: "NI", englishName: "Nicaragua"},
	"MM": {id: 104, code: "MM", englishName: "Myanmar"},
	"MR": {id: 478, code: "MR", englishName: "Mauritania"},
	"DJ": {id: 262, code: "DJ", englishName: "Djibouti"},
	"HT": {id: 332, code: "HT", englishName: "Haiti"},
	"NR": {id: 520, code: "NR", englishName: "Nauru"},
	"CX": {id: 162, code: "CX", englishName: "Christmas Island"},
	"UZ": {id: 860, code: "UZ", englishName: "Uzbekistan"},
	"MV": {id: 462, code: "MV", englishName: "Maldives"},
	"KY": {id: 136, code: "KY", englishName: "Cayman Islands"},
	"GN": {id: 324, code: "GN", englishName: "Guinea"},
	"RS": {id: 688, code: "RS", englishName: "Serbia"},
	"PT": {id: 620, code: "PT", englishName: "Portugal"},
	"BH": {id: 48, code: "BH", englishName: "Bahrain"},
	"CD": {id: 180, code: "CD", englishName: "The Democratic Republic of the Congo"},
	"TC": {id: 796, code: "TC", englishName: "Turks and Caicos Islands"},
	"TW": {id: 158, code: "TW", englishName: "Taiwan, Province of China"},
	"AX": {id: 248, code: "AX", englishName: "Åland Islands"},
	"LK": {id: 144, code: "LK", englishName: "Sri Lanka"},
	"LT": {id: 440, code: "LT", englishName: "Lithuania"},
	"GE": {id: 268, code: "GE", englishName: "Georgia"},
	"CC": {id: 166, code: "CC", englishName: "Cocos (Keeling) Islands"},
	"GS": {id: 239, code: "GS", englishName: "South Georgia and the South Sandwich Islands"},
	"SO": {id: 706, code: "SO", englishName: "Somalia"},
	"GB": {id: 826, code: "GB", englishName: "United Kingdom"},
	"AS": {id: 16, code: "AS", englishName: "American Samoa"},
	"LV": {id: 428, code: "LV", englishName: "Latvia"},
	"IL": {id: 376, code: "IL", englishName: "Israel"},
	"CA": {id: 124, code: "CA", englishName: "Canada"},
	"MY": {id: 458, code: "MY", englishName: "Malaysia"},
	"WF": {id: 876, code: "WF", englishName: "Wallis and Futuna"},
	"BI": {id: 108, code: "BI", englishName: "Burundi"},
	"MX": {id: 484, code: "MX", englishName: "Mexico"},
	"HM": {id: 334, code: "HM", englishName: "Heard Island and McDonald Islands"},
	"VN": {id: 704, code: "VN", englishName: "Viet Nam"},
	"RU": {id: 643, code: "RU", englishName: "Russian Federation"},
	"PR": {id: 630, code: "PR", englishName: "Puerto Rico"},
	"VU": {id: 548, code: "VU", englishName: "Vanuatu"},
	"MF": {id: 663, code: "MF", englishName: "Saint Martin (French part)"},
	"LY": {id: 434, code: "LY", englishName: "Libyan Arab Jamahiriya"},
	"PM": {id: 666, code: "PM", englishName: "Saint Pierre and Miquelon"},
	"HR": {id: 191, code: "HR", englishName: "Croatia"},
	"BG": {id: 100, code: "BG", englishName: "Bulgaria"},
	"BT": {id: 64, code: "BT", englishName: "Bhutan"},
	"EH": {id: 732, code: "EH", englishName: "Western Sahara"},
	"AI": {id: 660, code: "AI", englishName: "Anguilla"},
	"MS": {id: 500, code: "MS", englishName: "Montserrat"},
	"SZ": {id: 748, code: "SZ", englishName: "Swaziland"},
	"UM": {id: 581, code: "UM", englishName: "United States Minor Outlying Islands"},
	"AD": {id: 20, code: "AD", englishName: "Andorra"},
	"DZ": {id: 12, code: "DZ", englishName: "Algeria"},
	"LU": {id: 442, code: "LU", englishName: "Luxembourg"},
	"AF": {id: 4, code: "AF", englishName: "Afghanistan"},
	"HK": {id: 344, code: "HK", englishName: "Hong Kong"},
	"BZ": {id: 84, code: "BZ", englishName: "Belize"},
	"GU": {id: 316, code: "GU", englishName: "Guam"},
	"BS": {id: 44, code: "BS", englishName: "Bahamas"},
	"LS": {id: 426, code: "LS", englishName: "Lesotho"},
	"BW": {id: 72, code: "BW", englishName: "Botswana"},
	"ES": {id: 724, code: "ES", englishName: "Spain"},
	"PY": {id: 600, code: "PY", englishName: "Paraguay"},
	"IS": {id: 352, code: "IS", englishName: "Iceland"},
	"GQ": {id: 226, code: "GQ", englishName: "Equatorial Guinea"},
	"BF": {id: 854, code: "BF", englishName: "Burkina Faso"},
	"BR": {id: 76, code: "BR", englishName: "Brazil"},
	"BL": {id: 652, code: "BL", englishName: "Saint Barthelemy"},
	"MU": {id: 480, code: "MU", englishName: "Mauritius"},
	"GY": {id: 328, code: "GY", englishName: "Guyana"},
	"LB": {id: 422, code: "LB", englishName: "Lebanon"},
	"LR": {id: 430, code: "LR", englishName: "Liberia"},
	"PH": {id: 608, code: "PH", englishName: "Philippines"},
	"JO": {id: 400, code: "JO", englishName: "Jordan"},
	"MG": {id: 450, code: "MG", englishName: "Madagascar"},
	"BN": {id: 96, code: "BN", englishName: "Brunei Darussalam"},
	"NO": {id: 578, code: "NO", englishName: "Norway"},
	"AT": {id: 40, code: "AT", englishName: "Austria"},
	"TH": {id: 764, code: "TH", englishName: "Thailand"},
	"TO": {id: 776, code: "TO", englishName: "Tonga"},
	"SI": {id: 705, code: "SI", englishName: "Slovenia"},
	"TK": {id: 772, code: "TK", englishName: "Tokelau"},
	"FK": {id: 238, code: "FK", englishName: "Falkland Islands (Malvinas)"},
	"US": {id: 840, code: "US", englishName: "United States"},
	"UG": {id: 800, code: "UG", englishName: "Uganda"},
	"SM": {id: 674, code: "SM", englishName: "San Marino"},
	"GL": {id: 304, code: "GL", englishName: "Greenland"},
	"GI": {id: 292, code: "GI", englishName: "Gibraltar"},
	"NA": {id: 516, code: "NA", englishName: "Namibia"},
	"SJ": {id: 744, code: "SJ", englishName: "Svalbard and Jan Mayen"},
	"SH": {id: 654, code: "SH", englishName: "Saint Helena, Ascension and Tristan da Cunha"},
	"MT": {id: 470, code: "MT", englishName: "Malta"},
	"PL": {id: 616, code: "PL", englishName: "Poland"},
	"FM": {id: 583, code: "FM", englishName: "Federated States of Micronesia"},
	"BY": {id: 112, code: "BY", englishName: "Belarus"},
	"CN": {id: 156, code: "CN", englishName: "China"},
	"SV": {id: 222, code: "SV", englishName: "El Salvador"},
	"EE": {id: 233, code: "EE", englishName: "Estonia"},
	"BB": {id: 52, code: "BB", englishName: "Barbados"},
	"BM": {id: 60, code: "BM", englishName: "Bermuda"},
	"DK": {id: 208, code: "DK", englishName: "Denmark"},
	"AW": {id: 533, code: "AW", englishName: "Aruba"},
	"SR": {id: 740, code: "SR", englishName: "Suriname"},
	"ML": {id: 466, code: "ML", englishName: "Mali"},
	"TR": {id: 792, code: "TR", englishName: "Turkey"},
	"UY": {id: 858, code: "UY", englishName: "Uruguay"},
	"LC": {id: 662, code: "LC", englishName: "Saint Lucia"},
	"EC": {id: 218, code: "EC", englishName: "Ecuador"},
	"HN": {id: 340, code: "HN", englishName: "Honduras"},
	"PN": {id: 612, code: "PN", englishName: "Pitcairn"},
	"SC": {id: 690, code: "SC", englishName: "Seychelles"},
	"RE": {id: 638, code: "RE", englishName: "Réunion"},
	"PS": {id: 275, code: "PS", englishName: "Occupied Palestinian Territory"},
	"GA": {id: 266, code: "GA", englishName: "Gabon"},
	"CZ": {id: 203, code: "CZ", englishName: "Czech Republic"},
	"VA": {id: 336, code: "VA", englishName: "Holy See (Vatican City State)"},
	"MA": {id: 504, code: "MA", englishName: "Morocco"},
	"NG": {id: 566, code: "NG", englishName: "Nigeria"},
	"MK": {id: 807, code: "MK", englishName: "The Former Yugoslav Republic of Macedonia"},
	"AR": {id: 32, code: "AR", englishName: "Argentina"},
	"IT": {id: 380, code: "IT", englishName: "Italy"},
	"AG": {id: 28, code: "AG", englishName: "Antigua and Barbuda"},
	"VI": {id: 850, code: "VI", englishName: "U.S. Virgin Islands"},
	"AQ": {id: 10, code: "AQ", englishName: "Antarctica"},
	"ZM": {id: 894, code: "ZM", englishName: "Zambia"},
	"LA": {id: 418, code: "LA", englishName: "Lao People's Democratic Republic"},
	"NU": {id: 570, code: "NU", englishName: "Niue"},
	"CY": {id: 196, code: "CY", englishName: "Cyprus"},
	"PG": {id: 598, code: "PG", englishName: "Papua New Guinea"},
	"BV": {id: 74, code: "BV", englishName: "Bouvet Island"},
	"BQ": {id: 535, code: "BQ", englishName: "Bonaire, Saint Eustatius and Saba"},
	"SN": {id: 686, code: "SN", englishName: "Senegal"},
	"ID": {id: 360, code: "ID", englishName: "Indonesia"},
	"FR": {id: 250, code: "FR", englishName: "France"},
	"KE": {id: 404, code: "KE", englishName: "Kenya"},
	"SA": {id: 682, code: "SA", englishName: "Saudi Arabia"},
	"KM": {id: 174, code: "KM", englishName: "Comoros"},
	"PK": {id: 586, code: "PK", englishName: "Pakistan"},
	"BJ": {id: 204, code: "BJ", englishName: "Benin"},
	"PF": {id: 258, code: "PF", englishName: "French Polynesia"},
	"AO": {id: 24, code: "AO", englishName: "Angola"},
	"JM": {id: 388, code: "JM", englishName: "Jamaica"},
	"NF": {id: 574, code: "NF", englishName: "Norfolk Island"},
	"GR": {id: 300, code: "GR", englishName: "Greece"},
	"VC": {id: 670, code: "VC", englishName: "Saint Vincent and The Grenadines"},
	"MO": {id: 446, code: "MO", englishName: "Macao"},
	"ET": {id: 231, code: "ET", englishName: "Ethiopia"},
	"KW": {id: 414, code: "KW", englishName: "Kuwait"},
	"BA": {id: 70, code: "BA", englishName: "Bosnia and Herzegovina"},
	"SL": {id: 694, code: "SL", englishName: "Sierra Leone"},
	"SE": {id: 752, code: "SE", englishName: "Sweden"},
	"CI": {id: 384, code: "CI", englishName: "Côte d'Ivoire"},
	"MC": {id: 492, code: "MC", englishName: "Monaco"},
	"YE": {id: 887, code: "YE", englishName: "Yemen"},
	"MP": {id: 580, code: "MP", englishName: "Northern Mariana Islands"},
	"FJ": {id: 242, code: "FJ", englishName: "Fiji"},
	"CR": {id: 188, code: "CR", englishName: "Costa Rica"},
	"HU": {id: 348, code: "HU", englishName: "Hungary"},
	"AM": {id: 51, code: "AM", englishName: "Armenia"},
	"GF": {id: 254, code: "GF", englishName: "French Guiana"},
	"JE": {id: 832, code: "JE", englishName: "Jersey"},
	"BO": {id: 68, code: "BO", englishName: "Plurinational State of Bolivia"},
	"MD": {id: 498, code: "MD", englishName: "Republic of Moldova"},
	"CH": {id: 756, code: "CH", englishName: "Switzerland"},
	"IR": {id: 364, code: "IR", englishName: "Islamic Republic of Iran"},
	"NL": {id: 528, code: "NL", englishName: "Netherlands"},
	"NP": {id: 524, code: "NP", englishName: "Nepal"},
	"MH": {id: 584, code: "MH", englishName: "Marshall Islands"},
	"SD": {id: 736, code: "SD", englishName: "Sudan"},
	"KH": {id: 116, code: "KH", englishName: "Cambodia"},
	"SG": {id: 702, code: "SG", englishName: "Singapore"},
	"CM": {id: 120, code: "CM", englishName: "Cameroon"},
	"SB": {id: 90, code: "SB", englishName: "Solomon Islands"},
	"CU": {id: 192, code: "CU", englishName: "Cuba"},
	"DO": {id: 214, code: "DO", englishName: "Dominican Republic"},
	"CO": {id: 170, code: "CO", englishName: "Colombia"},
	"CW": {id: 531, code: "CW", englishName: "Curaçao"},
	"TT": {id: 780, code: "TT", englishName: "Trinidad and Tobago"},
	"TM": {id: 795, code: "TM", englishName: "Turkmenistan"},
	"YT": {id: 175, code: "YT", englishName: "Mayotte"},
	"SK": {id: 703, code: "SK", englishName: "Slovakia"},
	"IO": {id: 86, code: "IO", englishName: "British Indian Ocean Territory"},
	"IN": {id: 356, code: "IN", englishName: "India"},
	"TL": {id: 626, code: "TL", englishName: "Timor-Leste"},
	"FI": {id: 246, code: "FI", englishName: "Finland"},
	"IM": {id: 833, code: "IM", englishName: "Isle of Man"},
	"EG": {id: 818, code: "EG", englishName: "Egypt"},
	"GD": {id: 308, code: "GD", englishName: "Grenada"},
	"GM": {id: 270, code: "GM", englishName: "Gambia"},
	"GH": {id: 288, code: "GH", englishName: "Ghana"},
	"CL": {id: 152, code: "CL", englishName: "Chile"},
	"MN": {id: 496, code: "MN", englishName: "Mongolia"},
	"ER": {id: 232, code: "ER", englishName: "Eritrea"},
	"KI": {id: 296, code: "KI", englishName: "Kiribati"},
	"DE": {id: 276, code: "DE", englishName: "Germany"},
	"SY": {id: 760, code: "SY", englishName: "Syrian Arab Republic"},
	"PE": {id: 604, code: "PE", englishName: "Peru"},
	"KP": {id: 408, code: "KP", englishName: "Democratic People's Republic of Korea"},
	"ST": {id: 678, code: "ST", englishName: "Sao Tome and Principe"},
	"LI": {id: 438, code: "LI", englishName: "Liechtenstein"},
	"TF": {id: 260, code: "TF", englishName: "French Southern Territories"},
	"GG": {id: 831, code: "GG", englishName: "Guernsey"},
	"CV": {id: 132, code: "CV", englishName: "Cape Verde"},
	"ZW": {id: 716, code: "ZW", englishName: "Zimbabwe"},
	"QA": {id: 634, code: "QA", englishName: "Qatar"},
	"TJ": {id: 762, code: "TJ", englishName: "Tajikistan"},
	"PW": {id: 585, code: "PW", englishName: "Palau"},
	"CF": {id: 140, code: "CF", englishName: "Central African Republic"},
	"AE": {id: 784, code: "AE", englishName: "United Arab Emirates"},
	"NE": {id: 562, code: "NE", englishName: "Niger"},
	"AL": {id: 8, code: "AL", englishName: "Albania"},
	"VE": {id: 862, code: "VE", englishName: "Bolivarian Republic of Venezuela"},
	"MQ": {id: 474, code: "MQ", englishName: "Martinique"},
	"GW": {id: 624, code: "GW", englishName: "Guinea-Bissau"},
	"IE": {id: 372, code: "IE", englishName: "Ireland"},
	"GP": {id: 312, code: "GP", englishName: "Guadeloupe"},
	"IQ": {id: 368, code: "IQ", englishName: "Iraq"},
	"BD": {id: 50, code: "BD", englishName: "Bangladesh"},
	"CK": {id: 184, code: "CK", englishName: "Cook Islands"},
	"NC": {id: 540, code: "NC", englishName: "New Caledonia"},
	"CG": {id: 178, code: "CG", englishName: "Congo"},
	"MZ": {id: 508, code: "MZ", englishName: "Mozambique"},
	"ZA": {id: 710, code: "ZA", englishName: "South Africa"},
	"TV": {id: 798, code: "TV", englishName: "Tuvalu"},
	"KR": {id: 410, code: "KR", englishName: "Republic of Korea"},
	"WS": {id: 882, code: "WS", englishName: "Samoa"},
	"AZ": {id: 31, code: "AZ", englishName: "Azerbaijan"},
	"PA": {id: 591, code: "PA", englishName: "Panama"},
	"GT": {id: 320, code: "GT", englishName: "Guatemala"},
	"KZ": {id: 398, code: "KZ", englishName: "Kazakhstan"},
	"BE": {id: 56, code: "BE", englishName: "Belgium"},
	"KG": {id: 417, code: "KG", englishName: "Kyrgyzstan"},
	"RW": {id: 646, code: "RW", englishName: "Rwanda"},
	"SX": {id: 534, code: "SX", englishName: "Sint Maarten (Dutch part)"},
	"JP": {id: 392, code: "JP", englishName: "Japan"},
	"TG": {id: 768, code: "TG", englishName: "Togo"},
	"FO": {id: 234, code: "FO", englishName: "Faroe Islands"},
	"NZ": {id: 554, code: "NZ", englishName: "New Zealand"},
}
