// Code generated by espal-store-synthesizer. DO NOT EDIT.
package saleorder

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ SaleOrderEntity = &SaleOrder{}

type SaleOrderEntity interface {
	database.Model
	UserID() string
	SetUserID(userID string)
	DomainID() string
	SetDomainID(domainID string)
	Currency() uint16
	SetCurrency(currency uint16)
	Code() *string
	SetCode(code *string)
	UserInfoBusiness() bool
	SetUserInfoBusiness(userInfoBusiness bool)
	UserInfoBusinessCocNumber() *string
	SetUserInfoBusinessCocNumber(userInfoBusinessCocNumber *string)
	UserInfoFirstName() string
	SetUserInfoFirstName(userInfoFirstName string)
	UserInfoSurname() string
	SetUserInfoSurname(userInfoSurname string)
	UserInfoStreet() string
	SetUserInfoStreet(userInfoStreet string)
	UserInfoStreetLine2() *string
	SetUserInfoStreetLine2(userInfoStreetLine2 *string)
	UserInfoNumber() string
	SetUserInfoNumber(userInfoNumber string)
	UserInfoNumberAddition() *string
	SetUserInfoNumberAddition(userInfoNumberAddition *string)
	UserInfoZipCode() string
	SetUserInfoZipCode(userInfoZipCode string)
	UserInfoCity() string
	SetUserInfoCity(userInfoCity string)
	UserInfoState() *uint
	SetUserInfoState(userInfoState *uint)
	UserInfoCountry() *uint16
	SetUserInfoCountry(userInfoCountry *uint16)
	UserInfoPhoneNumber() *string
	SetUserInfoPhoneNumber(userInfoPhoneNumber *string)
	UserInfoEmail() *string
	SetUserInfoEmail(userInfoEmail *string)
	ShippingAddressBusiness() bool
	SetShippingAddressBusiness(shippingAddressBusiness bool)
	ShippingAddressBusinessCocNumber() *string
	SetShippingAddressBusinessCocNumber(shippingAddressBusinessCocNumber *string)
	ShippingAddressFirstName() string
	SetShippingAddressFirstName(shippingAddressFirstName string)
	ShippingAddressSurname() string
	SetShippingAddressSurname(shippingAddressSurname string)
	ShippingAddressStreet() string
	SetShippingAddressStreet(shippingAddressStreet string)
	ShippingAddressStreetLine2() *string
	SetShippingAddressStreetLine2(shippingAddressStreetLine2 *string)
	ShippingAddressNumber() string
	SetShippingAddressNumber(shippingAddressNumber string)
	ShippingAddressNumberAddition() *string
	SetShippingAddressNumberAddition(shippingAddressNumberAddition *string)
	ShippingAddressZipCode() string
	SetShippingAddressZipCode(shippingAddressZipCode string)
	ShippingAddressCity() string
	SetShippingAddressCity(shippingAddressCity string)
	ShippingAddressState() *uint
	SetShippingAddressState(shippingAddressState *uint)
	ShippingAddressCountry() *uint16
	SetShippingAddressCountry(shippingAddressCountry *uint16)
	ShippingAddressPhoneNumber() *string
	SetShippingAddressPhoneNumber(shippingAddressPhoneNumber *string)
	ShippingAddressEmail() *string
	SetShippingAddressEmail(shippingAddressEmail *string)
	Comments() *string
	SetComments(comments *string)
	SellingPartyAutograph() *string
	SetSellingPartyAutograph(sellingPartyAutograph *string)
	BuyingPartyAutograph() *string
	SetBuyingPartyAutograph(buyingPartyAutograph *string)
	SaleOfferID() *string
	SetSaleOfferID(saleOfferID *string)
}

// TableName returns the table name that belongs to the current model.
func (s *SaleOrder) TableName() string {
	return "SaleOrder"
}

// TableAlias returns the unique resolved table alias for use in queries.
func (s *SaleOrder) TableAlias() string {
	return "soe"
}

// ID returns id.
func (s *SaleOrder) ID() string {
	return s.id
}

// CreatedByID returns createdByID.
func (s *SaleOrder) CreatedByID() string {
	return s.createdByID
}

// SetCreatedByID sets the createdByID.
func (s *SaleOrder) SetCreatedByID(createdByID string) {
	s.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (s *SaleOrder) UpdatedByID() *string {
	return s.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (s *SaleOrder) SetUpdatedByID(updatedByID *string) {
	s.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (s *SaleOrder) CreatedAt() time.Time {
	return s.createdAt
}

// SetCreatedAt sets the createdAt.
func (s *SaleOrder) SetCreatedAt(createdAt time.Time) {
	s.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (s *SaleOrder) UpdatedAt() *time.Time {
	return s.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (s *SaleOrder) SetUpdatedAt(updatedAt *time.Time) {
	s.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (s *SaleOrder) CreatedByFirstName() *string {
	return s.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (s *SaleOrder) SetCreatedByFirstName(createdByFirstName *string) {
	s.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (s *SaleOrder) CreatedBySurname() *string {
	return s.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (s *SaleOrder) SetCreatedBySurname(createdBySurname *string) {
	s.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (s *SaleOrder) UpdatedByFirstName() *string {
	return s.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (s *SaleOrder) SetUpdatedByFirstName(updatedByFirstName *string) {
	s.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (s *SaleOrder) UpdatedBySurname() *string {
	return s.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (s *SaleOrder) SetUpdatedBySurname(updatedBySurname *string) {
	s.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (s *SaleOrder) IsUpdated() bool {
	return s.updatedByID != nil
}

// UserID returns userID.
func (s *SaleOrder) UserID() string {
	return s.userID
}

// SetUserID sets the userID.
func (s *SaleOrder) SetUserID(userID string) {
	s.userID = userID
}

// DomainID returns domainID.
func (s *SaleOrder) DomainID() string {
	return s.domainID
}

// SetDomainID sets the domainID.
func (s *SaleOrder) SetDomainID(domainID string) {
	s.domainID = domainID
}

// Currency returns currency.
func (s *SaleOrder) Currency() uint16 {
	return s.currency
}

// SetCurrency sets the currency.
func (s *SaleOrder) SetCurrency(currency uint16) {
	s.currency = currency
}

// Code returns code.
func (s *SaleOrder) Code() *string {
	return s.code
}

// SetCode sets the code.
func (s *SaleOrder) SetCode(code *string) {
	s.code = code
}

// UserInfoBusiness returns userInfoBusiness.
func (s *SaleOrder) UserInfoBusiness() bool {
	return s.userInfoBusiness
}

// SetUserInfoBusiness sets the userInfoBusiness.
func (s *SaleOrder) SetUserInfoBusiness(userInfoBusiness bool) {
	s.userInfoBusiness = userInfoBusiness
}

// UserInfoBusinessCocNumber returns userInfoBusinessCocNumber.
func (s *SaleOrder) UserInfoBusinessCocNumber() *string {
	return s.userInfoBusinessCocNumber
}

// SetUserInfoBusinessCocNumber sets the userInfoBusinessCocNumber.
func (s *SaleOrder) SetUserInfoBusinessCocNumber(userInfoBusinessCocNumber *string) {
	s.userInfoBusinessCocNumber = userInfoBusinessCocNumber
}

// UserInfoFirstName returns userInfoFirstName.
func (s *SaleOrder) UserInfoFirstName() string {
	return s.userInfoFirstName
}

// SetUserInfoFirstName sets the userInfoFirstName.
func (s *SaleOrder) SetUserInfoFirstName(userInfoFirstName string) {
	s.userInfoFirstName = userInfoFirstName
}

// UserInfoSurname returns userInfoSurname.
func (s *SaleOrder) UserInfoSurname() string {
	return s.userInfoSurname
}

// SetUserInfoSurname sets the userInfoSurname.
func (s *SaleOrder) SetUserInfoSurname(userInfoSurname string) {
	s.userInfoSurname = userInfoSurname
}

// UserInfoStreet returns userInfoStreet.
func (s *SaleOrder) UserInfoStreet() string {
	return s.userInfoStreet
}

// SetUserInfoStreet sets the userInfoStreet.
func (s *SaleOrder) SetUserInfoStreet(userInfoStreet string) {
	s.userInfoStreet = userInfoStreet
}

// UserInfoStreetLine2 returns userInfoStreetLine2.
func (s *SaleOrder) UserInfoStreetLine2() *string {
	return s.userInfoStreetLine2
}

// SetUserInfoStreetLine2 sets the userInfoStreetLine2.
func (s *SaleOrder) SetUserInfoStreetLine2(userInfoStreetLine2 *string) {
	s.userInfoStreetLine2 = userInfoStreetLine2
}

// UserInfoNumber returns userInfoNumber.
func (s *SaleOrder) UserInfoNumber() string {
	return s.userInfoNumber
}

// SetUserInfoNumber sets the userInfoNumber.
func (s *SaleOrder) SetUserInfoNumber(userInfoNumber string) {
	s.userInfoNumber = userInfoNumber
}

// UserInfoNumberAddition returns userInfoNumberAddition.
func (s *SaleOrder) UserInfoNumberAddition() *string {
	return s.userInfoNumberAddition
}

// SetUserInfoNumberAddition sets the userInfoNumberAddition.
func (s *SaleOrder) SetUserInfoNumberAddition(userInfoNumberAddition *string) {
	s.userInfoNumberAddition = userInfoNumberAddition
}

// UserInfoZipCode returns userInfoZipCode.
func (s *SaleOrder) UserInfoZipCode() string {
	return s.userInfoZipCode
}

// SetUserInfoZipCode sets the userInfoZipCode.
func (s *SaleOrder) SetUserInfoZipCode(userInfoZipCode string) {
	s.userInfoZipCode = userInfoZipCode
}

// UserInfoCity returns userInfoCity.
func (s *SaleOrder) UserInfoCity() string {
	return s.userInfoCity
}

// SetUserInfoCity sets the userInfoCity.
func (s *SaleOrder) SetUserInfoCity(userInfoCity string) {
	s.userInfoCity = userInfoCity
}

// UserInfoState returns userInfoState.
func (s *SaleOrder) UserInfoState() *uint {
	return s.userInfoState
}

// SetUserInfoState sets the userInfoState.
func (s *SaleOrder) SetUserInfoState(userInfoState *uint) {
	s.userInfoState = userInfoState
}

// UserInfoCountry returns userInfoCountry.
func (s *SaleOrder) UserInfoCountry() *uint16 {
	return s.userInfoCountry
}

// SetUserInfoCountry sets the userInfoCountry.
func (s *SaleOrder) SetUserInfoCountry(userInfoCountry *uint16) {
	s.userInfoCountry = userInfoCountry
}

// UserInfoPhoneNumber returns userInfoPhoneNumber.
func (s *SaleOrder) UserInfoPhoneNumber() *string {
	return s.userInfoPhoneNumber
}

// SetUserInfoPhoneNumber sets the userInfoPhoneNumber.
func (s *SaleOrder) SetUserInfoPhoneNumber(userInfoPhoneNumber *string) {
	s.userInfoPhoneNumber = userInfoPhoneNumber
}

// UserInfoEmail returns userInfoEmail.
func (s *SaleOrder) UserInfoEmail() *string {
	return s.userInfoEmail
}

// SetUserInfoEmail sets the userInfoEmail.
func (s *SaleOrder) SetUserInfoEmail(userInfoEmail *string) {
	s.userInfoEmail = userInfoEmail
}

// ShippingAddressBusiness returns shippingAddressBusiness.
func (s *SaleOrder) ShippingAddressBusiness() bool {
	return s.shippingAddressBusiness
}

// SetShippingAddressBusiness sets the shippingAddressBusiness.
func (s *SaleOrder) SetShippingAddressBusiness(shippingAddressBusiness bool) {
	s.shippingAddressBusiness = shippingAddressBusiness
}

// ShippingAddressBusinessCocNumber returns shippingAddressBusinessCocNumber.
func (s *SaleOrder) ShippingAddressBusinessCocNumber() *string {
	return s.shippingAddressBusinessCocNumber
}

// SetShippingAddressBusinessCocNumber sets the shippingAddressBusinessCocNumber.
func (s *SaleOrder) SetShippingAddressBusinessCocNumber(shippingAddressBusinessCocNumber *string) {
	s.shippingAddressBusinessCocNumber = shippingAddressBusinessCocNumber
}

// ShippingAddressFirstName returns shippingAddressFirstName.
func (s *SaleOrder) ShippingAddressFirstName() string {
	return s.shippingAddressFirstName
}

// SetShippingAddressFirstName sets the shippingAddressFirstName.
func (s *SaleOrder) SetShippingAddressFirstName(shippingAddressFirstName string) {
	s.shippingAddressFirstName = shippingAddressFirstName
}

// ShippingAddressSurname returns shippingAddressSurname.
func (s *SaleOrder) ShippingAddressSurname() string {
	return s.shippingAddressSurname
}

// SetShippingAddressSurname sets the shippingAddressSurname.
func (s *SaleOrder) SetShippingAddressSurname(shippingAddressSurname string) {
	s.shippingAddressSurname = shippingAddressSurname
}

// ShippingAddressStreet returns shippingAddressStreet.
func (s *SaleOrder) ShippingAddressStreet() string {
	return s.shippingAddressStreet
}

// SetShippingAddressStreet sets the shippingAddressStreet.
func (s *SaleOrder) SetShippingAddressStreet(shippingAddressStreet string) {
	s.shippingAddressStreet = shippingAddressStreet
}

// ShippingAddressStreetLine2 returns shippingAddressStreetLine2.
func (s *SaleOrder) ShippingAddressStreetLine2() *string {
	return s.shippingAddressStreetLine2
}

// SetShippingAddressStreetLine2 sets the shippingAddressStreetLine2.
func (s *SaleOrder) SetShippingAddressStreetLine2(shippingAddressStreetLine2 *string) {
	s.shippingAddressStreetLine2 = shippingAddressStreetLine2
}

// ShippingAddressNumber returns shippingAddressNumber.
func (s *SaleOrder) ShippingAddressNumber() string {
	return s.shippingAddressNumber
}

// SetShippingAddressNumber sets the shippingAddressNumber.
func (s *SaleOrder) SetShippingAddressNumber(shippingAddressNumber string) {
	s.shippingAddressNumber = shippingAddressNumber
}

// ShippingAddressNumberAddition returns shippingAddressNumberAddition.
func (s *SaleOrder) ShippingAddressNumberAddition() *string {
	return s.shippingAddressNumberAddition
}

// SetShippingAddressNumberAddition sets the shippingAddressNumberAddition.
func (s *SaleOrder) SetShippingAddressNumberAddition(shippingAddressNumberAddition *string) {
	s.shippingAddressNumberAddition = shippingAddressNumberAddition
}

// ShippingAddressZipCode returns shippingAddressZipCode.
func (s *SaleOrder) ShippingAddressZipCode() string {
	return s.shippingAddressZipCode
}

// SetShippingAddressZipCode sets the shippingAddressZipCode.
func (s *SaleOrder) SetShippingAddressZipCode(shippingAddressZipCode string) {
	s.shippingAddressZipCode = shippingAddressZipCode
}

// ShippingAddressCity returns shippingAddressCity.
func (s *SaleOrder) ShippingAddressCity() string {
	return s.shippingAddressCity
}

// SetShippingAddressCity sets the shippingAddressCity.
func (s *SaleOrder) SetShippingAddressCity(shippingAddressCity string) {
	s.shippingAddressCity = shippingAddressCity
}

// ShippingAddressState returns shippingAddressState.
func (s *SaleOrder) ShippingAddressState() *uint {
	return s.shippingAddressState
}

// SetShippingAddressState sets the shippingAddressState.
func (s *SaleOrder) SetShippingAddressState(shippingAddressState *uint) {
	s.shippingAddressState = shippingAddressState
}

// ShippingAddressCountry returns shippingAddressCountry.
func (s *SaleOrder) ShippingAddressCountry() *uint16 {
	return s.shippingAddressCountry
}

// SetShippingAddressCountry sets the shippingAddressCountry.
func (s *SaleOrder) SetShippingAddressCountry(shippingAddressCountry *uint16) {
	s.shippingAddressCountry = shippingAddressCountry
}

// ShippingAddressPhoneNumber returns shippingAddressPhoneNumber.
func (s *SaleOrder) ShippingAddressPhoneNumber() *string {
	return s.shippingAddressPhoneNumber
}

// SetShippingAddressPhoneNumber sets the shippingAddressPhoneNumber.
func (s *SaleOrder) SetShippingAddressPhoneNumber(shippingAddressPhoneNumber *string) {
	s.shippingAddressPhoneNumber = shippingAddressPhoneNumber
}

// ShippingAddressEmail returns shippingAddressEmail.
func (s *SaleOrder) ShippingAddressEmail() *string {
	return s.shippingAddressEmail
}

// SetShippingAddressEmail sets the shippingAddressEmail.
func (s *SaleOrder) SetShippingAddressEmail(shippingAddressEmail *string) {
	s.shippingAddressEmail = shippingAddressEmail
}

// Comments returns comments.
func (s *SaleOrder) Comments() *string {
	return s.comments
}

// SetComments sets the comments.
func (s *SaleOrder) SetComments(comments *string) {
	s.comments = comments
}

// SellingPartyAutograph returns sellingPartyAutograph.
func (s *SaleOrder) SellingPartyAutograph() *string {
	return s.sellingPartyAutograph
}

// SetSellingPartyAutograph sets the sellingPartyAutograph.
func (s *SaleOrder) SetSellingPartyAutograph(sellingPartyAutograph *string) {
	s.sellingPartyAutograph = sellingPartyAutograph
}

// BuyingPartyAutograph returns buyingPartyAutograph.
func (s *SaleOrder) BuyingPartyAutograph() *string {
	return s.buyingPartyAutograph
}

// SetBuyingPartyAutograph sets the buyingPartyAutograph.
func (s *SaleOrder) SetBuyingPartyAutograph(buyingPartyAutograph *string) {
	s.buyingPartyAutograph = buyingPartyAutograph
}

// SaleOfferID returns saleOfferID.
func (s *SaleOrder) SaleOfferID() *string {
	return s.saleOfferID
}

// SetSaleOfferID sets the saleOfferID.
func (s *SaleOrder) SetSaleOfferID(saleOfferID *string) {
	s.saleOfferID = saleOfferID
}

func newSaleOrder() *SaleOrder {
	return &SaleOrder{}
}

// New returns a new instance of SaleOrderEntity.
func NewSaleOrderEntity() SaleOrderEntity {
	return newSaleOrder()
}
