// Code generated by espal-store-synthesizer. DO NOT EDIT.
package group

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ PropertyEntity = &Property{}

type PropertyEntity interface {
	database.Model
	PropertyGroupID() string
	SetPropertyGroupID(propertyGroupID string)
	PropertyID() string
	SetPropertyID(propertyID string)
}

// ID returns id.
func (p *Property) ID() string {
	return p.id
}

// CreatedByID returns createdByID.
func (p *Property) CreatedByID() string {
	return p.createdByID
}

// SetCreatedByID sets the createdByID.
func (p *Property) SetCreatedByID(createdByID string) {
	p.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (p *Property) UpdatedByID() *string {
	return p.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (p *Property) SetUpdatedByID(updatedByID *string) {
	p.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (p *Property) CreatedAt() time.Time {
	return p.createdAt
}

// SetCreatedAt sets the createdAt.
func (p *Property) SetCreatedAt(createdAt time.Time) {
	p.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (p *Property) UpdatedAt() *time.Time {
	return p.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (p *Property) SetUpdatedAt(updatedAt *time.Time) {
	p.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (p *Property) CreatedByFirstName() *string {
	return p.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (p *Property) SetCreatedByFirstName(createdByFirstName *string) {
	p.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (p *Property) CreatedBySurname() *string {
	return p.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (p *Property) SetCreatedBySurname(createdBySurname *string) {
	p.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (p *Property) UpdatedByFirstName() *string {
	return p.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (p *Property) SetUpdatedByFirstName(updatedByFirstName *string) {
	p.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (p *Property) UpdatedBySurname() *string {
	return p.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (p *Property) SetUpdatedBySurname(updatedBySurname *string) {
	p.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (p *Property) IsUpdated() bool {
	return p.updatedByID != nil
}

// PropertyGroupID returns propertyGroupID.
func (p *Property) PropertyGroupID() string {
	return p.propertyGroupID
}

// SetPropertyGroupID sets the propertyGroupID.
func (p *Property) SetPropertyGroupID(propertyGroupID string) {
	p.propertyGroupID = propertyGroupID
}

// PropertyID returns propertyID.
func (p *Property) PropertyID() string {
	return p.propertyID
}

// SetPropertyID sets the propertyID.
func (p *Property) SetPropertyID(propertyID string) {
	p.propertyID = propertyID
}

func newProperty() *Property {
	return &Property{}
}

// New returns a new instance of PropertyEntity.
func NewPropertyEntity() PropertyEntity {
	return newProperty()
}
