// Code generated by espal-store-synthesizer. DO NOT EDIT.
package property

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ OptionTranslationEntity = &OptionTranslation{}

type OptionTranslationEntity interface {
	database.TranslationModel
	OptionID() string
	SetOptionID(optionID string)
}

// ID returns id.
func (optionTranslation *OptionTranslation) ID() string {
	return optionTranslation.id
}

// CreatedByID returns createdByID.
func (optionTranslation *OptionTranslation) CreatedByID() string {
	return optionTranslation.createdByID
}

// SetCreatedByID sets the createdByID.
func (optionTranslation *OptionTranslation) SetCreatedByID(createdByID string) {
	optionTranslation.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (optionTranslation *OptionTranslation) UpdatedByID() *string {
	return optionTranslation.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (optionTranslation *OptionTranslation) SetUpdatedByID(updatedByID *string) {
	optionTranslation.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (optionTranslation *OptionTranslation) CreatedAt() time.Time {
	return optionTranslation.createdAt
}

// SetCreatedAt sets the createdAt.
func (optionTranslation *OptionTranslation) SetCreatedAt(createdAt time.Time) {
	optionTranslation.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (optionTranslation *OptionTranslation) UpdatedAt() *time.Time {
	return optionTranslation.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (optionTranslation *OptionTranslation) SetUpdatedAt(updatedAt *time.Time) {
	optionTranslation.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (optionTranslation *OptionTranslation) CreatedByFirstName() *string {
	return optionTranslation.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (optionTranslation *OptionTranslation) SetCreatedByFirstName(createdByFirstName *string) {
	optionTranslation.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (optionTranslation *OptionTranslation) CreatedBySurname() *string {
	return optionTranslation.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (optionTranslation *OptionTranslation) SetCreatedBySurname(createdBySurname *string) {
	optionTranslation.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (optionTranslation *OptionTranslation) UpdatedByFirstName() *string {
	return optionTranslation.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (optionTranslation *OptionTranslation) SetUpdatedByFirstName(updatedByFirstName *string) {
	optionTranslation.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (optionTranslation *OptionTranslation) UpdatedBySurname() *string {
	return optionTranslation.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (optionTranslation *OptionTranslation) SetUpdatedBySurname(updatedBySurname *string) {
	optionTranslation.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (optionTranslation *OptionTranslation) IsUpdated() bool {
	return optionTranslation.updatedByID != nil
}

// Language returns language.
func (optionTranslation *OptionTranslation) Language() uint16 {
	return optionTranslation.language
}

// SetLanguage sets the language.
func (optionTranslation *OptionTranslation) SetLanguage(language uint16) {
	optionTranslation.language = language
}

// Field returns field.
func (optionTranslation *OptionTranslation) Field() uint16 {
	return optionTranslation.field
}

// SetField sets the field.
func (optionTranslation *OptionTranslation) SetField(field uint16) {
	optionTranslation.field = field
}

// Value returns value.
func (optionTranslation *OptionTranslation) Value() string {
	return optionTranslation.value
}

// SetValue sets the value.
func (optionTranslation *OptionTranslation) SetValue(value string) {
	optionTranslation.value = value
}

// OptionID returns optionID.
func (optionTranslation *OptionTranslation) OptionID() string {
	return optionTranslation.optionID
}

// SetOptionID sets the optionID.
func (optionTranslation *OptionTranslation) SetOptionID(optionID string) {
	optionTranslation.optionID = optionID
}

func newOptionTranslation() *OptionTranslation {
	return &OptionTranslation{}
}

// New returns a new instance of OptionTranslationEntity.
func NewOptionTranslationEntity() OptionTranslationEntity {
	return newOptionTranslation()
}
