// Code generated by espal-store-synthesizer. DO NOT EDIT.
package property

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ PropertyEntity = &Property{}

type PropertyEntity interface {
	database.Model
	UnitID() *string
	SetUnitID(unitID *string)
	Active() bool
	SetActive(active bool)
	Sorting() uint
	SetSorting(sorting uint)
	Key() *string
	SetKey(key *string)
	Type() uint8
	SetType(_type uint8)
	MultiLingual() bool
	SetMultiLingual(multiLingual bool)
}

// TableName returns the table name that belongs to the current model.
func (property *Property) TableName() string {
	return "Property"
}

// ID returns id.
func (property *Property) ID() string {
	return property.id
}

// CreatedByID returns createdByID.
func (property *Property) CreatedByID() string {
	return property.createdByID
}

// SetCreatedByID sets the createdByID.
func (property *Property) SetCreatedByID(createdByID string) {
	property.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (property *Property) UpdatedByID() *string {
	return property.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (property *Property) SetUpdatedByID(updatedByID *string) {
	property.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (property *Property) CreatedAt() time.Time {
	return property.createdAt
}

// SetCreatedAt sets the createdAt.
func (property *Property) SetCreatedAt(createdAt time.Time) {
	property.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (property *Property) UpdatedAt() *time.Time {
	return property.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (property *Property) SetUpdatedAt(updatedAt *time.Time) {
	property.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (property *Property) CreatedByFirstName() *string {
	return property.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (property *Property) SetCreatedByFirstName(createdByFirstName *string) {
	property.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (property *Property) CreatedBySurname() *string {
	return property.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (property *Property) SetCreatedBySurname(createdBySurname *string) {
	property.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (property *Property) UpdatedByFirstName() *string {
	return property.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (property *Property) SetUpdatedByFirstName(updatedByFirstName *string) {
	property.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (property *Property) UpdatedBySurname() *string {
	return property.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (property *Property) SetUpdatedBySurname(updatedBySurname *string) {
	property.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (property *Property) IsUpdated() bool {
	return property.updatedByID != nil
}

// UnitID returns unitID.
func (property *Property) UnitID() *string {
	return property.unitID
}

// SetUnitID sets the unitID.
func (property *Property) SetUnitID(unitID *string) {
	property.unitID = unitID
}

// Active returns active.
func (property *Property) Active() bool {
	return property.active
}

// SetActive sets the active.
func (property *Property) SetActive(active bool) {
	property.active = active
}

// Sorting returns sorting.
func (property *Property) Sorting() uint {
	return property.sorting
}

// SetSorting sets the sorting.
func (property *Property) SetSorting(sorting uint) {
	property.sorting = sorting
}

// Key returns key.
func (property *Property) Key() *string {
	return property.key
}

// SetKey sets the key.
func (property *Property) SetKey(key *string) {
	property.key = key
}

// Type returns _type.
func (property *Property) Type() uint8 {
	return property._type
}

// SetType sets the _type.
func (property *Property) SetType(_type uint8) {
	property._type = _type
}

// MultiLingual returns multiLingual.
func (property *Property) MultiLingual() bool {
	return property.multiLingual
}

// SetMultiLingual sets the multiLingual.
func (property *Property) SetMultiLingual(multiLingual bool) {
	property.multiLingual = multiLingual
}

func newProperty() *Property {
	return &Property{}
}

// New returns a new instance of PropertyEntity.
func NewPropertyEntity() PropertyEntity {
	return newProperty()
}
