// Code generated by espal-store-synthesizer. DO NOT EDIT.
package property

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ UnitTranslationEntity = &UnitTranslation{}

type UnitTranslationEntity interface {
	database.TranslationModel
	UnitID() string
	SetUnitID(unitID string)
	Display() *string
	SetDisplay(display *string)
}

// ID returns id.
func (unitTranslation *UnitTranslation) ID() string {
	return unitTranslation.id
}

// CreatedByID returns createdByID.
func (unitTranslation *UnitTranslation) CreatedByID() string {
	return unitTranslation.createdByID
}

// SetCreatedByID sets the createdByID.
func (unitTranslation *UnitTranslation) SetCreatedByID(createdByID string) {
	unitTranslation.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (unitTranslation *UnitTranslation) UpdatedByID() *string {
	return unitTranslation.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (unitTranslation *UnitTranslation) SetUpdatedByID(updatedByID *string) {
	unitTranslation.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (unitTranslation *UnitTranslation) CreatedAt() time.Time {
	return unitTranslation.createdAt
}

// SetCreatedAt sets the createdAt.
func (unitTranslation *UnitTranslation) SetCreatedAt(createdAt time.Time) {
	unitTranslation.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (unitTranslation *UnitTranslation) UpdatedAt() *time.Time {
	return unitTranslation.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (unitTranslation *UnitTranslation) SetUpdatedAt(updatedAt *time.Time) {
	unitTranslation.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (unitTranslation *UnitTranslation) CreatedByFirstName() *string {
	return unitTranslation.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (unitTranslation *UnitTranslation) SetCreatedByFirstName(createdByFirstName *string) {
	unitTranslation.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (unitTranslation *UnitTranslation) CreatedBySurname() *string {
	return unitTranslation.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (unitTranslation *UnitTranslation) SetCreatedBySurname(createdBySurname *string) {
	unitTranslation.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (unitTranslation *UnitTranslation) UpdatedByFirstName() *string {
	return unitTranslation.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (unitTranslation *UnitTranslation) SetUpdatedByFirstName(updatedByFirstName *string) {
	unitTranslation.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (unitTranslation *UnitTranslation) UpdatedBySurname() *string {
	return unitTranslation.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (unitTranslation *UnitTranslation) SetUpdatedBySurname(updatedBySurname *string) {
	unitTranslation.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (unitTranslation *UnitTranslation) IsUpdated() bool {
	return unitTranslation.updatedByID != nil
}

// Language returns language.
func (unitTranslation *UnitTranslation) Language() uint16 {
	return unitTranslation.language
}

// SetLanguage sets the language.
func (unitTranslation *UnitTranslation) SetLanguage(language uint16) {
	unitTranslation.language = language
}

// Field returns field.
func (unitTranslation *UnitTranslation) Field() uint16 {
	return unitTranslation.field
}

// SetField sets the field.
func (unitTranslation *UnitTranslation) SetField(field uint16) {
	unitTranslation.field = field
}

// UnitID returns unitID.
func (unitTranslation *UnitTranslation) UnitID() string {
	return unitTranslation.unitID
}

// SetUnitID sets the unitID.
func (unitTranslation *UnitTranslation) SetUnitID(unitID string) {
	unitTranslation.unitID = unitID
}

// Value returns value.
func (unitTranslation *UnitTranslation) Value() string {
	return unitTranslation.value
}

// SetValue sets the value.
func (unitTranslation *UnitTranslation) SetValue(value string) {
	unitTranslation.value = value
}

// Display returns display.
func (unitTranslation *UnitTranslation) Display() *string {
	return unitTranslation.display
}

// SetDisplay sets the display.
func (unitTranslation *UnitTranslation) SetDisplay(display *string) {
	unitTranslation.display = display
}

func newUnitTranslation() *UnitTranslation {
	return &UnitTranslation{}
}

// New returns a new instance of UnitTranslationEntity.
func NewUnitTranslationEntity() UnitTranslationEntity {
	return newUnitTranslation()
}
