// Code generated by espal-store-synthesizer. DO NOT EDIT.
package frequentlyaskedquestion

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ SectionTranslationEntity = &SectionTranslation{}

type SectionTranslationEntity interface {
	database.TranslationModel
	SectionID() string
	SetSectionID(sectionID string)
}

// ID returns id.
func (s *SectionTranslation) ID() string {
	return s.id
}

// CreatedByID returns createdByID.
func (s *SectionTranslation) CreatedByID() string {
	return s.createdByID
}

// SetCreatedByID sets the createdByID.
func (s *SectionTranslation) SetCreatedByID(createdByID string) {
	s.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (s *SectionTranslation) UpdatedByID() *string {
	return s.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (s *SectionTranslation) SetUpdatedByID(updatedByID *string) {
	s.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (s *SectionTranslation) CreatedAt() time.Time {
	return s.createdAt
}

// SetCreatedAt sets the createdAt.
func (s *SectionTranslation) SetCreatedAt(createdAt time.Time) {
	s.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (s *SectionTranslation) UpdatedAt() *time.Time {
	return s.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (s *SectionTranslation) SetUpdatedAt(updatedAt *time.Time) {
	s.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (s *SectionTranslation) CreatedByFirstName() *string {
	return s.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (s *SectionTranslation) SetCreatedByFirstName(createdByFirstName *string) {
	s.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (s *SectionTranslation) CreatedBySurname() *string {
	return s.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (s *SectionTranslation) SetCreatedBySurname(createdBySurname *string) {
	s.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (s *SectionTranslation) UpdatedByFirstName() *string {
	return s.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (s *SectionTranslation) SetUpdatedByFirstName(updatedByFirstName *string) {
	s.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (s *SectionTranslation) UpdatedBySurname() *string {
	return s.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (s *SectionTranslation) SetUpdatedBySurname(updatedBySurname *string) {
	s.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (s *SectionTranslation) IsUpdated() bool {
	return s.updatedByID != nil
}

// Language returns language.
func (s *SectionTranslation) Language() uint16 {
	return s.language
}

// SetLanguage sets the language.
func (s *SectionTranslation) SetLanguage(language uint16) {
	s.language = language
}

// Field returns field.
func (s *SectionTranslation) Field() uint16 {
	return s.field
}

// SetField sets the field.
func (s *SectionTranslation) SetField(field uint16) {
	s.field = field
}

// Value returns value.
func (s *SectionTranslation) Value() string {
	return s.value
}

// SetValue sets the value.
func (s *SectionTranslation) SetValue(value string) {
	s.value = value
}

// SectionID returns sectionID.
func (s *SectionTranslation) SectionID() string {
	return s.sectionID
}

// SetSectionID sets the sectionID.
func (s *SectionTranslation) SetSectionID(sectionID string) {
	s.sectionID = sectionID
}

func newSectionTranslation() *SectionTranslation {
	return &SectionTranslation{}
}

// New returns a new instance of SectionTranslationEntity.
func NewSectionTranslationEntity() SectionTranslationEntity {
	return newSectionTranslation()
}
