// Code generated by espal-store-synthesizer. DO NOT EDIT.
package page

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ PageEntity = &Page{}

type PageEntity interface {
	database.Model
	DomainID() string
	SetDomainID(domainID string)
	Active() bool
	SetActive(active bool)
}

// TableName returns the table name that belongs to the current model.
func (p *Page) TableName() string {
	return "Page"
}

// ID returns id.
func (p *Page) ID() string {
	return p.id
}

// CreatedByID returns createdByID.
func (p *Page) CreatedByID() string {
	return p.createdByID
}

// SetCreatedByID sets the createdByID.
func (p *Page) SetCreatedByID(createdByID string) {
	p.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (p *Page) UpdatedByID() *string {
	return p.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (p *Page) SetUpdatedByID(updatedByID *string) {
	p.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (p *Page) CreatedAt() time.Time {
	return p.createdAt
}

// SetCreatedAt sets the createdAt.
func (p *Page) SetCreatedAt(createdAt time.Time) {
	p.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (p *Page) UpdatedAt() *time.Time {
	return p.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (p *Page) SetUpdatedAt(updatedAt *time.Time) {
	p.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (p *Page) CreatedByFirstName() *string {
	return p.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (p *Page) SetCreatedByFirstName(createdByFirstName *string) {
	p.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (p *Page) CreatedBySurname() *string {
	return p.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (p *Page) SetCreatedBySurname(createdBySurname *string) {
	p.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (p *Page) UpdatedByFirstName() *string {
	return p.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (p *Page) SetUpdatedByFirstName(updatedByFirstName *string) {
	p.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (p *Page) UpdatedBySurname() *string {
	return p.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (p *Page) SetUpdatedBySurname(updatedBySurname *string) {
	p.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (p *Page) IsUpdated() bool {
	return p.updatedByID != nil
}

// DomainID returns domainID.
func (p *Page) DomainID() string {
	return p.domainID
}

// SetDomainID sets the domainID.
func (p *Page) SetDomainID(domainID string) {
	p.domainID = domainID
}

// Active returns active.
func (p *Page) Active() bool {
	return p.active
}

// SetActive sets the active.
func (p *Page) SetActive(active bool) {
	p.active = active
}

func newPage() *Page {
	return &Page{}
}

// New returns a new instance of PageEntity.
func NewPageEntity() PageEntity {
	return newPage()
}
