// Code generated by espal-store-synthesizer. DO NOT EDIT.
package filter_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/filter"
)

func TestFilterTable(t *testing.T) {
	filter := filter.NewFilterEntity()
	if filter.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestFilterTableAlias(t *testing.T) {
	filter := filter.NewFilterEntity()
	if filter.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestFilterIsUpdated(t *testing.T) {
	filter := filter.NewFilterEntity()
	filter.IsUpdated()
}

func TestFilterID(t *testing.T) {
	filter := filter.NewFilterEntity()
	filter.ID()
}

func TestFilterCreatedByID(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := "testValue"
	filter.SetCreatedByID(testValue)
	if testValue != filter.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestFilterUpdatedByID(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := "testValue"
	filter.SetUpdatedByID(&testValue)
	if &testValue != filter.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestFilterCreatedAt(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := time.Now()
	filter.SetCreatedAt(testValue)
	if testValue != filter.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestFilterUpdatedAt(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := time.Now()
	filter.SetUpdatedAt(&testValue)
	if &testValue != filter.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestFilterCreatedByFirstName(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := "testValue"
	filter.SetCreatedByFirstName(&testValue)
	if &testValue != filter.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestFilterCreatedBySurname(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := "testValue"
	filter.SetCreatedBySurname(&testValue)
	if &testValue != filter.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestFilterUpdatedByFirstName(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := "testValue"
	filter.SetUpdatedByFirstName(&testValue)
	if &testValue != filter.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestFilterUpdatedBySurname(t *testing.T) {
	filter := filter.NewFilterEntity()
	testValue := "testValue"
	filter.SetUpdatedBySurname(&testValue)
	if &testValue != filter.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}
