// Code generated by espal-store-synthesizer. DO NOT EDIT.
package credit_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/credit"
)

func TestCreditTable(t *testing.T) {
	credit := credit.NewCreditEntity()
	if credit.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestCreditTableAlias(t *testing.T) {
	credit := credit.NewCreditEntity()
	if credit.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestCreditIsUpdated(t *testing.T) {
	credit := credit.NewCreditEntity()
	credit.IsUpdated()
}

func TestCreditID(t *testing.T) {
	credit := credit.NewCreditEntity()
	credit.ID()
}

func TestCreditCreatedByID(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := "testValue"
	credit.SetCreatedByID(testValue)
	if testValue != credit.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestCreditUpdatedByID(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := "testValue"
	credit.SetUpdatedByID(&testValue)
	if &testValue != credit.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestCreditCreatedAt(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := time.Now()
	credit.SetCreatedAt(testValue)
	if testValue != credit.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestCreditUpdatedAt(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := time.Now()
	credit.SetUpdatedAt(&testValue)
	if &testValue != credit.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestCreditCreatedByFirstName(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := "testValue"
	credit.SetCreatedByFirstName(&testValue)
	if &testValue != credit.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestCreditCreatedBySurname(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := "testValue"
	credit.SetCreatedBySurname(&testValue)
	if &testValue != credit.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestCreditUpdatedByFirstName(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := "testValue"
	credit.SetUpdatedByFirstName(&testValue)
	if &testValue != credit.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestCreditUpdatedBySurname(t *testing.T) {
	credit := credit.NewCreditEntity()
	testValue := "testValue"
	credit.SetUpdatedBySurname(&testValue)
	if &testValue != credit.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}
