// Code generated by espal-store-synthesizer. DO NOT EDIT.
package personalmessage_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/personalmessage"
)

func TestPersonalMessageTable(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	if p.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestPersonalMessageTableAlias(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	if p.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestPersonalMessageIsUpdated(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	p.IsUpdated()
}

func TestPersonalMessageID(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	p.ID()
}

func TestPersonalMessageCreatedByID(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetCreatedByID(testValue)
	if testValue != p.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageUpdatedByID(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetUpdatedByID(&testValue)
	if &testValue != p.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageCreatedAt(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := time.Now()
	p.SetCreatedAt(testValue)
	if testValue != p.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageUpdatedAt(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := time.Now()
	p.SetUpdatedAt(&testValue)
	if &testValue != p.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageCreatedByFirstName(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetCreatedByFirstName(&testValue)
	if &testValue != p.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageCreatedBySurname(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetCreatedBySurname(&testValue)
	if &testValue != p.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageUpdatedByFirstName(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetUpdatedByFirstName(&testValue)
	if &testValue != p.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageUpdatedBySurname(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetUpdatedBySurname(&testValue)
	if &testValue != p.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageUserID(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetUserID(testValue)
	if testValue != p.UserID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageRecipientID(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetRecipientID(testValue)
	if testValue != p.RecipientID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageResponseToID(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetResponseToID(&testValue)
	if &testValue != p.ResponseToID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageTitle(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetTitle(&testValue)
	if &testValue != p.Title() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPersonalMessageMessage(t *testing.T) {
	p := personalmessage.NewPersonalMessageEntity()
	testValue := "testValue"
	p.SetMessage(testValue)
	if testValue != p.Message() {
		t.Fatal("Getter did not return the Set value")
	}
}
