// Code generated by espal-store-synthesizer. DO NOT EDIT.
package pointofsale_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/pointofsale"
)

func TestPointOfSaleTable(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	if p.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestPointOfSaleTableAlias(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	if p.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestPointOfSaleIsUpdated(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	p.IsUpdated()
}

func TestPointOfSaleID(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	p.ID()
}

func TestPointOfSaleCreatedByID(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := "testValue"
	p.SetCreatedByID(testValue)
	if testValue != p.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleUpdatedByID(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := "testValue"
	p.SetUpdatedByID(&testValue)
	if &testValue != p.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleCreatedAt(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := time.Now()
	p.SetCreatedAt(testValue)
	if testValue != p.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleUpdatedAt(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := time.Now()
	p.SetUpdatedAt(&testValue)
	if &testValue != p.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleCreatedByFirstName(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := "testValue"
	p.SetCreatedByFirstName(&testValue)
	if &testValue != p.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleCreatedBySurname(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := "testValue"
	p.SetCreatedBySurname(&testValue)
	if &testValue != p.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleUpdatedByFirstName(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := "testValue"
	p.SetUpdatedByFirstName(&testValue)
	if &testValue != p.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleUpdatedBySurname(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := "testValue"
	p.SetUpdatedBySurname(&testValue)
	if &testValue != p.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPointOfSaleShopID(t *testing.T) {
	p := pointofsale.NewPointOfSaleEntity()
	testValue := "testValue"
	p.SetShopID(testValue)
	if testValue != p.ShopID() {
		t.Fatal("Getter did not return the Set value")
	}
}
