// Code generated by espal-store-synthesizer. DO NOT EDIT.
package gift

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ WrappingEntity = &Wrapping{}

type WrappingEntity interface {
	database.Model
}

// ID returns id.
func (w *Wrapping) ID() string {
	return w.id
}

// CreatedByID returns createdByID.
func (w *Wrapping) CreatedByID() string {
	return w.createdByID
}

// SetCreatedByID sets the createdByID.
func (w *Wrapping) SetCreatedByID(createdByID string) {
	w.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (w *Wrapping) UpdatedByID() *string {
	return w.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (w *Wrapping) SetUpdatedByID(updatedByID *string) {
	w.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (w *Wrapping) CreatedAt() time.Time {
	return w.createdAt
}

// SetCreatedAt sets the createdAt.
func (w *Wrapping) SetCreatedAt(createdAt time.Time) {
	w.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (w *Wrapping) UpdatedAt() *time.Time {
	return w.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (w *Wrapping) SetUpdatedAt(updatedAt *time.Time) {
	w.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (w *Wrapping) CreatedByFirstName() *string {
	return w.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (w *Wrapping) SetCreatedByFirstName(createdByFirstName *string) {
	w.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (w *Wrapping) CreatedBySurname() *string {
	return w.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (w *Wrapping) SetCreatedBySurname(createdBySurname *string) {
	w.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (w *Wrapping) UpdatedByFirstName() *string {
	return w.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (w *Wrapping) SetUpdatedByFirstName(updatedByFirstName *string) {
	w.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (w *Wrapping) UpdatedBySurname() *string {
	return w.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (w *Wrapping) SetUpdatedBySurname(updatedBySurname *string) {
	w.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (w *Wrapping) IsUpdated() bool {
	return w.updatedByID != nil
}

func newWrapping() *Wrapping {
	return &Wrapping{}
}

// New returns a new instance of WrappingEntity.
func NewWrappingEntity() WrappingEntity {
	return newWrapping()
}
