// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/base/base.qtpl:1
package base

//line pages/base/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/base/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/base/base.qtpl:2
type BasePage interface {
//line pages/base/base.qtpl:2
	Title() string
//line pages/base/base.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Menu() string
//line pages/base/base.qtpl:2
	StreamMenu(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteMenu(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Content() string
//line pages/base/base.qtpl:2
	StreamContent(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteContent(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Stylesheets() string
//line pages/base/base.qtpl:2
	StreamStylesheets(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteStylesheets(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Javascripts() string
//line pages/base/base.qtpl:2
	StreamJavascripts(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteJavascripts(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	mainJavascripts() string
//line pages/base/base.qtpl:2
	streammainJavascripts(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	writemainJavascripts(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
}

//line pages/base/base.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, p BasePage) {
//line pages/base/base.qtpl:12
	qw422016.N().S(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>`)
//line pages/base/base.qtpl:17
	p.StreamTitle(qw422016)
//line pages/base/base.qtpl:17
	qw422016.N().S(`</title><link rel="stylesheet" href="/c/m.css">`)
//line pages/base/base.qtpl:19
	p.StreamStylesheets(qw422016)
//line pages/base/base.qtpl:19
	qw422016.N().S(`</head><body>`)
//line pages/base/base.qtpl:22
	p.StreamMenu(qw422016)
//line pages/base/base.qtpl:23
	p.StreamContent(qw422016)
//line pages/base/base.qtpl:24
	p.streammainJavascripts(qw422016)
//line pages/base/base.qtpl:25
	p.StreamJavascripts(qw422016)
//line pages/base/base.qtpl:26
	qw422016.N().S(`</body></html>`)
//line pages/base/base.qtpl:28
}

//line pages/base/base.qtpl:28
func WritePageTemplate(qq422016 qtio422016.Writer, p BasePage) {
//line pages/base/base.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:28
	StreamPageTemplate(qw422016, p)
//line pages/base/base.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:28
}

//line pages/base/base.qtpl:28
func PageTemplate(p BasePage) string {
//line pages/base/base.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:28
	WritePageTemplate(qb422016, p)
//line pages/base/base.qtpl:28
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:28
	return qs422016
//line pages/base/base.qtpl:28
}

//line pages/base/base.qtpl:30
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:30
}

//line pages/base/base.qtpl:30
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:30
	p.StreamTitle(qw422016)
//line pages/base/base.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:30
}

//line pages/base/base.qtpl:30
func (p *Page) Title() string {
//line pages/base/base.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:30
	p.WriteTitle(qb422016)
//line pages/base/base.qtpl:30
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:30
	return qs422016
//line pages/base/base.qtpl:30
}

//line pages/base/base.qtpl:32
func (p *Page) StreamMenu(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:32
	qw422016.N().S(`<header><a href="/">`)
//line pages/base/base.qtpl:34
	qw422016.E().S(p.Translate("home"))
//line pages/base/base.qtpl:34
	qw422016.N().S(`</a><a href="/Catalog">`)
//line pages/base/base.qtpl:35
	qw422016.E().S(p.Translate("catalog"))
//line pages/base/base.qtpl:35
	qw422016.N().S(`</a><a href="/Forums">`)
//line pages/base/base.qtpl:36
	qw422016.E().S(p.TranslatePlural("forum"))
//line pages/base/base.qtpl:36
	qw422016.N().S(`</a><a href="/Cart">`)
//line pages/base/base.qtpl:37
	qw422016.E().S(p.Translate("shoppingCart"))
//line pages/base/base.qtpl:37
	qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:38
	if p.IsLoggedIn() {
//line pages/base/base.qtpl:38
		qw422016.N().S(`<a href="/Account">`)
//line pages/base/base.qtpl:38
		qw422016.E().S(p.Translate("myAccount"))
//line pages/base/base.qtpl:38
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:38
	}
//line pages/base/base.qtpl:39
	if !p.IsLoggedIn() {
//line pages/base/base.qtpl:39
		qw422016.N().S(`<a href="/Login">`)
//line pages/base/base.qtpl:39
		qw422016.E().S(p.Translate("login"))
//line pages/base/base.qtpl:39
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:39
	}
//line pages/base/base.qtpl:40
	if p.IsLoggedIn() {
//line pages/base/base.qtpl:40
		qw422016.N().S(`<a href="/Logout">`)
//line pages/base/base.qtpl:40
		qw422016.E().S(p.Translate("logout"))
//line pages/base/base.qtpl:40
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:40
	}
//line pages/base/base.qtpl:41
	if !p.IsLoggedIn() {
//line pages/base/base.qtpl:41
		qw422016.N().S(`<a href="/ForgotPassword">`)
//line pages/base/base.qtpl:41
		qw422016.E().S(p.Translate("forgotPassword"))
//line pages/base/base.qtpl:41
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:41
	}
//line pages/base/base.qtpl:42
	if p.IsLoggedIn() && p.HasAdminAccess() {
//line pages/base/base.qtpl:42
		qw422016.N().S(`<a href="`)
//line pages/base/base.qtpl:43
		qw422016.E().S(p.AdminURL())
//line pages/base/base.qtpl:43
		qw422016.N().S(`">`)
//line pages/base/base.qtpl:43
		qw422016.E().S(p.Translate("admin"))
//line pages/base/base.qtpl:43
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:44
	}
//line pages/base/base.qtpl:45
	if p.HasPprofEnabled() {
//line pages/base/base.qtpl:45
		qw422016.N().S(`<a href="`)
//line pages/base/base.qtpl:46
		qw422016.E().S(p.PprofURL())
//line pages/base/base.qtpl:46
		qw422016.N().S(`">Pprof</a>`)
//line pages/base/base.qtpl:47
	}
//line pages/base/base.qtpl:47
	qw422016.N().S(`</header>`)
//line pages/base/base.qtpl:49
}

//line pages/base/base.qtpl:49
func (p *Page) WriteMenu(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:49
	p.StreamMenu(qw422016)
//line pages/base/base.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:49
}

//line pages/base/base.qtpl:49
func (p *Page) Menu() string {
//line pages/base/base.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:49
	p.WriteMenu(qb422016)
//line pages/base/base.qtpl:49
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:49
	return qs422016
//line pages/base/base.qtpl:49
}

//line pages/base/base.qtpl:51
func (p *Page) streammainJavascripts(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:52
	if p.HasFlashMessage() {
//line pages/base/base.qtpl:52
		qw422016.N().S(`<script src="/j/flashMessage.js"></script>`)
//line pages/base/base.qtpl:54
	}
//line pages/base/base.qtpl:55
}

//line pages/base/base.qtpl:55
func (p *Page) writemainJavascripts(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:55
	p.streammainJavascripts(qw422016)
//line pages/base/base.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:55
}

//line pages/base/base.qtpl:55
func (p *Page) mainJavascripts() string {
//line pages/base/base.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:55
	p.writemainJavascripts(qb422016)
//line pages/base/base.qtpl:55
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:55
	return qs422016
//line pages/base/base.qtpl:55
}

//line pages/base/base.qtpl:57
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:57
}

//line pages/base/base.qtpl:57
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:57
	p.StreamContent(qw422016)
//line pages/base/base.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:57
}

//line pages/base/base.qtpl:57
func (p *Page) Content() string {
//line pages/base/base.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:57
	p.WriteContent(qb422016)
//line pages/base/base.qtpl:57
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:57
	return qs422016
//line pages/base/base.qtpl:57
}

//line pages/base/base.qtpl:59
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:59
}

//line pages/base/base.qtpl:59
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:59
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:59
	p.StreamStylesheets(qw422016)
//line pages/base/base.qtpl:59
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:59
}

//line pages/base/base.qtpl:59
func (p *Page) Stylesheets() string {
//line pages/base/base.qtpl:59
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:59
	p.WriteStylesheets(qb422016)
//line pages/base/base.qtpl:59
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:59
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:59
	return qs422016
//line pages/base/base.qtpl:59
}

//line pages/base/base.qtpl:61
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:61
}

//line pages/base/base.qtpl:61
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:61
	p.StreamJavascripts(qw422016)
//line pages/base/base.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:61
}

//line pages/base/base.qtpl:61
func (p *Page) Javascripts() string {
//line pages/base/base.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:61
	p.WriteJavascripts(qb422016)
//line pages/base/base.qtpl:61
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:61
	return qs422016
//line pages/base/base.qtpl:61
}
