// Code generated by espal-store-synthesizer. DO NOT EDIT.
package office

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ OfficeEntity = &Office{}

type OfficeEntity interface {
	database.Model
	Active() bool
	SetActive(active bool)
	Sorting() uint
	SetSorting(sorting uint)
	PrimaryContactPerson() *string
	SetPrimaryContactPerson(primaryContactPerson *string)
	Street() string
	SetStreet(street string)
	StreetLine2() *string
	SetStreetLine2(streetLine2 *string)
	Number() string
	SetNumber(number string)
	NumberAddition() *string
	SetNumberAddition(numberAddition *string)
	ZipCode() string
	SetZipCode(zipCode string)
	City() string
	SetCity(city string)
	State() *string
	SetState(state *string)
	Country() *uint16
	SetCountry(country *uint16)
	PhoneNumber() *string
	SetPhoneNumber(phoneNumber *string)
	Email() *string
	SetEmail(email *string)
}

// ID returns id.
func (office *Office) ID() string {
	return office.id
}

// CreatedByID returns createdByID.
func (office *Office) CreatedByID() string {
	return office.createdByID
}

// SetCreatedByID sets the createdByID.
func (office *Office) SetCreatedByID(createdByID string) {
	office.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (office *Office) UpdatedByID() *string {
	return office.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (office *Office) SetUpdatedByID(updatedByID *string) {
	office.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (office *Office) CreatedAt() time.Time {
	return office.createdAt
}

// SetCreatedAt sets the createdAt.
func (office *Office) SetCreatedAt(createdAt time.Time) {
	office.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (office *Office) UpdatedAt() *time.Time {
	return office.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (office *Office) SetUpdatedAt(updatedAt *time.Time) {
	office.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (office *Office) CreatedByFirstName() *string {
	return office.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (office *Office) SetCreatedByFirstName(createdByFirstName *string) {
	office.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (office *Office) CreatedBySurname() *string {
	return office.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (office *Office) SetCreatedBySurname(createdBySurname *string) {
	office.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (office *Office) UpdatedByFirstName() *string {
	return office.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (office *Office) SetUpdatedByFirstName(updatedByFirstName *string) {
	office.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (office *Office) UpdatedBySurname() *string {
	return office.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (office *Office) SetUpdatedBySurname(updatedBySurname *string) {
	office.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (office *Office) IsUpdated() bool {
	return office.updatedByID != nil
}

// Active returns active.
func (office *Office) Active() bool {
	return office.active
}

// SetActive sets the active.
func (office *Office) SetActive(active bool) {
	office.active = active
}

// Sorting returns sorting.
func (office *Office) Sorting() uint {
	return office.sorting
}

// SetSorting sets the sorting.
func (office *Office) SetSorting(sorting uint) {
	office.sorting = sorting
}

// PrimaryContactPerson returns primaryContactPerson.
func (office *Office) PrimaryContactPerson() *string {
	return office.primaryContactPerson
}

// SetPrimaryContactPerson sets the primaryContactPerson.
func (office *Office) SetPrimaryContactPerson(primaryContactPerson *string) {
	office.primaryContactPerson = primaryContactPerson
}

// Street returns street.
func (office *Office) Street() string {
	return office.street
}

// SetStreet sets the street.
func (office *Office) SetStreet(street string) {
	office.street = street
}

// StreetLine2 returns streetLine2.
func (office *Office) StreetLine2() *string {
	return office.streetLine2
}

// SetStreetLine2 sets the streetLine2.
func (office *Office) SetStreetLine2(streetLine2 *string) {
	office.streetLine2 = streetLine2
}

// Number returns number.
func (office *Office) Number() string {
	return office.number
}

// SetNumber sets the number.
func (office *Office) SetNumber(number string) {
	office.number = number
}

// NumberAddition returns numberAddition.
func (office *Office) NumberAddition() *string {
	return office.numberAddition
}

// SetNumberAddition sets the numberAddition.
func (office *Office) SetNumberAddition(numberAddition *string) {
	office.numberAddition = numberAddition
}

// ZipCode returns zipCode.
func (office *Office) ZipCode() string {
	return office.zipCode
}

// SetZipCode sets the zipCode.
func (office *Office) SetZipCode(zipCode string) {
	office.zipCode = zipCode
}

// City returns city.
func (office *Office) City() string {
	return office.city
}

// SetCity sets the city.
func (office *Office) SetCity(city string) {
	office.city = city
}

// State returns state.
func (office *Office) State() *string {
	return office.state
}

// SetState sets the state.
func (office *Office) SetState(state *string) {
	office.state = state
}

// Country returns country.
func (office *Office) Country() *uint16 {
	return office.country
}

// SetCountry sets the country.
func (office *Office) SetCountry(country *uint16) {
	office.country = country
}

// PhoneNumber returns phoneNumber.
func (office *Office) PhoneNumber() *string {
	return office.phoneNumber
}

// SetPhoneNumber sets the phoneNumber.
func (office *Office) SetPhoneNumber(phoneNumber *string) {
	office.phoneNumber = phoneNumber
}

// Email returns email.
func (office *Office) Email() *string {
	return office.email
}

// SetEmail sets the email.
func (office *Office) SetEmail(email *string) {
	office.email = email
}

func newOffice() *Office {
	return &Office{}
}

// New returns a new instance of OfficeEntity.
func NewOfficeEntity() OfficeEntity {
	return newOffice()
}
