package renderer

import (
	"strings"
)

// AccountMenu will render the shared account side menu.
func (r *TemplateRenderer) AccountMenu(ctx context) string {
	out := strings.Builder{}

	// TODO :: Mark the active menu-item
	// TODO :: Support Assistant Chat Interface

	r.perror(out.WriteString(`<p><i>Chat Assistance Module</i></p>`))

	r.perror(out.WriteString(`<a href="/Account">`))
	r.perror(out.WriteString(ctx.Translate("myAccount")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Wishlists">`))
	r.perror(out.WriteString(ctx.TranslatePlural("wishlist")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Recommendations">`))
	r.perror(out.WriteString(ctx.TranslatePlural("recommendation")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Shipments">`))
	r.perror(out.WriteString(ctx.TranslatePlural("shipment")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Purchases">`))
	r.perror(out.WriteString(ctx.TranslatePlural("purchase")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/DigitalPurchases">`))
	r.perror(out.WriteString(ctx.TranslatePlural("digitalPurchase")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Orders">`))
	r.perror(out.WriteString(ctx.TranslatePlural("order")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Invoices">`))
	r.perror(out.WriteString(ctx.TranslatePlural("invoice")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/CouponCodes">`))
	r.perror(out.WriteString(ctx.TranslatePlural("couponCode")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Discounts">`))
	r.perror(out.WriteString(ctx.TranslatePlural("discount")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Subscriptions">`))
	r.perror(out.WriteString(ctx.TranslatePlural("subscription")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Newsletters">`))
	r.perror(out.WriteString(ctx.TranslatePlural("newsletter")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Addressbook">`))
	r.perror(out.WriteString(ctx.Translate("addressbook")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Contacts">`))
	r.perror(out.WriteString(ctx.TranslatePlural("contact")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/PersonalMessages">`))
	r.perror(out.WriteString(ctx.TranslatePlural("personalMessage")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Activity">`))
	r.perror(out.WriteString(ctx.Translate("activity")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Preferences">`))
	r.perror(out.WriteString(ctx.TranslatePlural("preference")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/EmailSettings">`))
	r.perror(out.WriteString(ctx.TranslatePlural("emailSetting")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Edit">`))
	r.perror(out.WriteString(ctx.Translate("editAccount")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/PaymentOptions">`))
	r.perror(out.WriteString(ctx.TranslatePlural("paymentOption")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Credits">`))
	r.perror(out.WriteString(ctx.TranslatePlural("credit")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/TwoFactorIdentification">`))
	r.perror(out.WriteString(ctx.Translate("twoFactorIdentification")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/Apps">`))
	r.perror(out.WriteString(ctx.TranslatePlural("app")))
	r.perror(out.WriteString(`</a>`))
	r.perror(out.WriteString(`<a href="/Account/ChangePassword">`))
	r.perror(out.WriteString(ctx.Translate("changePassword")))
	r.perror(out.WriteString(`</a>`))

	return out.String()
}
