package renderer

import (
	"strings"
)

// AccountMenu will render the shared account side menu.
// nolint:funlen
func (r *TemplateRenderer) AccountMenu(ctx context) string {
	out := strings.Builder{}

	// TODO :: Mark the active menu-item
	// TODO :: Support Assistant Chat Interface

	out.WriteString(`<p><i>Chat Assistance Module</i></p>`)

	out.WriteString(`<a href="/Account">`)
	out.WriteString(ctx.Translate("myAccount"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Wishlists">`)
	out.WriteString(ctx.TranslatePlural("wishlist"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Recommendations">`)
	out.WriteString(ctx.TranslatePlural("recommendation"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Shipments">`)
	out.WriteString(ctx.TranslatePlural("shipment"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Purchases">`)
	out.WriteString(ctx.TranslatePlural("purchase"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/DigitalPurchases">`)
	out.WriteString(ctx.TranslatePlural("digitalPurchase"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Orders">`)
	out.WriteString(ctx.TranslatePlural("order"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Invoices">`)
	out.WriteString(ctx.TranslatePlural("invoice"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/CouponCodes">`)
	out.WriteString(ctx.TranslatePlural("couponCode"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Discounts">`)
	out.WriteString(ctx.TranslatePlural("discount"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Subscriptions">`)
	out.WriteString(ctx.TranslatePlural("subscription"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Newsletters">`)
	out.WriteString(ctx.TranslatePlural("newsletter"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Addressbook">`)
	out.WriteString(ctx.Translate("addressbook"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Contacts">`)
	out.WriteString(ctx.TranslatePlural("contact"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/PersonalMessages">`)
	out.WriteString(ctx.TranslatePlural("personalMessage"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Activity">`)
	out.WriteString(ctx.Translate("activity"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Preferences">`)
	out.WriteString(ctx.TranslatePlural("preference"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/EmailSettings">`)
	out.WriteString(ctx.TranslatePlural("emailSetting"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Edit">`)
	out.WriteString(ctx.Translate("editAccount"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/PaymentOptions">`)
	out.WriteString(ctx.TranslatePlural("paymentOption"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Credits">`)
	out.WriteString(ctx.TranslatePlural("credit"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/TwoFactorIdentification">`)
	out.WriteString(ctx.Translate("twoFactorIdentification"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/Apps">`)
	out.WriteString(ctx.TranslatePlural("app"))
	out.WriteString(`</a>`)
	out.WriteString(`<a href="/Account/ChangePassword">`)
	out.WriteString(ctx.Translate("changePassword"))
	out.WriteString(`</a>`)

	return out.String()
}
