package renderer

import (
	"strings"
)

// AccountMenu will render the shared account side menu.
func (templateRenderer *TemplateRenderer) AccountMenu(ctx context) string {
	out := strings.Builder{}

	// TODO :: Mark the active menu-item
	// TODO :: Support Assistant Chat Interface

	templateRenderer.perror(out.WriteString(`<p><i>Chat Assistance Module</i></p>`))

	templateRenderer.perror(out.WriteString(`<a href="/Account">`))
	templateRenderer.perror(out.WriteString(ctx.Translate("myAccount")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Wishlists">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("wishlist")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Recommendations">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("recommendation")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Shipments">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("shipment")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Purchases">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("purchase")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/DigitalPurchases">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("digitalPurchase")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Orders">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("order")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Invoices">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("invoice")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/CouponCodes">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("couponCode")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Discounts">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("discount")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Subscriptions">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("subscription")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Newsletters">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("newsletter")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Addressbook">`))
	templateRenderer.perror(out.WriteString(ctx.Translate("addressbook")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Contacts">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("contact")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/PersonalMessages">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("personalMessage")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Activity">`))
	templateRenderer.perror(out.WriteString(ctx.Translate("activity")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Preferences">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("preference")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/EmailSettings">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("emailSetting")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Edit">`))
	templateRenderer.perror(out.WriteString(ctx.Translate("editAccount")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/PaymentOptions">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("paymentOption")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Credits">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("credit")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/TwoFactorIdentification">`))
	templateRenderer.perror(out.WriteString(ctx.Translate("twoFactorIdentification")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/Apps">`))
	templateRenderer.perror(out.WriteString(ctx.TranslatePlural("app")))
	templateRenderer.perror(out.WriteString(`</a>`))
	templateRenderer.perror(out.WriteString(`<a href="/Account/ChangePassword">`))
	templateRenderer.perror(out.WriteString(ctx.Translate("changePassword")))
	templateRenderer.perror(out.WriteString(`</a>`))

	return out.String()
}
