// Code generated by espal-store-synthesizer. DO NOT EDIT.
package wishlist

import (
	"database/sql"
	"github.com/espal-digital-development/espal-core/database"
	"github.com/juju/errors"
)

var _ Store = &WishlistsStore{}

// Store represents a data interaction object.
type Store interface {
}

func (s *WishlistsStore) fetch(query string, withCreators bool, params ...interface{}) (result []*Wishlist, ok bool, err error) {
	rows, err := s.selecterDatabase.Query(query, params...)
	if err == sql.ErrNoRows {
		err = nil
		return
	}
	if err != nil {
		err = errors.Trace(err)
		return
	}
	defer func(dbRows database.Rows) {
		closeErr := dbRows.Close()
		if err != nil && closeErr != nil {
			err = errors.Wrap(err, closeErr)
		} else if closeErr != nil {
			err = errors.Trace(closeErr)
		}
	}(rows)
	result = make([]*Wishlist, 0)
	for rows.Next() {
		if err := rows.Err(); err != nil {
			return nil, false, errors.Trace(err)
		}
		w := newWishlist()
		fields := []interface{}{&w.id, &w.createdByID, &w.updatedByID, &w.createdAt, &w.updatedAt, &w.domainID, &w.userID, &w.sorting}
		if withCreators {
			fields = append(fields, &w.createdByFirstName, &w.createdBySurname, &w.updatedByFirstName, &w.updatedBySurname)
		}
		if err := rows.Scan(fields...); err != nil {
			return nil, false, errors.Trace(err)
		}
		result = append(result, w)
	}
	ok = len(result) > 0
	return
}

// New returns a new instance of WishlistsStore.
func New(selecterDatabase database.Database) (*WishlistsStore, error) {
	s := &WishlistsStore{
		selecterDatabase: selecterDatabase,
	}
	return s, nil
}
