// Code generated by espal-store-synthesizer. DO NOT EDIT.
package shipment

import (
	"database/sql"
	"github.com/espal-digital-development/espal-core/database"
	"github.com/juju/errors"
)

var _ Store = &ShipmentsStore{}

// Store represents a data interaction object.
type Store interface {
}

func (s *ShipmentsStore) fetch(query string, withCreators bool, params ...interface{}) (result []*Shipment, ok bool, err error) {
	rows, err := s.selecterDatabase.Query(query, params...)
	if err == sql.ErrNoRows {
		err = nil
		return
	}
	if err != nil {
		err = errors.Trace(err)
		return
	}
	defer func(dbRows database.Rows) {
		closeErr := dbRows.Close()
		if err != nil && closeErr != nil {
			err = errors.Wrap(err, closeErr)
		} else if closeErr != nil {
			err = errors.Trace(closeErr)
		}
	}(rows)
	result = make([]*Shipment, 0)
	for rows.Next() {
		if err := rows.Err(); err != nil {
			return nil, false, errors.Trace(err)
		}
		s := newShipment()
		fields := []interface{}{&s.id, &s.createdByID, &s.updatedByID, &s.createdAt, &s.updatedAt, &s.domainID, &s.userID, &s.saleOrderID, &s.code, &s.userInfoBusiness, &s.userInfoBusinessCocNumber, &s.userInfoFirstName, &s.userInfoSurname, &s.userInfoStreet, &s.userInfoStreetLine2, &s.userInfoNumber, &s.userInfoNumberAddition, &s.userInfoZipCode, &s.userInfoCity, &s.userInfoState, &s.userInfoCountry, &s.userInfoPhoneNumber, &s.userInfoEmail, &s.comments, &s.sellingPartyAutograph, &s.buyingPartyAutograph}
		if withCreators {
			fields = append(fields, &s.createdByFirstName, &s.createdBySurname, &s.updatedByFirstName, &s.updatedBySurname)
		}
		if err := rows.Scan(fields...); err != nil {
			return nil, false, errors.Trace(err)
		}
		result = append(result, s)
	}
	ok = len(result) > 0
	return
}

// New returns a new instance of ShipmentsStore.
func New(selecterDatabase database.Database) (*ShipmentsStore, error) {
	s := &ShipmentsStore{
		selecterDatabase: selecterDatabase,
	}
	return s, nil
}
