package currencies

// nolint:gomnd
var data = map[string]Currency{
	"AFN": {id: 1, code: "AFN", symbol: "؋", englishName: "Afghanistan Afghani"},
	"ALL": {id: 2, code: "ALL", symbol: "Lek", englishName: "AlbaniaLek"},
	"ARS": {id: 3, code: "ARS", symbol: "$", englishName: "Argentina Peso"},
	"AWG": {id: 4, code: "AWG", symbol: "ƒ", englishName: "ArubaGuilder"},
	"AUD": {id: 5, code: "AUD", symbol: "$", englishName: "Australia Dollar"},
	"AZN": {id: 6, code: "AZN", symbol: "ман", englishName: "Azerbaijan New Manat"},
	"BSD": {id: 7, code: "BSD", symbol: "$", englishName: "Bahamas Dollar"},
	"BBD": {id: 8, code: "BBD", symbol: "$", englishName: "Barbados Dollar"},
	"BYN": {id: 9, code: "BYN", symbol: "Br", englishName: "Belarus Ruble"},
	"BZD": {id: 10, code: "BZD", symbol: "BZ$", englishName: "Belize Dollar"},
	"BMD": {id: 11, code: "BMD", symbol: "$", englishName: "Bermuda Dollar"},
	"BOB": {id: 12, code: "BOB", symbol: "$b", englishName: "Bolivia Bolíviano"},
	"BAM": {id: 13, code: "BAM", symbol: "KM", englishName: "Bosnia and Herzegovina Convertible Marka"},
	"BWP": {id: 14, code: "BWP", symbol: "P", englishName: "Botswana Pula"},
	"BGN": {id: 15, code: "BGN", symbol: "лв", englishName: "Bulgaria Lev"},
	"BRL": {id: 16, code: "BRL", symbol: "R$", englishName: "Brazil Real"},
	"BND": {id: 17, code: "BND", symbol: "$", englishName: "Brunei Darussalam Dollar"},
	"KHR": {id: 18, code: "KHR", symbol: "៛", englishName: "Cambodia Riel"},
	"CAD": {id: 19, code: "CAD", symbol: "$", englishName: "Canada Dollar"},
	"KYD": {id: 20, code: "KYD", symbol: "$", englishName: "Cayman Islands Dollar"},
	"CLP": {id: 21, code: "CLP", symbol: "$", englishName: "Chile Peso"},
	"CNY": {id: 22, code: "CNY", symbol: "¥", englishName: "China Yuan Renminbi"},
	"COP": {id: 23, code: "COP", symbol: "$", englishName: "Colombia Peso"},
	"CRC": {id: 24, code: "CRC", symbol: "₡", englishName: "Costa Rica Colon"},
	"HRK": {id: 25, code: "HRK", symbol: "kn", englishName: "Croatia Kuna"},
	"CUP": {id: 26, code: "CUP", symbol: "₱", englishName: "Cuba Peso"},
	"CZK": {id: 27, code: "CZK", symbol: "Kč", englishName: "Czech Republic Koruna"},
	"DKK": {id: 28, code: "DKK", symbol: "kr", englishName: "Denmark Krone"},
	"DOP": {id: 29, code: "DOP", symbol: "RD$", englishName: "Dominican Republic Peso"},
	"XCD": {id: 30, code: "XCD", symbol: "$", englishName: "East Caribbean Dollar"},
	"EGP": {id: 31, code: "EGP", symbol: "£", englishName: "Egypt Pound"},
	"SVC": {id: 32, code: "SVC", symbol: "$", englishName: "El Salvador Colon"},
	"EUR": {id: 33, code: "EUR", symbol: "€", englishName: "Euro Member Countries"},
	"FKP": {id: 34, code: "FKP", symbol: "£", englishName: "Falkland Islands (Malvinas) Pound"},
	"FJD": {id: 35, code: "FJD", symbol: "$", englishName: "Fiji Dollar"},
	"GHS": {id: 36, code: "GHS", symbol: "¢", englishName: "Ghana Cedi"},
	"GIP": {id: 37, code: "GIP", symbol: "£", englishName: "Gibraltar Pound"},
	"GTQ": {id: 38, code: "GTQ", symbol: "Q", englishName: "Guatemala Quetzal"},
	"GGP": {id: 39, code: "GGP", symbol: "£", englishName: "Guernsey Pound"},
	"GYD": {id: 40, code: "GYD", symbol: "$", englishName: "Guyana Dollar"},
	"HNL": {id: 41, code: "HNL", symbol: "L", englishName: "Honduras Lempira"},
	"HKD": {id: 42, code: "HKD", symbol: "$", englishName: "Hong Kong Dollar"},
	"HUF": {id: 43, code: "HUF", symbol: "Ft", englishName: "Hungary Forint"},
	"ISK": {id: 44, code: "ISK", symbol: "kr", englishName: "Iceland Krona"},
	"INR": {id: 45, code: "INR", symbol: "", englishName: "India Rupee"},
	"IDR": {id: 46, code: "IDR", symbol: "Rp", englishName: "Indonesia Rupiah"},
	"IRR": {id: 47, code: "IRR", symbol: "﷼", englishName: "Iran Rial"},
	"IMP": {id: 48, code: "IMP", symbol: "£", englishName: "Isle of Man Pound"},
	"ILS": {id: 49, code: "ILS", symbol: "₪", englishName: "Israel Shekel"},
	"JMD": {id: 50, code: "JMD", symbol: "J$", englishName: "Jamaica Dollar"},
	"JPY": {id: 51, code: "JPY", symbol: "¥", englishName: "Japan Yen"},
	"JEP": {id: 52, code: "JEP", symbol: "£", englishName: "Jersey Pound"},
	"KZT": {id: 53, code: "KZT", symbol: "лв", englishName: "Kazakhstan Tenge"},
	"KPW": {id: 54, code: "KPW", symbol: "₩", englishName: "Korea (North) Won"},
	"KRW": {id: 55, code: "KRW", symbol: "₩", englishName: "Korea (South) Won"},
	"KGS": {id: 56, code: "KGS", symbol: "лв", englishName: "Kyrgyzstan Som"},
	"LAK": {id: 57, code: "LAK", symbol: "₭", englishName: "Laos Kip"},
	"LBP": {id: 58, code: "LBP", symbol: "£", englishName: "Lebanon Pound"},
	"LRD": {id: 59, code: "LRD", symbol: "$", englishName: "Liberia Dollar"},
	"MKD": {id: 60, code: "MKD", symbol: "ден", englishName: "Macedonia Denar"},
	"MYR": {id: 61, code: "MYR", symbol: "RM", englishName: "Malaysia Ringgit"},
	"MUR": {id: 62, code: "MUR", symbol: "₨", englishName: "Mauritius Rupee"},
	"MXN": {id: 63, code: "MXN", symbol: "$", englishName: "Mexico Peso"},
	"MNT": {id: 64, code: "MNT", symbol: "₮", englishName: "Mongolia Tughrik"},
	"MZN": {id: 65, code: "MZN", symbol: "MT", englishName: "Mozambique Metical"},
	"NAD": {id: 66, code: "NAD", symbol: "$", englishName: "Namibia Dollar"},
	"NPR": {id: 67, code: "NPR", symbol: "₨", englishName: "Nepal Rupee"},
	"ANG": {id: 68, code: "ANG", symbol: "ƒ", englishName: "Netherlands Antilles Guilder"},
	"NZD": {id: 69, code: "NZD", symbol: "$", englishName: "New Zealand Dollar"},
	"NIO": {id: 70, code: "NIO", symbol: "C$", englishName: "Nicaragua Cordoba"},
	"NGN": {id: 71, code: "NGN", symbol: "₦", englishName: "Nigeria Naira"},
	"NOK": {id: 72, code: "NOK", symbol: "kr", englishName: "Norway Krone"},
	"OMR": {id: 73, code: "OMR", symbol: "﷼", englishName: "Oman Rial"},
	"PKR": {id: 74, code: "PKR", symbol: "₨", englishName: "Pakistan Rupee"},
	"PAB": {id: 75, code: "PAB", symbol: "B/.", englishName: "Panama Balboa"},
	"PYG": {id: 76, code: "PYG", symbol: "Gs", englishName: "Paraguay Guarani"},
	"PEN": {id: 77, code: "PEN", symbol: "S/.", englishName: "Peru Sol"},
	"PHP": {id: 78, code: "PHP", symbol: "₱", englishName: "Philippines Peso"},
	"PLN": {id: 79, code: "PLN", symbol: "zł", englishName: "Poland Zloty"},
	"QAR": {id: 80, code: "QAR", symbol: "﷼", englishName: "Qatar Riyal"},
	"RON": {id: 81, code: "RON", symbol: "lei", englishName: "Romania New Leu"},
	"RUB": {id: 82, code: "RUB", symbol: "руб", englishName: "Russia Ruble"},
	"SHP": {id: 83, code: "SHP", symbol: "£", englishName: "Saint Helena Pound"},
	"SAR": {id: 84, code: "SAR", symbol: "﷼", englishName: "Saudi Arabia Riyal"},
	"RSD": {id: 85, code: "RSD", symbol: "Дин.", englishName: "Serbia Dinar"},
	"SCR": {id: 86, code: "SCR", symbol: "₨", englishName: "Seychelles Rupee"},
	"SGD": {id: 87, code: "SGD", symbol: "$", englishName: "Singapore Dollar"},
	"SBD": {id: 88, code: "SBD", symbol: "$", englishName: "Solomon Islands Dollar"},
	"SOS": {id: 89, code: "SOS", symbol: "S", englishName: "Somalia Shilling"},
	"ZAR": {id: 90, code: "ZAR", symbol: "R", englishName: "South Africa Rand"},
	"LKR": {id: 91, code: "LKR", symbol: "₨", englishName: "Sri Lanka Rupee"},
	"SEK": {id: 92, code: "SEK", symbol: "kr", englishName: "Sweden Krona"},
	"CHF": {id: 93, code: "CHF", symbol: "CHF", englishName: "Switzerland Franc"},
	"SRD": {id: 94, code: "SRD", symbol: "$", englishName: "Suriname Dollar"},
	"SYP": {id: 95, code: "SYP", symbol: "£", englishName: "Syria Pound"},
	"TWD": {id: 96, code: "TWD", symbol: "NT$", englishName: "Taiwan New Dollar"},
	"THB": {id: 97, code: "THB", symbol: "฿", englishName: "Thailand Baht"},
	"TTD": {id: 98, code: "TTD", symbol: "TT$", englishName: "Trinidad and Tobago Dollar"},
	"TRY": {id: 99, code: "TRY", symbol: "", englishName: "Turkey Lira"},
	"TVD": {id: 100, code: "TVD", symbol: "$", englishName: "Tuvalu Dollar"},
	"UAH": {id: 101, code: "UAH", symbol: "₴", englishName: "Ukraine Hryvnia"},
	"GBP": {id: 102, code: "GBP", symbol: "£", englishName: "United Kingdom Pound"},
	"USD": {id: 103, code: "USD", symbol: "$", englishName: "United States Dollar"},
	"UYU": {id: 104, code: "UYU", symbol: "$U", englishName: "Uruguay Peso"},
	"UZS": {id: 105, code: "UZS", symbol: "лв", englishName: "Uzbekistan Som"},
	"VEF": {id: 106, code: "VEF", symbol: "Bs", englishName: "Venezuela Bolivar"},
	"VND": {id: 107, code: "VND", symbol: "₫", englishName: "Viet Nam Dong"},
	"YER": {id: 108, code: "YER", symbol: "﷼", englishName: "Yemen Rial"},
	"ZWD": {id: 109, code: "ZWD", symbol: "Z$", englishName: "Zimbabwe Dollar"},
	"AED": {id: 110, code: "AED", numeral: "784", symbol: "د.إ", englishName: "United Arab Emirates Dirham"},
	"AMD": {id: 111, code: "AMD", numeral: "051", symbol: "֏", englishName: "Armenian Dram"},
	"AOA": {id: 112, code: "AOA", numeral: "973", symbol: "Kz", englishName: "Angola Kwanza"},
	"BDT": {id: 113, code: "BDT", numeral: "050", symbol: "৳", englishName: "Bangladeshi taka"},
	"BHD": {id: 114, code: "BHD", numeral: "048", symbol: ".د.ب", englishName: "Bahraini dinar"},
	"BIF": {id: 115, code: "BIF", numeral: "108", symbol: "FBu", englishName: "Burundian franc"},
	"BOV": {id: 116, code: "BOV", numeral: "984", symbol: "BOV", englishName: "Bolivian Mvdol"},
	"BTN": {id: 117, code: "BTN", numeral: "064", symbol: "Nu.", englishName: "Bhutanese ngultrum"},
	"CDF": {id: 118, code: "CDF", numeral: "976", symbol: "FC", englishName: "Congolese franc"},
	"CHE": {id: 119, code: "CHE", numeral: "947", symbol: "CHE", englishName: "WIR Euro"},
	"CHW": {id: 120, code: "CHW", numeral: "948", symbol: "CHW", englishName: "WIR Franc"},
	"CLF": {id: 121, code: "CLF", numeral: "990", symbol: "FC", englishName: "Unidad de Fomento"},
	"COU": {id: 122, code: "COU", numeral: "970", symbol: "UVR", englishName: "Unidad de Valor Rea"},
	"CUC": {id: 123, code: "CUC", numeral: "931", symbol: "CUC$", englishName: "Cuban convertible peso"},
	"CVE": {id: 124, code: "CVE", numeral: "132", symbol: "Esc$", englishName: "Cape Verdean escudo"},
	"DJF": {id: 125, code: "DJF", numeral: "262", symbol: "Fdj", englishName: "Djiboutian franc"},
	"DZD": {id: 126, code: "DZD", numeral: "012", symbol: "دج", englishName: "Algerian dinar"},
	"ERN": {id: 127, code: "ERN", numeral: "232", symbol: "ናቕፋ", englishName: "Eritrean nakfa"},
	"ETB": {id: 128, code: "ETB", numeral: "230", symbol: "ብር", englishName: "Ethiopian birr"},
	"GEL": {id: 129, code: "GEL", numeral: "981", symbol: "₾", englishName: "Georgian lari"},
	"GMD": {id: 130, code: "GMD", numeral: "270", symbol: "D", englishName: "Gambian dalasi"},
	"GNF": {id: 132, code: "GNF", numeral: "324", symbol: "FG", englishName: "Guinean franc"},
	"HTG": {id: 133, code: "HTG", numeral: "332", symbol: "G", englishName: "Haitian gourde"},
	"IQD": {id: 134, code: "IQD", numeral: "368", symbol: "د.ع", englishName: "Iraqi dinar"},
	"JOD": {id: 135, code: "JOD", numeral: "400", symbol: "JD", englishName: "Jordanian dinar"},
	"KES": {id: 136, code: "KES", numeral: "404", symbol: "KSh", englishName: "Kenyan shilling"},
	"KMF": {id: 137, code: "KMF", numeral: "174", symbol: "CF", englishName: "Comoros franc"},
	"KWD": {id: 138, code: "KWD", numeral: "414", symbol: "د.ك", englishName: "Kuwaiti dinar"},
	"LSL": {id: 139, code: "LSL", numeral: "426", symbol: "L", englishName: "Lesotho loti"},
	"LVL": {id: 141, code: "LVL", numeral: "428", symbol: "Ls", englishName: "Latvian lats"},
	"LYD": {id: 142, code: "LYD", numeral: "434", symbol: "ل.د", englishName: "Libyan dinar"},
	"MAD": {id: 143, code: "MAD", numeral: "504", symbol: "DH", englishName: "Moroccan dirham"},
	"MDL": {id: 144, code: "MDL", numeral: "498", symbol: "leu", englishName: "Moldovan leu"},
	"MGA": {id: 145, code: "MGA", numeral: "969", symbol: "Ar", englishName: "Malagasy ariary"},
	"MMK": {id: 146, code: "MMK", numeral: "104", symbol: "K", englishName: "Burmese kyat"},
	"MOP": {id: 147, code: "MOP", numeral: "446", symbol: "MOP$", englishName: "Macanese pataca"},
	"MVR": {id: 149, code: "MVR", numeral: "462", symbol: "Rf", englishName: "Maldivian rufiyaa"},
	"MWK": {id: 150, code: "MWK", numeral: "454", symbol: "K", englishName: "Malawian kwacha"},
	"MXV": {id: 151, code: "MXV", numeral: "979", symbol: "MXV", englishName: "Mexican unidad de inversión"},
	"PGK": {id: 152, code: "PGK", numeral: "598", symbol: "K", englishName: "Papua New Guinean kina"},
	"RWF": {id: 153, code: "RWF", numeral: "646", symbol: "FRw", englishName: "Rwandan franc"},
	"SDG": {id: 154, code: "SDG", numeral: "938", symbol: "ج.س", englishName: "Sudanese pound"},
	"SLL": {id: 156, code: "SLL", numeral: "694", symbol: "Le", englishName: "Sierra Leonean leone"},
	"SSP": {id: 157, code: "SSP", numeral: "728", symbol: "SSP", englishName: "South Sudanese pound"},
	"SZL": {id: 159, code: "SZL", numeral: "748", symbol: "L", englishName: "Swazi lilangeni"},
	"TJS": {id: 160, code: "TJS", numeral: "972", symbol: "TJS", englishName: "Tajikistani somoni"},
	"TMT": {id: 162, code: "TMT", numeral: "934", symbol: "T", englishName: "Turkmenistan manat"},
	"TND": {id: 163, code: "TND", numeral: "788", symbol: "د.ت", englishName: "Tunisian dinar"},
	"TOP": {id: 164, code: "TOP", numeral: "776", symbol: "T$", englishName: "Tongan paʻanga"},
	"TZS": {id: 165, code: "TZS", numeral: "834", symbol: "TSh", englishName: "Tanzanian shilling"},
	"UGX": {id: 166, code: "UGX", numeral: "800", symbol: "USh", englishName: "Ugandan shilling"},
	"USN": {id: 167, code: "USN", numeral: "997", symbol: "$", englishName: "United States Dollar (next day)"},
	"USS": {id: 168, code: "USS", numeral: "998", symbol: "$", englishName: "United States Dollar (same day)"},
	"VUV": {id: 169, code: "VUV", numeral: "548", symbol: "VT", englishName: "Vanuatu vatu"},
	"WST": {id: 170, code: "WST", numeral: "882", symbol: "WS$", englishName: "Samoan tālā"},
	"XAF": {id: 171, code: "XAF", numeral: "950", symbol: "FCFA", englishName: "Central African CFA franc"},
	"XAG": {id: 172, code: "XAG", numeral: "961", symbol: "Ag", englishName: "Silver"},
	"XAU": {id: 173, code: "XAU", numeral: "959", symbol: "Au", englishName: "Gold"},
	"XBA": {id: 174, code: "XBA", numeral: "955", symbol: "EURCO", englishName: "European Unit of Account"},
	"XBB": {id: 175, code: "XBB", numeral: "956", symbol: "E.M.U.-6", englishName: "European Monetary Unit"},
	"XBC": {id: 176, code: "XBC", numeral: "957", symbol: "E.U.A.-9", englishName: "European Unit of Account 9"},
	"XBD": {id: 177, code: "XBD", numeral: "958", symbol: "E.U.A.-17", englishName: "European Unit of Account 17"},
	"XDR": {id: 178, code: "XDR", numeral: "960", symbol: "SDR", englishName: "Special drawing rights"},
	"XOF": {id: 180, code: "XOF", numeral: "952", symbol: "CFA", englishName: "West African CFA franc"},
	"XPD": {id: 181, code: "XPD", numeral: "964", symbol: "Pd", englishName: "Palladium"},
	"XPF": {id: 182, code: "XPF", numeral: "953", symbol: "CFP", englishName: "CFP franc"},
	"XPT": {id: 183, code: "XPT", numeral: "962", symbol: "Pt", englishName: "Platinum"},
	"XTS": {id: 184, code: "XTS", numeral: "963", symbol: "XTS", englishName: "Code reserved for testing purposes"},
	"XXX": {id: 185, code: "XXX", numeral: "999", symbol: "XXX", englishName: "No currency"},
	"ZMW": {id: 186, code: "ZMW", numeral: "967", symbol: "ZK", englishName: "Zambian kwacha"},

	// Historical
	"BYR": {id: 201, code: "BYR", numeral: "974", symbol: "UF", englishName: "Belarusian ruble"},
	"LTL": {id: 202, code: "LTL", numeral: "440", symbol: "Lt", englishName: "Lithuanian litas"},
	"MRO": {id: 203, code: "MRO", numeral: "478", symbol: "UM", englishName: "Mauritanian ouguiya"},
	"STD": {id: 204, code: "STD", numeral: "678", symbol: "Db", englishName: "São Tomé and Príncipe Dobra"},
	"TMM": {id: 205, code: "TMM", numeral: "795", symbol: "T", englishName: "Turkmenistani manat"},
	"XFU": {id: 206, code: "XFU", numeral: "...", symbol: "XFU", englishName: "UIC franc"},

	// What is this?
	"SIL": {id: 300, code: "SIL", numeral: "TODO", symbol: "TODO", englishName: "TODO"},

	// TODO :: 777
	// - Re-sort all entries by name
	// - Add all numeral codes
	// - Add and mark historical/expired codes (show them in the dropdown with parentheses as expired)
}
