// Code generated by qtc from "servererror.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/servererror/servererror.qtpl:1
package servererror

//line pages/servererror/servererror.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/servererror/servererror.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/servererror/servererror.qtpl:1
func (p *page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/servererror/servererror.qtpl:1
	qw422016.N().S(`<link rel="stylesheet" href="/c/simpleBox.css">`)
//line pages/servererror/servererror.qtpl:1
}

//line pages/servererror/servererror.qtpl:1
func (p *page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/servererror/servererror.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/servererror/servererror.qtpl:1
	p.StreamStylesheets(qw422016)
//line pages/servererror/servererror.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/servererror/servererror.qtpl:1
}

//line pages/servererror/servererror.qtpl:1
func (p *page) Stylesheets() string {
//line pages/servererror/servererror.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/servererror/servererror.qtpl:1
	p.WriteStylesheets(qb422016)
//line pages/servererror/servererror.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/servererror/servererror.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/servererror/servererror.qtpl:1
	return qs422016
//line pages/servererror/servererror.qtpl:1
}

//line pages/servererror/servererror.qtpl:3
func (p *page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/servererror/servererror.qtpl:3
	qw422016.E().S(p.title)
//line pages/servererror/servererror.qtpl:3
}

//line pages/servererror/servererror.qtpl:3
func (p *page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/servererror/servererror.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/servererror/servererror.qtpl:3
	p.StreamTitle(qw422016)
//line pages/servererror/servererror.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/servererror/servererror.qtpl:3
}

//line pages/servererror/servererror.qtpl:3
func (p *page) Title() string {
//line pages/servererror/servererror.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/servererror/servererror.qtpl:3
	p.WriteTitle(qb422016)
//line pages/servererror/servererror.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/servererror/servererror.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/servererror/servererror.qtpl:3
	return qs422016
//line pages/servererror/servererror.qtpl:3
}

//line pages/servererror/servererror.qtpl:5
func (p *page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/servererror/servererror.qtpl:5
	qw422016.N().S(`<div class="simpleBox" style="width: 90%;"><h1>`)
//line pages/servererror/servererror.qtpl:7
	qw422016.E().S(p.title)
//line pages/servererror/servererror.qtpl:7
	qw422016.N().S(`</h1><pre style="text-align: left;">`)
//line pages/servererror/servererror.qtpl:8
	qw422016.E().S(p.message)
//line pages/servererror/servererror.qtpl:8
	qw422016.N().S(`</pre></div>`)
//line pages/servererror/servererror.qtpl:10
}

//line pages/servererror/servererror.qtpl:10
func (p *page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/servererror/servererror.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/servererror/servererror.qtpl:10
	p.StreamContent(qw422016)
//line pages/servererror/servererror.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line pages/servererror/servererror.qtpl:10
}

//line pages/servererror/servererror.qtpl:10
func (p *page) Content() string {
//line pages/servererror/servererror.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/servererror/servererror.qtpl:10
	p.WriteContent(qb422016)
//line pages/servererror/servererror.qtpl:10
	qs422016 := string(qb422016.B)
//line pages/servererror/servererror.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/servererror/servererror.qtpl:10
	return qs422016
//line pages/servererror/servererror.qtpl:10
}
