// Code generated by espal-store-synthesizer. DO NOT EDIT.
package returnorder

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ ReturnOrderEntity = &ReturnOrder{}

type ReturnOrderEntity interface {
	database.Model
	DomainID() string
	SetDomainID(domainID string)
	UserID() string
	SetUserID(userID string)
	Comments() *string
	SetComments(comments *string)
}

// TableName returns the table name that belongs to the current model.
func (returnOrder *ReturnOrder) TableName() string {
	return "ReturnOrder"
}

// TableAlias returns the unique resolved table alias for use in queries.
func (returnOrder *ReturnOrder) TableAlias() string {
	return "roe"
}

// ID returns id.
func (returnOrder *ReturnOrder) ID() string {
	return returnOrder.id
}

// CreatedByID returns createdByID.
func (returnOrder *ReturnOrder) CreatedByID() string {
	return returnOrder.createdByID
}

// SetCreatedByID sets the createdByID.
func (returnOrder *ReturnOrder) SetCreatedByID(createdByID string) {
	returnOrder.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (returnOrder *ReturnOrder) UpdatedByID() *string {
	return returnOrder.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (returnOrder *ReturnOrder) SetUpdatedByID(updatedByID *string) {
	returnOrder.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (returnOrder *ReturnOrder) CreatedAt() time.Time {
	return returnOrder.createdAt
}

// SetCreatedAt sets the createdAt.
func (returnOrder *ReturnOrder) SetCreatedAt(createdAt time.Time) {
	returnOrder.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (returnOrder *ReturnOrder) UpdatedAt() *time.Time {
	return returnOrder.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (returnOrder *ReturnOrder) SetUpdatedAt(updatedAt *time.Time) {
	returnOrder.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (returnOrder *ReturnOrder) CreatedByFirstName() *string {
	return returnOrder.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (returnOrder *ReturnOrder) SetCreatedByFirstName(createdByFirstName *string) {
	returnOrder.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (returnOrder *ReturnOrder) CreatedBySurname() *string {
	return returnOrder.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (returnOrder *ReturnOrder) SetCreatedBySurname(createdBySurname *string) {
	returnOrder.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (returnOrder *ReturnOrder) UpdatedByFirstName() *string {
	return returnOrder.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (returnOrder *ReturnOrder) SetUpdatedByFirstName(updatedByFirstName *string) {
	returnOrder.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (returnOrder *ReturnOrder) UpdatedBySurname() *string {
	return returnOrder.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (returnOrder *ReturnOrder) SetUpdatedBySurname(updatedBySurname *string) {
	returnOrder.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (returnOrder *ReturnOrder) IsUpdated() bool {
	return returnOrder.updatedByID != nil
}

// DomainID returns domainID.
func (returnOrder *ReturnOrder) DomainID() string {
	return returnOrder.domainID
}

// SetDomainID sets the domainID.
func (returnOrder *ReturnOrder) SetDomainID(domainID string) {
	returnOrder.domainID = domainID
}

// UserID returns userID.
func (returnOrder *ReturnOrder) UserID() string {
	return returnOrder.userID
}

// SetUserID sets the userID.
func (returnOrder *ReturnOrder) SetUserID(userID string) {
	returnOrder.userID = userID
}

// Comments returns comments.
func (returnOrder *ReturnOrder) Comments() *string {
	return returnOrder.comments
}

// SetComments sets the comments.
func (returnOrder *ReturnOrder) SetComments(comments *string) {
	returnOrder.comments = comments
}

func newReturnOrder() *ReturnOrder {
	return &ReturnOrder{}
}

// New returns a new instance of ReturnOrderEntity.
func NewReturnOrderEntity() ReturnOrderEntity {
	return newReturnOrder()
}
