// Code generated by espal-store-synthesizer. DO NOT EDIT.
package returnorder_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/returnorder"
)

func TestReturnOrderTable(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	if returnOrder.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestReturnOrderTableAlias(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	if returnOrder.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestReturnOrderIsUpdated(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	returnOrder.IsUpdated()
}

func TestReturnOrderID(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	returnOrder.ID()
}

func TestReturnOrderCreatedByID(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetCreatedByID(testValue)
	if testValue != returnOrder.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderUpdatedByID(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetUpdatedByID(&testValue)
	if &testValue != returnOrder.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderCreatedAt(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := time.Now()
	returnOrder.SetCreatedAt(testValue)
	if testValue != returnOrder.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderUpdatedAt(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := time.Now()
	returnOrder.SetUpdatedAt(&testValue)
	if &testValue != returnOrder.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderCreatedByFirstName(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetCreatedByFirstName(&testValue)
	if &testValue != returnOrder.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderCreatedBySurname(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetCreatedBySurname(&testValue)
	if &testValue != returnOrder.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderUpdatedByFirstName(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetUpdatedByFirstName(&testValue)
	if &testValue != returnOrder.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderUpdatedBySurname(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetUpdatedBySurname(&testValue)
	if &testValue != returnOrder.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderDomainID(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetDomainID(testValue)
	if testValue != returnOrder.DomainID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderUserID(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetUserID(testValue)
	if testValue != returnOrder.UserID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestReturnOrderComments(t *testing.T) {
	returnOrder := returnorder.NewReturnOrderEntity()
	testValue := "testValue"
	returnOrder.SetComments(&testValue)
	if &testValue != returnOrder.Comments() {
		t.Fatal("Getter did not return the Set value")
	}
}
