// Code generated by espal-store-synthesizer. DO NOT EDIT.
package stocklocation

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ StockLocationEntity = &StockLocation{}

type StockLocationEntity interface {
	database.Model
}

// TableName returns the table name that belongs to the current model.
func (stockLocation *StockLocation) TableName() string {
	return "StockLocation"
}

// TableAlias returns the unique resolved table alias for use in queries.
func (stockLocation *StockLocation) TableAlias() string {
	return "sle"
}

// ID returns id.
func (stockLocation *StockLocation) ID() string {
	return stockLocation.id
}

// CreatedByID returns createdByID.
func (stockLocation *StockLocation) CreatedByID() string {
	return stockLocation.createdByID
}

// SetCreatedByID sets the createdByID.
func (stockLocation *StockLocation) SetCreatedByID(createdByID string) {
	stockLocation.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (stockLocation *StockLocation) UpdatedByID() *string {
	return stockLocation.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (stockLocation *StockLocation) SetUpdatedByID(updatedByID *string) {
	stockLocation.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (stockLocation *StockLocation) CreatedAt() time.Time {
	return stockLocation.createdAt
}

// SetCreatedAt sets the createdAt.
func (stockLocation *StockLocation) SetCreatedAt(createdAt time.Time) {
	stockLocation.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (stockLocation *StockLocation) UpdatedAt() *time.Time {
	return stockLocation.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (stockLocation *StockLocation) SetUpdatedAt(updatedAt *time.Time) {
	stockLocation.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (stockLocation *StockLocation) CreatedByFirstName() *string {
	return stockLocation.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (stockLocation *StockLocation) SetCreatedByFirstName(createdByFirstName *string) {
	stockLocation.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (stockLocation *StockLocation) CreatedBySurname() *string {
	return stockLocation.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (stockLocation *StockLocation) SetCreatedBySurname(createdBySurname *string) {
	stockLocation.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (stockLocation *StockLocation) UpdatedByFirstName() *string {
	return stockLocation.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (stockLocation *StockLocation) SetUpdatedByFirstName(updatedByFirstName *string) {
	stockLocation.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (stockLocation *StockLocation) UpdatedBySurname() *string {
	return stockLocation.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (stockLocation *StockLocation) SetUpdatedBySurname(updatedBySurname *string) {
	stockLocation.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (stockLocation *StockLocation) IsUpdated() bool {
	return stockLocation.updatedByID != nil
}

func newStockLocation() *StockLocation {
	return &StockLocation{}
}

// New returns a new instance of StockLocationEntity.
func NewStockLocationEntity() StockLocationEntity {
	return newStockLocation()
}
