// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package loggermock

import (
	"sync"
)

var (
	lockLoggerMockCustom         sync.RWMutex
	lockLoggerMockCustomf        sync.RWMutex
	lockLoggerMockDisable        sync.RWMutex
	lockLoggerMockEnable         sync.RWMutex
	lockLoggerMockEnableTestMode sync.RWMutex
	lockLoggerMockError          sync.RWMutex
	lockLoggerMockErrorf         sync.RWMutex
	lockLoggerMockGetLastMessage sync.RWMutex
	lockLoggerMockInfo           sync.RWMutex
	lockLoggerMockInfof          sync.RWMutex
	lockLoggerMockIsEnabled      sync.RWMutex
	lockLoggerMockWarning        sync.RWMutex
	lockLoggerMockWarningf       sync.RWMutex
)

// LoggerMock is a mock implementation of Logger.
//
//     func TestSomethingThatUsesLogger(t *testing.T) {
//
//         // make and configure a mocked Logger
//         mockedLogger := &LoggerMock{
//             CustomFunc: func(message string, callback func(string) string)  {
// 	               panic("mock out the Custom method")
//             },
//             CustomfFunc: func(message string, callback func(string) string, params ...interface{})  {
// 	               panic("mock out the Customf method")
//             },
//             DisableFunc: func()  {
// 	               panic("mock out the Disable method")
//             },
//             EnableFunc: func()  {
// 	               panic("mock out the Enable method")
//             },
//             EnableTestModeFunc: func()  {
// 	               panic("mock out the EnableTestMode method")
//             },
//             ErrorFunc: func(message string)  {
// 	               panic("mock out the Error method")
//             },
//             ErrorfFunc: func(message string, params ...interface{})  {
// 	               panic("mock out the Errorf method")
//             },
//             GetLastMessageFunc: func() string {
// 	               panic("mock out the GetLastMessage method")
//             },
//             InfoFunc: func(message string)  {
// 	               panic("mock out the Info method")
//             },
//             InfofFunc: func(message string, params ...interface{})  {
// 	               panic("mock out the Infof method")
//             },
//             IsEnabledFunc: func() bool {
// 	               panic("mock out the IsEnabled method")
//             },
//             WarningFunc: func(message string)  {
// 	               panic("mock out the Warning method")
//             },
//             WarningfFunc: func(message string, params ...interface{})  {
// 	               panic("mock out the Warningf method")
//             },
//         }
//
//         // use mockedLogger in code that requires Logger
//         // and then make assertions.
//
//     }
type LoggerMock struct {
	// CustomFunc mocks the Custom method.
	CustomFunc func(message string, callback func(string) string)

	// CustomfFunc mocks the Customf method.
	CustomfFunc func(message string, callback func(string) string, params ...interface{})

	// DisableFunc mocks the Disable method.
	DisableFunc func()

	// EnableFunc mocks the Enable method.
	EnableFunc func()

	// EnableTestModeFunc mocks the EnableTestMode method.
	EnableTestModeFunc func()

	// ErrorFunc mocks the Error method.
	ErrorFunc func(message string)

	// ErrorfFunc mocks the Errorf method.
	ErrorfFunc func(message string, params ...interface{})

	// GetLastMessageFunc mocks the GetLastMessage method.
	GetLastMessageFunc func() string

	// InfoFunc mocks the Info method.
	InfoFunc func(message string)

	// InfofFunc mocks the Infof method.
	InfofFunc func(message string, params ...interface{})

	// IsEnabledFunc mocks the IsEnabled method.
	IsEnabledFunc func() bool

	// WarningFunc mocks the Warning method.
	WarningFunc func(message string)

	// WarningfFunc mocks the Warningf method.
	WarningfFunc func(message string, params ...interface{})

	// calls tracks calls to the methods.
	calls struct {
		// Custom holds details about calls to the Custom method.
		Custom []struct {
			// Message is the message argument value.
			Message string
			// Callback is the callback argument value.
			Callback func(string) string
		}
		// Customf holds details about calls to the Customf method.
		Customf []struct {
			// Message is the message argument value.
			Message string
			// Callback is the callback argument value.
			Callback func(string) string
			// Params is the params argument value.
			Params []interface{}
		}
		// Disable holds details about calls to the Disable method.
		Disable []struct {
		}
		// Enable holds details about calls to the Enable method.
		Enable []struct {
		}
		// EnableTestMode holds details about calls to the EnableTestMode method.
		EnableTestMode []struct {
		}
		// Error holds details about calls to the Error method.
		Error []struct {
			// Message is the message argument value.
			Message string
		}
		// Errorf holds details about calls to the Errorf method.
		Errorf []struct {
			// Message is the message argument value.
			Message string
			// Params is the params argument value.
			Params []interface{}
		}
		// GetLastMessage holds details about calls to the GetLastMessage method.
		GetLastMessage []struct {
		}
		// Info holds details about calls to the Info method.
		Info []struct {
			// Message is the message argument value.
			Message string
		}
		// Infof holds details about calls to the Infof method.
		Infof []struct {
			// Message is the message argument value.
			Message string
			// Params is the params argument value.
			Params []interface{}
		}
		// IsEnabled holds details about calls to the IsEnabled method.
		IsEnabled []struct {
		}
		// Warning holds details about calls to the Warning method.
		Warning []struct {
			// Message is the message argument value.
			Message string
		}
		// Warningf holds details about calls to the Warningf method.
		Warningf []struct {
			// Message is the message argument value.
			Message string
			// Params is the params argument value.
			Params []interface{}
		}
	}
}

// Custom calls CustomFunc.
func (mock *LoggerMock) Custom(message string, callback func(string) string) {
	if mock.CustomFunc == nil {
		panic("LoggerMock.CustomFunc: method is nil but Logger.Custom was just called")
	}
	callInfo := struct {
		Message  string
		Callback func(string) string
	}{
		Message:  message,
		Callback: callback,
	}
	lockLoggerMockCustom.Lock()
	mock.calls.Custom = append(mock.calls.Custom, callInfo)
	lockLoggerMockCustom.Unlock()
	mock.CustomFunc(message, callback)
}

// CustomCalls gets all the calls that were made to Custom.
// Check the length with:
//     len(mockedLogger.CustomCalls())
func (mock *LoggerMock) CustomCalls() []struct {
	Message  string
	Callback func(string) string
} {
	var calls []struct {
		Message  string
		Callback func(string) string
	}
	lockLoggerMockCustom.RLock()
	calls = mock.calls.Custom
	lockLoggerMockCustom.RUnlock()
	return calls
}

// Customf calls CustomfFunc.
func (mock *LoggerMock) Customf(message string, callback func(string) string, params ...interface{}) {
	if mock.CustomfFunc == nil {
		panic("LoggerMock.CustomfFunc: method is nil but Logger.Customf was just called")
	}
	callInfo := struct {
		Message  string
		Callback func(string) string
		Params   []interface{}
	}{
		Message:  message,
		Callback: callback,
		Params:   params,
	}
	lockLoggerMockCustomf.Lock()
	mock.calls.Customf = append(mock.calls.Customf, callInfo)
	lockLoggerMockCustomf.Unlock()
	mock.CustomfFunc(message, callback, params...)
}

// CustomfCalls gets all the calls that were made to Customf.
// Check the length with:
//     len(mockedLogger.CustomfCalls())
func (mock *LoggerMock) CustomfCalls() []struct {
	Message  string
	Callback func(string) string
	Params   []interface{}
} {
	var calls []struct {
		Message  string
		Callback func(string) string
		Params   []interface{}
	}
	lockLoggerMockCustomf.RLock()
	calls = mock.calls.Customf
	lockLoggerMockCustomf.RUnlock()
	return calls
}

// Disable calls DisableFunc.
func (mock *LoggerMock) Disable() {
	if mock.DisableFunc == nil {
		panic("LoggerMock.DisableFunc: method is nil but Logger.Disable was just called")
	}
	callInfo := struct {
	}{}
	lockLoggerMockDisable.Lock()
	mock.calls.Disable = append(mock.calls.Disable, callInfo)
	lockLoggerMockDisable.Unlock()
	mock.DisableFunc()
}

// DisableCalls gets all the calls that were made to Disable.
// Check the length with:
//     len(mockedLogger.DisableCalls())
func (mock *LoggerMock) DisableCalls() []struct {
} {
	var calls []struct {
	}
	lockLoggerMockDisable.RLock()
	calls = mock.calls.Disable
	lockLoggerMockDisable.RUnlock()
	return calls
}

// Enable calls EnableFunc.
func (mock *LoggerMock) Enable() {
	if mock.EnableFunc == nil {
		panic("LoggerMock.EnableFunc: method is nil but Logger.Enable was just called")
	}
	callInfo := struct {
	}{}
	lockLoggerMockEnable.Lock()
	mock.calls.Enable = append(mock.calls.Enable, callInfo)
	lockLoggerMockEnable.Unlock()
	mock.EnableFunc()
}

// EnableCalls gets all the calls that were made to Enable.
// Check the length with:
//     len(mockedLogger.EnableCalls())
func (mock *LoggerMock) EnableCalls() []struct {
} {
	var calls []struct {
	}
	lockLoggerMockEnable.RLock()
	calls = mock.calls.Enable
	lockLoggerMockEnable.RUnlock()
	return calls
}

// EnableTestMode calls EnableTestModeFunc.
func (mock *LoggerMock) EnableTestMode() {
	if mock.EnableTestModeFunc == nil {
		panic("LoggerMock.EnableTestModeFunc: method is nil but Logger.EnableTestMode was just called")
	}
	callInfo := struct {
	}{}
	lockLoggerMockEnableTestMode.Lock()
	mock.calls.EnableTestMode = append(mock.calls.EnableTestMode, callInfo)
	lockLoggerMockEnableTestMode.Unlock()
	mock.EnableTestModeFunc()
}

// EnableTestModeCalls gets all the calls that were made to EnableTestMode.
// Check the length with:
//     len(mockedLogger.EnableTestModeCalls())
func (mock *LoggerMock) EnableTestModeCalls() []struct {
} {
	var calls []struct {
	}
	lockLoggerMockEnableTestMode.RLock()
	calls = mock.calls.EnableTestMode
	lockLoggerMockEnableTestMode.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *LoggerMock) Error(message string) {
	if mock.ErrorFunc == nil {
		panic("LoggerMock.ErrorFunc: method is nil but Logger.Error was just called")
	}
	callInfo := struct {
		Message string
	}{
		Message: message,
	}
	lockLoggerMockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	lockLoggerMockError.Unlock()
	mock.ErrorFunc(message)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//     len(mockedLogger.ErrorCalls())
func (mock *LoggerMock) ErrorCalls() []struct {
	Message string
} {
	var calls []struct {
		Message string
	}
	lockLoggerMockError.RLock()
	calls = mock.calls.Error
	lockLoggerMockError.RUnlock()
	return calls
}

// Errorf calls ErrorfFunc.
func (mock *LoggerMock) Errorf(message string, params ...interface{}) {
	if mock.ErrorfFunc == nil {
		panic("LoggerMock.ErrorfFunc: method is nil but Logger.Errorf was just called")
	}
	callInfo := struct {
		Message string
		Params  []interface{}
	}{
		Message: message,
		Params:  params,
	}
	lockLoggerMockErrorf.Lock()
	mock.calls.Errorf = append(mock.calls.Errorf, callInfo)
	lockLoggerMockErrorf.Unlock()
	mock.ErrorfFunc(message, params...)
}

// ErrorfCalls gets all the calls that were made to Errorf.
// Check the length with:
//     len(mockedLogger.ErrorfCalls())
func (mock *LoggerMock) ErrorfCalls() []struct {
	Message string
	Params  []interface{}
} {
	var calls []struct {
		Message string
		Params  []interface{}
	}
	lockLoggerMockErrorf.RLock()
	calls = mock.calls.Errorf
	lockLoggerMockErrorf.RUnlock()
	return calls
}

// GetLastMessage calls GetLastMessageFunc.
func (mock *LoggerMock) GetLastMessage() string {
	if mock.GetLastMessageFunc == nil {
		panic("LoggerMock.GetLastMessageFunc: method is nil but Logger.GetLastMessage was just called")
	}
	callInfo := struct {
	}{}
	lockLoggerMockGetLastMessage.Lock()
	mock.calls.GetLastMessage = append(mock.calls.GetLastMessage, callInfo)
	lockLoggerMockGetLastMessage.Unlock()
	return mock.GetLastMessageFunc()
}

// GetLastMessageCalls gets all the calls that were made to GetLastMessage.
// Check the length with:
//     len(mockedLogger.GetLastMessageCalls())
func (mock *LoggerMock) GetLastMessageCalls() []struct {
} {
	var calls []struct {
	}
	lockLoggerMockGetLastMessage.RLock()
	calls = mock.calls.GetLastMessage
	lockLoggerMockGetLastMessage.RUnlock()
	return calls
}

// Info calls InfoFunc.
func (mock *LoggerMock) Info(message string) {
	if mock.InfoFunc == nil {
		panic("LoggerMock.InfoFunc: method is nil but Logger.Info was just called")
	}
	callInfo := struct {
		Message string
	}{
		Message: message,
	}
	lockLoggerMockInfo.Lock()
	mock.calls.Info = append(mock.calls.Info, callInfo)
	lockLoggerMockInfo.Unlock()
	mock.InfoFunc(message)
}

// InfoCalls gets all the calls that were made to Info.
// Check the length with:
//     len(mockedLogger.InfoCalls())
func (mock *LoggerMock) InfoCalls() []struct {
	Message string
} {
	var calls []struct {
		Message string
	}
	lockLoggerMockInfo.RLock()
	calls = mock.calls.Info
	lockLoggerMockInfo.RUnlock()
	return calls
}

// Infof calls InfofFunc.
func (mock *LoggerMock) Infof(message string, params ...interface{}) {
	if mock.InfofFunc == nil {
		panic("LoggerMock.InfofFunc: method is nil but Logger.Infof was just called")
	}
	callInfo := struct {
		Message string
		Params  []interface{}
	}{
		Message: message,
		Params:  params,
	}
	lockLoggerMockInfof.Lock()
	mock.calls.Infof = append(mock.calls.Infof, callInfo)
	lockLoggerMockInfof.Unlock()
	mock.InfofFunc(message, params...)
}

// InfofCalls gets all the calls that were made to Infof.
// Check the length with:
//     len(mockedLogger.InfofCalls())
func (mock *LoggerMock) InfofCalls() []struct {
	Message string
	Params  []interface{}
} {
	var calls []struct {
		Message string
		Params  []interface{}
	}
	lockLoggerMockInfof.RLock()
	calls = mock.calls.Infof
	lockLoggerMockInfof.RUnlock()
	return calls
}

// IsEnabled calls IsEnabledFunc.
func (mock *LoggerMock) IsEnabled() bool {
	if mock.IsEnabledFunc == nil {
		panic("LoggerMock.IsEnabledFunc: method is nil but Logger.IsEnabled was just called")
	}
	callInfo := struct {
	}{}
	lockLoggerMockIsEnabled.Lock()
	mock.calls.IsEnabled = append(mock.calls.IsEnabled, callInfo)
	lockLoggerMockIsEnabled.Unlock()
	return mock.IsEnabledFunc()
}

// IsEnabledCalls gets all the calls that were made to IsEnabled.
// Check the length with:
//     len(mockedLogger.IsEnabledCalls())
func (mock *LoggerMock) IsEnabledCalls() []struct {
} {
	var calls []struct {
	}
	lockLoggerMockIsEnabled.RLock()
	calls = mock.calls.IsEnabled
	lockLoggerMockIsEnabled.RUnlock()
	return calls
}

// Warning calls WarningFunc.
func (mock *LoggerMock) Warning(message string) {
	if mock.WarningFunc == nil {
		panic("LoggerMock.WarningFunc: method is nil but Logger.Warning was just called")
	}
	callInfo := struct {
		Message string
	}{
		Message: message,
	}
	lockLoggerMockWarning.Lock()
	mock.calls.Warning = append(mock.calls.Warning, callInfo)
	lockLoggerMockWarning.Unlock()
	mock.WarningFunc(message)
}

// WarningCalls gets all the calls that were made to Warning.
// Check the length with:
//     len(mockedLogger.WarningCalls())
func (mock *LoggerMock) WarningCalls() []struct {
	Message string
} {
	var calls []struct {
		Message string
	}
	lockLoggerMockWarning.RLock()
	calls = mock.calls.Warning
	lockLoggerMockWarning.RUnlock()
	return calls
}

// Warningf calls WarningfFunc.
func (mock *LoggerMock) Warningf(message string, params ...interface{}) {
	if mock.WarningfFunc == nil {
		panic("LoggerMock.WarningfFunc: method is nil but Logger.Warningf was just called")
	}
	callInfo := struct {
		Message string
		Params  []interface{}
	}{
		Message: message,
		Params:  params,
	}
	lockLoggerMockWarningf.Lock()
	mock.calls.Warningf = append(mock.calls.Warningf, callInfo)
	lockLoggerMockWarningf.Unlock()
	mock.WarningfFunc(message, params...)
}

// WarningfCalls gets all the calls that were made to Warningf.
// Check the length with:
//     len(mockedLogger.WarningfCalls())
func (mock *LoggerMock) WarningfCalls() []struct {
	Message string
	Params  []interface{}
} {
	var calls []struct {
		Message string
		Params  []interface{}
	}
	lockLoggerMockWarningf.RLock()
	calls = mock.calls.Warningf
	lockLoggerMockWarningf.RUnlock()
	return calls
}
