// Code generated by espal-store-synthesizer. DO NOT EDIT.
package invoice

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ InvoiceEntity = &Invoice{}

type InvoiceEntity interface {
	database.Model
	DomainID() string
	SetDomainID(domainID string)
	UserID() string
	SetUserID(userID string)
	SaleOrderID() string
	SetSaleOrderID(saleOrderID string)
	Currency() uint
	SetCurrency(currency uint)
	Code() *string
	SetCode(code *string)
	UserInfoBusiness() bool
	SetUserInfoBusiness(userInfoBusiness bool)
	UserInfoBusinessCocNumber() *string
	SetUserInfoBusinessCocNumber(userInfoBusinessCocNumber *string)
	UserInfoFirstName() string
	SetUserInfoFirstName(userInfoFirstName string)
	UserInfoSurname() string
	SetUserInfoSurname(userInfoSurname string)
	UserInfoStreet() string
	SetUserInfoStreet(userInfoStreet string)
	UserInfoStreetLine2() *string
	SetUserInfoStreetLine2(userInfoStreetLine2 *string)
	UserInfoNumber() string
	SetUserInfoNumber(userInfoNumber string)
	UserInfoNumberAddition() *string
	SetUserInfoNumberAddition(userInfoNumberAddition *string)
	UserInfoZipCode() string
	SetUserInfoZipCode(userInfoZipCode string)
	UserInfoCity() string
	SetUserInfoCity(userInfoCity string)
	UserInfoState() *uint
	SetUserInfoState(userInfoState *uint)
	UserInfoCountry() *uint16
	SetUserInfoCountry(userInfoCountry *uint16)
	UserInfoPhoneNumber() *string
	SetUserInfoPhoneNumber(userInfoPhoneNumber *string)
	UserInfoEmail() *string
	SetUserInfoEmail(userInfoEmail *string)
	Comments() *string
	SetComments(comments *string)
	SellingPartyAutograph() *string
	SetSellingPartyAutograph(sellingPartyAutograph *string)
	BuyingPartyAutograph() *string
	SetBuyingPartyAutograph(buyingPartyAutograph *string)
}

// TableName returns the table name that belongs to the current model.
func (invoice *Invoice) TableName() string {
	return "Invoice"
}

// TableAlias returns the unique resolved table alias for use in queries.
func (invoice *Invoice) TableAlias() string {
	return "ie"
}

// ID returns id.
func (invoice *Invoice) ID() string {
	return invoice.id
}

// CreatedByID returns createdByID.
func (invoice *Invoice) CreatedByID() string {
	return invoice.createdByID
}

// SetCreatedByID sets the createdByID.
func (invoice *Invoice) SetCreatedByID(createdByID string) {
	invoice.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (invoice *Invoice) UpdatedByID() *string {
	return invoice.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (invoice *Invoice) SetUpdatedByID(updatedByID *string) {
	invoice.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (invoice *Invoice) CreatedAt() time.Time {
	return invoice.createdAt
}

// SetCreatedAt sets the createdAt.
func (invoice *Invoice) SetCreatedAt(createdAt time.Time) {
	invoice.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (invoice *Invoice) UpdatedAt() *time.Time {
	return invoice.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (invoice *Invoice) SetUpdatedAt(updatedAt *time.Time) {
	invoice.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (invoice *Invoice) CreatedByFirstName() *string {
	return invoice.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (invoice *Invoice) SetCreatedByFirstName(createdByFirstName *string) {
	invoice.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (invoice *Invoice) CreatedBySurname() *string {
	return invoice.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (invoice *Invoice) SetCreatedBySurname(createdBySurname *string) {
	invoice.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (invoice *Invoice) UpdatedByFirstName() *string {
	return invoice.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (invoice *Invoice) SetUpdatedByFirstName(updatedByFirstName *string) {
	invoice.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (invoice *Invoice) UpdatedBySurname() *string {
	return invoice.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (invoice *Invoice) SetUpdatedBySurname(updatedBySurname *string) {
	invoice.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (invoice *Invoice) IsUpdated() bool {
	return invoice.updatedByID != nil
}

// DomainID returns domainID.
func (invoice *Invoice) DomainID() string {
	return invoice.domainID
}

// SetDomainID sets the domainID.
func (invoice *Invoice) SetDomainID(domainID string) {
	invoice.domainID = domainID
}

// UserID returns userID.
func (invoice *Invoice) UserID() string {
	return invoice.userID
}

// SetUserID sets the userID.
func (invoice *Invoice) SetUserID(userID string) {
	invoice.userID = userID
}

// SaleOrderID returns saleOrderID.
func (invoice *Invoice) SaleOrderID() string {
	return invoice.saleOrderID
}

// SetSaleOrderID sets the saleOrderID.
func (invoice *Invoice) SetSaleOrderID(saleOrderID string) {
	invoice.saleOrderID = saleOrderID
}

// Currency returns currency.
func (invoice *Invoice) Currency() uint {
	return invoice.currency
}

// SetCurrency sets the currency.
func (invoice *Invoice) SetCurrency(currency uint) {
	invoice.currency = currency
}

// Code returns code.
func (invoice *Invoice) Code() *string {
	return invoice.code
}

// SetCode sets the code.
func (invoice *Invoice) SetCode(code *string) {
	invoice.code = code
}

// UserInfoBusiness returns userInfoBusiness.
func (invoice *Invoice) UserInfoBusiness() bool {
	return invoice.userInfoBusiness
}

// SetUserInfoBusiness sets the userInfoBusiness.
func (invoice *Invoice) SetUserInfoBusiness(userInfoBusiness bool) {
	invoice.userInfoBusiness = userInfoBusiness
}

// UserInfoBusinessCocNumber returns userInfoBusinessCocNumber.
func (invoice *Invoice) UserInfoBusinessCocNumber() *string {
	return invoice.userInfoBusinessCocNumber
}

// SetUserInfoBusinessCocNumber sets the userInfoBusinessCocNumber.
func (invoice *Invoice) SetUserInfoBusinessCocNumber(userInfoBusinessCocNumber *string) {
	invoice.userInfoBusinessCocNumber = userInfoBusinessCocNumber
}

// UserInfoFirstName returns userInfoFirstName.
func (invoice *Invoice) UserInfoFirstName() string {
	return invoice.userInfoFirstName
}

// SetUserInfoFirstName sets the userInfoFirstName.
func (invoice *Invoice) SetUserInfoFirstName(userInfoFirstName string) {
	invoice.userInfoFirstName = userInfoFirstName
}

// UserInfoSurname returns userInfoSurname.
func (invoice *Invoice) UserInfoSurname() string {
	return invoice.userInfoSurname
}

// SetUserInfoSurname sets the userInfoSurname.
func (invoice *Invoice) SetUserInfoSurname(userInfoSurname string) {
	invoice.userInfoSurname = userInfoSurname
}

// UserInfoStreet returns userInfoStreet.
func (invoice *Invoice) UserInfoStreet() string {
	return invoice.userInfoStreet
}

// SetUserInfoStreet sets the userInfoStreet.
func (invoice *Invoice) SetUserInfoStreet(userInfoStreet string) {
	invoice.userInfoStreet = userInfoStreet
}

// UserInfoStreetLine2 returns userInfoStreetLine2.
func (invoice *Invoice) UserInfoStreetLine2() *string {
	return invoice.userInfoStreetLine2
}

// SetUserInfoStreetLine2 sets the userInfoStreetLine2.
func (invoice *Invoice) SetUserInfoStreetLine2(userInfoStreetLine2 *string) {
	invoice.userInfoStreetLine2 = userInfoStreetLine2
}

// UserInfoNumber returns userInfoNumber.
func (invoice *Invoice) UserInfoNumber() string {
	return invoice.userInfoNumber
}

// SetUserInfoNumber sets the userInfoNumber.
func (invoice *Invoice) SetUserInfoNumber(userInfoNumber string) {
	invoice.userInfoNumber = userInfoNumber
}

// UserInfoNumberAddition returns userInfoNumberAddition.
func (invoice *Invoice) UserInfoNumberAddition() *string {
	return invoice.userInfoNumberAddition
}

// SetUserInfoNumberAddition sets the userInfoNumberAddition.
func (invoice *Invoice) SetUserInfoNumberAddition(userInfoNumberAddition *string) {
	invoice.userInfoNumberAddition = userInfoNumberAddition
}

// UserInfoZipCode returns userInfoZipCode.
func (invoice *Invoice) UserInfoZipCode() string {
	return invoice.userInfoZipCode
}

// SetUserInfoZipCode sets the userInfoZipCode.
func (invoice *Invoice) SetUserInfoZipCode(userInfoZipCode string) {
	invoice.userInfoZipCode = userInfoZipCode
}

// UserInfoCity returns userInfoCity.
func (invoice *Invoice) UserInfoCity() string {
	return invoice.userInfoCity
}

// SetUserInfoCity sets the userInfoCity.
func (invoice *Invoice) SetUserInfoCity(userInfoCity string) {
	invoice.userInfoCity = userInfoCity
}

// UserInfoState returns userInfoState.
func (invoice *Invoice) UserInfoState() *uint {
	return invoice.userInfoState
}

// SetUserInfoState sets the userInfoState.
func (invoice *Invoice) SetUserInfoState(userInfoState *uint) {
	invoice.userInfoState = userInfoState
}

// UserInfoCountry returns userInfoCountry.
func (invoice *Invoice) UserInfoCountry() *uint16 {
	return invoice.userInfoCountry
}

// SetUserInfoCountry sets the userInfoCountry.
func (invoice *Invoice) SetUserInfoCountry(userInfoCountry *uint16) {
	invoice.userInfoCountry = userInfoCountry
}

// UserInfoPhoneNumber returns userInfoPhoneNumber.
func (invoice *Invoice) UserInfoPhoneNumber() *string {
	return invoice.userInfoPhoneNumber
}

// SetUserInfoPhoneNumber sets the userInfoPhoneNumber.
func (invoice *Invoice) SetUserInfoPhoneNumber(userInfoPhoneNumber *string) {
	invoice.userInfoPhoneNumber = userInfoPhoneNumber
}

// UserInfoEmail returns userInfoEmail.
func (invoice *Invoice) UserInfoEmail() *string {
	return invoice.userInfoEmail
}

// SetUserInfoEmail sets the userInfoEmail.
func (invoice *Invoice) SetUserInfoEmail(userInfoEmail *string) {
	invoice.userInfoEmail = userInfoEmail
}

// Comments returns comments.
func (invoice *Invoice) Comments() *string {
	return invoice.comments
}

// SetComments sets the comments.
func (invoice *Invoice) SetComments(comments *string) {
	invoice.comments = comments
}

// SellingPartyAutograph returns sellingPartyAutograph.
func (invoice *Invoice) SellingPartyAutograph() *string {
	return invoice.sellingPartyAutograph
}

// SetSellingPartyAutograph sets the sellingPartyAutograph.
func (invoice *Invoice) SetSellingPartyAutograph(sellingPartyAutograph *string) {
	invoice.sellingPartyAutograph = sellingPartyAutograph
}

// BuyingPartyAutograph returns buyingPartyAutograph.
func (invoice *Invoice) BuyingPartyAutograph() *string {
	return invoice.buyingPartyAutograph
}

// SetBuyingPartyAutograph sets the buyingPartyAutograph.
func (invoice *Invoice) SetBuyingPartyAutograph(buyingPartyAutograph *string) {
	invoice.buyingPartyAutograph = buyingPartyAutograph
}

func newInvoice() *Invoice {
	return &Invoice{}
}

// New returns a new instance of InvoiceEntity.
func NewInvoiceEntity() InvoiceEntity {
	return newInvoice()
}
