// Code generated by espal-store-synthesizer. DO NOT EDIT.
package subscription

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ SubscriptionEntity = &Subscription{}

type SubscriptionEntity interface {
	database.Model
}

// TableName returns the table name that belongs to the current model.
func (s *Subscription) TableName() string {
	return "Subscription"
}

// ID returns id.
func (s *Subscription) ID() string {
	return s.id
}

// CreatedByID returns createdByID.
func (s *Subscription) CreatedByID() string {
	return s.createdByID
}

// SetCreatedByID sets the createdByID.
func (s *Subscription) SetCreatedByID(createdByID string) {
	s.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (s *Subscription) UpdatedByID() *string {
	return s.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (s *Subscription) SetUpdatedByID(updatedByID *string) {
	s.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (s *Subscription) CreatedAt() time.Time {
	return s.createdAt
}

// SetCreatedAt sets the createdAt.
func (s *Subscription) SetCreatedAt(createdAt time.Time) {
	s.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (s *Subscription) UpdatedAt() *time.Time {
	return s.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (s *Subscription) SetUpdatedAt(updatedAt *time.Time) {
	s.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (s *Subscription) CreatedByFirstName() *string {
	return s.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (s *Subscription) SetCreatedByFirstName(createdByFirstName *string) {
	s.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (s *Subscription) CreatedBySurname() *string {
	return s.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (s *Subscription) SetCreatedBySurname(createdBySurname *string) {
	s.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (s *Subscription) UpdatedByFirstName() *string {
	return s.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (s *Subscription) SetUpdatedByFirstName(updatedByFirstName *string) {
	s.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (s *Subscription) UpdatedBySurname() *string {
	return s.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (s *Subscription) SetUpdatedBySurname(updatedBySurname *string) {
	s.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (s *Subscription) IsUpdated() bool {
	return s.updatedByID != nil
}

func newSubscription() *Subscription {
	return &Subscription{}
}

// New returns a new instance of SubscriptionEntity.
func NewSubscriptionEntity() SubscriptionEntity {
	return newSubscription()
}
