// Code generated by espal-store-synthesizer. DO NOT EDIT.
package shippingwindow_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/shippingwindow"
)

func TestShippingWindowTable(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	if s.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestShippingWindowTableAlias(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	if s.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestShippingWindowIsUpdated(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	s.IsUpdated()
}

func TestShippingWindowID(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	s.ID()
}

func TestShippingWindowCreatedByID(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := "testValue"
	s.SetCreatedByID(testValue)
	if testValue != s.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowUpdatedByID(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := "testValue"
	s.SetUpdatedByID(&testValue)
	if &testValue != s.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowCreatedAt(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := time.Now()
	s.SetCreatedAt(testValue)
	if testValue != s.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowUpdatedAt(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := time.Now()
	s.SetUpdatedAt(&testValue)
	if &testValue != s.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowCreatedByFirstName(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := "testValue"
	s.SetCreatedByFirstName(&testValue)
	if &testValue != s.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowCreatedBySurname(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := "testValue"
	s.SetCreatedBySurname(&testValue)
	if &testValue != s.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowUpdatedByFirstName(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := "testValue"
	s.SetUpdatedByFirstName(&testValue)
	if &testValue != s.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowUpdatedBySurname(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := "testValue"
	s.SetUpdatedBySurname(&testValue)
	if &testValue != s.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowUserGroupID(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := "testValue"
	s.SetUserGroupID(&testValue)
	if &testValue != s.UserGroupID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowStartDate(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := time.Now()
	s.SetStartDate(&testValue)
	if &testValue != s.StartDate() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestShippingWindowEndDate(t *testing.T) {
	s := shippingwindow.NewShippingWindowEntity()
	testValue := time.Now()
	s.SetEndDate(&testValue)
	if &testValue != s.EndDate() {
		t.Fatal("Getter did not return the Set value")
	}
}
