// Code generated by espal-store-synthesizer. DO NOT EDIT.
package media

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ MediaEntity = &Media{}

type MediaEntity interface {
	database.Model
	Active() bool
	SetActive(active bool)
	FilePath() string
	SetFilePath(filePath string)
}

// TableName returns the table name that belongs to the current model.
func (media *Media) TableName() string {
	return "Media"
}

// TableAlias returns the unique resolved table alias for use in queries.
func (media *Media) TableAlias() string {
	return "me"
}

// ID returns id.
func (media *Media) ID() string {
	return media.id
}

// CreatedByID returns createdByID.
func (media *Media) CreatedByID() string {
	return media.createdByID
}

// SetCreatedByID sets the createdByID.
func (media *Media) SetCreatedByID(createdByID string) {
	media.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (media *Media) UpdatedByID() *string {
	return media.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (media *Media) SetUpdatedByID(updatedByID *string) {
	media.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (media *Media) CreatedAt() time.Time {
	return media.createdAt
}

// SetCreatedAt sets the createdAt.
func (media *Media) SetCreatedAt(createdAt time.Time) {
	media.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (media *Media) UpdatedAt() *time.Time {
	return media.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (media *Media) SetUpdatedAt(updatedAt *time.Time) {
	media.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (media *Media) CreatedByFirstName() *string {
	return media.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (media *Media) SetCreatedByFirstName(createdByFirstName *string) {
	media.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (media *Media) CreatedBySurname() *string {
	return media.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (media *Media) SetCreatedBySurname(createdBySurname *string) {
	media.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (media *Media) UpdatedByFirstName() *string {
	return media.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (media *Media) SetUpdatedByFirstName(updatedByFirstName *string) {
	media.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (media *Media) UpdatedBySurname() *string {
	return media.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (media *Media) SetUpdatedBySurname(updatedBySurname *string) {
	media.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (media *Media) IsUpdated() bool {
	return media.updatedByID != nil
}

// Active returns active.
func (media *Media) Active() bool {
	return media.active
}

// SetActive sets the active.
func (media *Media) SetActive(active bool) {
	media.active = active
}

// FilePath returns filePath.
func (media *Media) FilePath() string {
	return media.filePath
}

// SetFilePath sets the filePath.
func (media *Media) SetFilePath(filePath string) {
	media.filePath = filePath
}

func newMedia() *Media {
	return &Media{}
}

// New returns a new instance of MediaEntity.
func NewMediaEntity() MediaEntity {
	return newMedia()
}
