// Code generated by espal-store-synthesizer. DO NOT EDIT.
package media_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/media"
)

func TestMediaTable(t *testing.T) {
	m := media.NewMediaEntity()
	if m.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestMediaTableAlias(t *testing.T) {
	m := media.NewMediaEntity()
	if m.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestMediaIsUpdated(t *testing.T) {
	m := media.NewMediaEntity()
	m.IsUpdated()
}

func TestMediaID(t *testing.T) {
	m := media.NewMediaEntity()
	m.ID()
}

func TestMediaCreatedByID(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := "testValue"
	m.SetCreatedByID(testValue)
	if testValue != m.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaUpdatedByID(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := "testValue"
	m.SetUpdatedByID(&testValue)
	if &testValue != m.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaCreatedAt(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := time.Now()
	m.SetCreatedAt(testValue)
	if testValue != m.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaUpdatedAt(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := time.Now()
	m.SetUpdatedAt(&testValue)
	if &testValue != m.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaCreatedByFirstName(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := "testValue"
	m.SetCreatedByFirstName(&testValue)
	if &testValue != m.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaCreatedBySurname(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := "testValue"
	m.SetCreatedBySurname(&testValue)
	if &testValue != m.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaUpdatedByFirstName(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := "testValue"
	m.SetUpdatedByFirstName(&testValue)
	if &testValue != m.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaUpdatedBySurname(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := "testValue"
	m.SetUpdatedBySurname(&testValue)
	if &testValue != m.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaActive(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := true
	m.SetActive(testValue)
	if testValue != m.Active() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestMediaFilePath(t *testing.T) {
	m := media.NewMediaEntity()
	testValue := "testValue"
	m.SetFilePath(testValue)
	if testValue != m.FilePath() {
		t.Fatal("Getter did not return the Set value")
	}
}
