// Code generated by espal-store-synthesizer. DO NOT EDIT.
package forum_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/forum"
)

func TestPermissionTable(t *testing.T) {
	p := forum.NewPermissionEntity()
	if p.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestPermissionTableAlias(t *testing.T) {
	p := forum.NewPermissionEntity()
	if p.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestPermissionIsUpdated(t *testing.T) {
	p := forum.NewPermissionEntity()
	p.IsUpdated()
}

func TestPermissionID(t *testing.T) {
	p := forum.NewPermissionEntity()
	p.ID()
}

func TestPermissionCreatedByID(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetCreatedByID(testValue)
	if testValue != p.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionUpdatedByID(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetUpdatedByID(&testValue)
	if &testValue != p.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionCreatedAt(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := time.Now()
	p.SetCreatedAt(testValue)
	if testValue != p.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionUpdatedAt(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := time.Now()
	p.SetUpdatedAt(&testValue)
	if &testValue != p.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionCreatedByFirstName(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetCreatedByFirstName(&testValue)
	if &testValue != p.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionCreatedBySurname(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetCreatedBySurname(&testValue)
	if &testValue != p.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionUpdatedByFirstName(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetUpdatedByFirstName(&testValue)
	if &testValue != p.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionUpdatedBySurname(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetUpdatedBySurname(&testValue)
	if &testValue != p.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionForumID(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetForumID(&testValue)
	if &testValue != p.ForumID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionUserID(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := "testValue"
	p.SetUserID(&testValue)
	if &testValue != p.UserID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestPermissionPermission(t *testing.T) {
	p := forum.NewPermissionEntity()
	testValue := uint8(255)
	p.SetPermission(testValue)
	if testValue != p.Permission() {
		t.Fatal("Getter did not return the Set value")
	}
}
