CREATE TABLE "User" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID,
	"updatedByID" UUID,
	"defaultDeliveryAddressID" UUID,
	"defaultInvoiceaddressID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"active" BOOL NOT NULL DEFAULT false,
	"country" INT2,
	"language" INT2 NOT NULL,
	"firstName" STRING(50),
	"surname" STRING(50),
	"dateOfBirth" DATE,
	"email" STRING(255) NOT NULL,
	"password" STRING(72) NOT NULL,
	"avatar" STRING(255),
	"priority" INT NOT NULL DEFAULT 0,
	"activationHash" STRING(72),
	"activatedAt" TIMESTAMP,
	"passwordResetHash" STRING(72),
	"passwordResetLastSendAt" TIMESTAMP,
	"passwordLastResetAt" TIMESTAMP,
	"passwordResetCount" INT2,
	"biography" STRING,
	"comments" STRING,
	"currencies" STRING NOT NULL DEFAULT '',
	UNIQUE INDEX "User_uidx_email_key" ("email"),
	UNIQUE INDEX "User_uidx_activationHash" ("activationHash"),
	INDEX "User_idx_createdByID" ("createdByID"),
	INDEX "User_idx_updatedByID" ("updatedByID"),
	INDEX "User_idx_email_active" ("email", "active"),
	CONSTRAINT "User_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	FAMILY "Primary" ("id", "createdByID", "createdAt"),
	FAMILY "Secondary" ("updatedByID", "updatedAt"),
	FAMILY "Tertiary" ("defaultDeliveryAddressID", "defaultInvoiceaddressID",
		"active", "country", "language", "firstName", "surname", "dateOfBirth",
		"email", "password", "avatar", "priority", "activationHash", "activatedAt",
		"biography", "comments", "currencies"),
	FAMILY "PasswordReset" ("passwordResetHash", "passwordResetLastSendAt",
        "passwordLastResetAt", "passwordResetCount")
);
