CREATE TABLE "Setting" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"userID" UUID,
	"domainID" UUID,
	"siteID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
    "key" STRING(255),
    "value" STRING,
    UNIQUE INDEX "Setting_uidx_userID" ("userID"),
    UNIQUE INDEX "Setting_uidx_domainID" ("domainID"),
    UNIQUE INDEX "Setting_uidx_siteID" ("siteID"),
	INDEX "Setting_idx_createdByID" ("createdByID"),
	INDEX "Setting_idx_updatedByID" ("updatedByID"),
	CONSTRAINT "Setting_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "Setting_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "Setting_userID" FOREIGN KEY ("userID") REFERENCES "User" ("id"),
	CONSTRAINT "Setting_domainID" FOREIGN KEY ("domainID") REFERENCES "Domain" ("id"),
	CONSTRAINT "Setting_siteID" FOREIGN KEY ("siteID") REFERENCES "Site" ("id"),
    FAMILY "Primary" ("id", "createdByID", "userID", "domainID", "siteID", "createdAt", "key"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "value")
);
