CREATE TABLE "BundledProduct" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"taxGroupID" UUID NOT NULL,
	"nameRepresentationID" UUID,
	"descriptionRepresentationID" UUID,
	"imageRepresentationID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"active" BOOL NOT NULL DEFAULT false,
	"sorting" INT NOT NULL DEFAULT 0,
    "key" STRING(255),
    "variantsCanBeSoldSeperately" BOOL NOT NULL DEFAULT true,
    UNIQUE INDEX "BundledProduct_uidx_key" ("key"),
	INDEX "BundledProduct_idx_createdByID" ("createdByID"),
	INDEX "BundledProduct_idx_updatedByID" ("updatedByID"),
	INDEX "BundledProduct_idx_taxGroupID" ("taxGroupID"),
	INDEX "BundledProduct_idx_nameRepresentationID" ("nameRepresentationID"),
	INDEX "BundledProduct_idx_descriptionRepresentationID" ("descriptionRepresentationID"),
	INDEX "BundledProduct_idx_imageRepresentationID" ("imageRepresentationID"),
	CONSTRAINT "BundledProduct_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "BundledProduct_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "BundledProduct_taxGroupID" FOREIGN KEY ("taxGroupID") REFERENCES "TaxGroup" ("id"),
	CONSTRAINT "BundledProduct_nameRepresentationID" FOREIGN KEY ("nameRepresentationID") REFERENCES "Property" ("id"),
	CONSTRAINT "BundledProduct_descriptionRepresentationID" FOREIGN KEY ("descriptionRepresentationID") REFERENCES "Property" ("id"),
	CONSTRAINT "BundledProduct_imageRepresentationID" FOREIGN KEY ("imageRepresentationID") REFERENCES "Property" ("id"),
    FAMILY "Primary" ("id", "createdByID", "createdAt", "taxGroupID"),
	FAMILY "Secondary" ("updatedByID", "updatedAt"),
	FAMILY "Tertiary" ("active", "sorting", "key", "variantsCanBeSoldSeperately"),
	FAMILY "Properties" ("nameRepresentationID", "descriptionRepresentationID", "imageRepresentationID")
);
