CREATE TABLE "BundledProductVariant" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"bundledProductID" UUID NOT NULL,
	"productVariantID" UUID NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
    "quantity" INT,
    UNIQUE INDEX "BundledProductVariant_uidx_bundledProductID_productVariantID" ("bundledProductID", "productVariantID"),
	INDEX "BundledProductVariant_idx_createdByID" ("createdByID"),
	INDEX "BundledProductVariant_idx_updatedByID" ("updatedByID"),
	INDEX "BundledProductVariant_idx_productVariantID" ("productVariantID"),
	CONSTRAINT "BundledProductVariant_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "BundledProductVariant_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "BundledProductVariant_bundledProductID" FOREIGN KEY ("bundledProductID") REFERENCES "BundledProduct" ("id"),
	CONSTRAINT "BundledProductVariant_productVariantID" FOREIGN KEY ("productVariantID") REFERENCES "ProductVariant" ("id"),
    FAMILY "Primary" ("id", "createdByID", "createdAt", "bundledProductID", "productVariantID"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "quantity")
);
