CREATE TABLE "BundledProductReview" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"bundledProductID" UUID NOT NULL,
	"reviewedByID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"reviewedOnDate" TIMESTAMP,
    "reviewNotes" STRING,
    "approved" BOOL,
    "rating" DECIMAL(9,6),
    "title" STRING(255),
    "description" STRING,
	INDEX "BundledProductReview_idx_createdByID" ("createdByID"),
	INDEX "BundledProductReview_idx_updatedByID" ("updatedByID"),
	INDEX "BundledProductReview_idx_bundledProductID" ("bundledProductID"),
	INDEX "BundledProductReview_idx_reviewedByID" ("reviewedByID"),
	CONSTRAINT "BundledProductReview_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "BundledProductReview_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "BundledProductReview_bundledProductID" FOREIGN KEY ("bundledProductID") REFERENCES "BundledProduct" ("id"),
	CONSTRAINT "BundledProductReview_reviewedByID" FOREIGN KEY ("reviewedByID") REFERENCES "User" ("id"),
    FAMILY "Primary" ("id", "createdByID", "createdAt", "bundledProductID", "reviewedByID", "reviewedOnDate", "rating", "title", "description"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "reviewNotes", "approved")
);
