CREATE TABLE "Supplier" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"active" BOOL NOT NULL DEFAULT false,
	"key" STRING(255),
	"name" STRING(255) NOT NULL,
	"contactFirstName" STRING(50),
	"contactSurname" STRING(50),
	"street" STRING(72),
	"streetLine2" STRING(72),
	"number" STRING(12),
	"numberAddition" STRING(12),
	"zipCode" STRING(12),
	"city" STRING(255),
	"state" STRING,
	"country" INT2,
	"phoneNumber" STRING(32),
	"email" STRING(255),
	"comments" STRING,
    UNIQUE INDEX "Supplier_uidx_key" ("key"),
	INDEX "Supplier_idx_createdByID" ("createdByID"),
	INDEX "Supplier_idx_updatedByID" ("updatedByID"),
	CONSTRAINT "Supplier_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "Supplier_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
    FAMILY "Primary" ("id", "createdByID", "createdAt"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "active", "key", "name", "contactFirstName",
        "contactSurname", "street", "streetLine2", "number", "numberAddition", "zipCode", "city",
        "state", "country", "phoneNumber", "email", "comments")
);
