CREATE TABLE "SaleOrderLine" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"saleOrderID" UUID NOT NULL,
	"productVariantID" UUID,
	"bundledProductID" UUID,
	"deliveryMethodID" UUID NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"sorting" INT NOT NULL DEFAULT 0,
	"quantity" INT NOT NULL,
	"price" DECIMAL(9,2) NOT NULL,
	"vatPercentage" DECIMAL(9,6) NOT NULL,
	"comments" STRING,
	INDEX "SaleOrderLine_idx_createdByID" ("createdByID"),
	INDEX "SaleOrderLine_idx_updatedByID" ("updatedByID"),
	INDEX "SaleOrderLine_idx_saleOrderID" ("saleOrderID"),
	INDEX "SaleOrderLine_idx_productVariantID" ("productVariantID"),
	INDEX "SaleOrderLine_idx_bundledProductID" ("bundledProductID"),
	INDEX "SaleOrderLine_idx_deliveryMethodID" ("deliveryMethodID"),
	CONSTRAINT "SaleOrderLine_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "SaleOrderLine_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "SaleOrderLine_saleOrderID" FOREIGN KEY ("saleOrderID") REFERENCES "SaleOrder" ("id"),
	CONSTRAINT "SaleOrderLine_productVariantID" FOREIGN KEY ("productVariantID") REFERENCES "ProductVariant" ("id"),
	CONSTRAINT "SaleOrderLine_bundledProductID" FOREIGN KEY ("bundledProductID") REFERENCES "BundledProduct" ("id"),
	FAMILY "Primary" ("id", "createdByID", "createdAt", "saleOrderID", "productVariantID", "bundledProductID", "deliveryMethodID"),
	FAMILY "Secondary" ("updatedByID", "updatedAt"),
	FAMILY "Tertiary" ("sorting", "comments"),
	FAMILY "QuantityPrice" ("quantity", "price", "vatPercentage")
);
