CREATE TABLE "PurchaseOrderReceivingLine" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"purchaseOrderReceivingID" UUID NOT NULL,
	"purchaseOrderLineID" UUID,
	"productVariantID" UUID,
	"bundledProductID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"quantity" INT NOT NULL,
	"comments" STRING,
	INDEX "PurchaseOrderReceivingLine_idx_createdByID" ("createdByID"),
	INDEX "PurchaseOrderReceivingLine_idx_updatedByID" ("updatedByID"),
	INDEX "PurchaseOrderReceivingLine_idx_purchaseOrderReceivingID" ("purchaseOrderReceivingID"),
	INDEX "PurchaseOrderReceivingLine_idx_purchaseOrderLineID" ("purchaseOrderLineID"),
	INDEX "PurchaseOrderReceivingLine_idx_productVariantID" ("productVariantID"),
	INDEX "PurchaseOrderReceivingLine_idx_bundledProductID" ("bundledProductID"),
	CONSTRAINT "PurchaseOrderReceivingLine_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "PurchaseOrderReceivingLine_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "PurchaseOrderReceivingLine_purchaseOrderReceivingID" FOREIGN KEY ("purchaseOrderReceivingID") REFERENCES "PurchaseOrderReceiving" ("id"),
	CONSTRAINT "PurchaseOrderReceivingLine_purchaseOrderLineID" FOREIGN KEY ("purchaseOrderLineID") REFERENCES "PurchaseOrderLine" ("id"),
	CONSTRAINT "PurchaseOrderReceivingLine_productVariantID" FOREIGN KEY ("productVariantID") REFERENCES "ProductVariant" ("id"),
	CONSTRAINT "PurchaseOrderReceivingLine_bundledProductID" FOREIGN KEY ("bundledProductID") REFERENCES "BundledProduct" ("id"),
	FAMILY "Primary" ("id", "createdByID", "purchaseOrderReceivingID", "purchaseOrderLineID", "productVariantID", "bundledProductID", "createdAt"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "quantity", "comments")
);
