CREATE TABLE "ReturnOrder" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"domainID" UUID NOT NULL,
	"userID" UUID NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"comments" STRING,
	INDEX "ReturnOrder_idx_createdByID" ("createdByID"),
	INDEX "ReturnOrder_idx_updatedByID" ("updatedByID"),
	INDEX "ReturnOrder_idx_domainID" ("domainID"),
	INDEX "ReturnOrder_idx_userID" ("userID"),
	CONSTRAINT "ReturnOrder_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "ReturnOrder_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "ReturnOrder_domainID" FOREIGN KEY ("domainID") REFERENCES "Domain" ("id"),
	CONSTRAINT "ReturnOrder_userID" FOREIGN KEY ("userID") REFERENCES "User" ("id"),
	FAMILY "Primary" ("id", "createdByID", "domainID", "userID", "createdAt"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "comments")
);
