CREATE TABLE "Slug" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"domainID" UUID NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"language" INT2 NOT NULL,
	"path" STRING(255) NOT NULL,
	"rerouteTo" STRING(255) NOT NULL,
	"invalidWithStatus" INT2,
	"invalidMessage" STRING(255),
	"redirectToRawPath" STRING(255),
	"redirectStatusCode" INT2,
	UNIQUE INDEX "Slug_uidx_domainID_language_path" ("domainID", "language", "path"),
	INDEX "Slug_idx_createdByID" ("createdByID"),
	INDEX "Slug_idx_updatedByID" ("updatedByID"),
	CONSTRAINT "Slug_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "Slug_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "Slug_domainID" FOREIGN KEY ("domainID") REFERENCES "Domain" ("id"),
	FAMILY "Primary" ("id", "createdByID", "domainID", "createdAt", "language", "path"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "rerouteTo", "invalidWithStatus",
		"invalidMessage", "redirectToRawPath", "redirectStatusCode")
);
