CREATE TABLE "ForumPost" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"forumID" UUID NOT NULL,
	"responseToID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"sticky" BOOL NOT NULL DEFAULT false,
	"title" STRING(255),
	"message" STRING NOT NULL,
	"timesEdited" INT,
	INDEX "ForumPost_idx_createdByID" ("createdByID"),
	INDEX "ForumPost_idx_updatedByID" ("updatedByID"),
	INDEX "ForumPost_idx_forumID_responseToID_sticky_updatedAt_createdAt" ("forumID", "responseToID", "sticky", "updatedAt", "createdAt"),
	INDEX "ForumPost_idx_responseToID" ("responseToID"),
	CONSTRAINT "ForumPost_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "ForumPost_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "ForumPost_forumID" FOREIGN KEY ("forumID") REFERENCES "Forum" ("id"),
	CONSTRAINT "ForumPost_responseToID" FOREIGN KEY ("responseToID") REFERENCES "Forum" ("id"),
	FAMILY "Primary" ("id", "createdByID", "forumID", "responseToID", "createdAt"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "sticky", "title", "message", "timesEdited")
);
