CREATE TABLE "Office" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"active" BOOL NOT NULL DEFAULT false,
	"sorting" INT NOT NULL DEFAULT 0,
	"primaryContactPerson" STRING(72),
	"street" STRING(72) NOT NULL,
	"streetLine2" STRING(72),
	"number" STRING(12) NOT NULL,
	"numberAddition" STRING(12),
	"zipCode" STRING(12) NOT NULL,
	"city" STRING(255) NOT NULL,
	"state" STRING,
	"country" INT2,
	"phoneNumber" STRING(32),
	"email" STRING(255),
	INDEX "Office_idx_createdByID" ("createdByID"),
	INDEX "Office_idx_updatedByID" ("updatedByID"),
	CONSTRAINT "Office_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "Office_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	FAMILY "Primary" ("id", "createdByID", "createdAt"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "active", "sorting", "primaryContactPerson",
		"street", "streetLine2", "number", "numberAddition", "zipCode", "city", "state",
		"country", "phoneNumber", "email")
);
