CREATE TABLE "Price" (
	"id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"createdByID" UUID NOT NULL,
	"updatedByID" UUID,
	"bundledProductID" UUID,
	"productModelID" UUID,
	"productVariantID" UUID,
	"domainID" UUID NOT NULL,
	"priceGroupID" UUID NOT NULL,
	"taxGroupID" UUID NOT NULL,
	"currency" INT2 NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP,
	"price" DECIMAL(9,2) NOT NULL,
	INDEX "Price_idx_createdByID" ("createdByID"),
	INDEX "Price_idx_updatedByID" ("updatedByID"),
	INDEX "Price_idx_bundledProductID" ("bundledProductID"),
	INDEX "Price_idx_productModelID" ("productModelID"),
	INDEX "Price_idx_productVariantID" ("productVariantID"),
	INDEX "Price_idx_domainID" ("domainID"),
	INDEX "Price_idx_priceGroupID" ("priceGroupID"),
	INDEX "Price_idx_taxGroupID" ("taxGroupID"),
	INDEX "Price_idx_currency" ("currency"),
	INDEX "Price_idx_price" ("price"),
	CONSTRAINT "Price_createdByID" FOREIGN KEY ("createdByID") REFERENCES "User" ("id"),
	CONSTRAINT "Price_updatedByID" FOREIGN KEY ("updatedByID") REFERENCES "User" ("id"),
	CONSTRAINT "Price_bundledProductID" FOREIGN KEY ("bundledProductID") REFERENCES "BundledProduct" ("id"),
	CONSTRAINT "Price_productModelID" FOREIGN KEY ("productModelID") REFERENCES "ProductModel" ("id"),
	CONSTRAINT "Price_productVariantID" FOREIGN KEY ("productVariantID") REFERENCES "ProductVariant" ("id"),
	CONSTRAINT "Price_domainID" FOREIGN KEY ("domainID") REFERENCES "Domain" ("id"),
	CONSTRAINT "Price_priceGroupID" FOREIGN KEY ("priceGroupID") REFERENCES "PriceGroup" ("id"),
	CONSTRAINT "Price_taxGroupID" FOREIGN KEY ("taxGroupID") REFERENCES "TaxGroup" ("id"),
	FAMILY "Primary" ("id", "createdByID", "bundledProductID", "productModelID", "productVariantID",
		"domainID", "priceGroupID", "taxGroupID", "createdAt"),
	FAMILY "Secondary" ("updatedByID", "updatedAt", "currency", "price")
);
