// Code generated by espal-store-synthesizer. DO NOT EDIT.
package product

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ BundledEntity = &Bundled{}

type BundledEntity interface {
	database.Model
	Active() bool
	SetActive(active bool)
	Sorting() uint
	SetSorting(sorting uint)
	Key() *string
	SetKey(key *string)
	VariantsCanBeSoldSeperately() bool
	SetVariantsCanBeSoldSeperately(variantsCanBeSoldSeperately bool)
	TaxGroupID() string
	SetTaxGroupID(taxGroupID string)
	NameRepresentationID() *string
	SetNameRepresentationID(nameRepresentationID *string)
	DescriptionRepresentationID() *string
	SetDescriptionRepresentationID(descriptionRepresentationID *string)
	ImageRepresentationID() *string
	SetImageRepresentationID(imageRepresentationID *string)
}

// ID returns id.
func (b *Bundled) ID() string {
	return b.id
}

// CreatedByID returns createdByID.
func (b *Bundled) CreatedByID() string {
	return b.createdByID
}

// SetCreatedByID sets the createdByID.
func (b *Bundled) SetCreatedByID(createdByID string) {
	b.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (b *Bundled) UpdatedByID() *string {
	return b.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (b *Bundled) SetUpdatedByID(updatedByID *string) {
	b.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (b *Bundled) CreatedAt() time.Time {
	return b.createdAt
}

// SetCreatedAt sets the createdAt.
func (b *Bundled) SetCreatedAt(createdAt time.Time) {
	b.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (b *Bundled) UpdatedAt() *time.Time {
	return b.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (b *Bundled) SetUpdatedAt(updatedAt *time.Time) {
	b.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (b *Bundled) CreatedByFirstName() *string {
	return b.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (b *Bundled) SetCreatedByFirstName(createdByFirstName *string) {
	b.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (b *Bundled) CreatedBySurname() *string {
	return b.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (b *Bundled) SetCreatedBySurname(createdBySurname *string) {
	b.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (b *Bundled) UpdatedByFirstName() *string {
	return b.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (b *Bundled) SetUpdatedByFirstName(updatedByFirstName *string) {
	b.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (b *Bundled) UpdatedBySurname() *string {
	return b.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (b *Bundled) SetUpdatedBySurname(updatedBySurname *string) {
	b.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (b *Bundled) IsUpdated() bool {
	return b.updatedByID != nil
}

// Active returns active.
func (b *Bundled) Active() bool {
	return b.active
}

// SetActive sets the active.
func (b *Bundled) SetActive(active bool) {
	b.active = active
}

// Sorting returns sorting.
func (b *Bundled) Sorting() uint {
	return b.sorting
}

// SetSorting sets the sorting.
func (b *Bundled) SetSorting(sorting uint) {
	b.sorting = sorting
}

// Key returns key.
func (b *Bundled) Key() *string {
	return b.key
}

// SetKey sets the key.
func (b *Bundled) SetKey(key *string) {
	b.key = key
}

// VariantsCanBeSoldSeperately returns variantsCanBeSoldSeperately.
func (b *Bundled) VariantsCanBeSoldSeperately() bool {
	return b.variantsCanBeSoldSeperately
}

// SetVariantsCanBeSoldSeperately sets the variantsCanBeSoldSeperately.
func (b *Bundled) SetVariantsCanBeSoldSeperately(variantsCanBeSoldSeperately bool) {
	b.variantsCanBeSoldSeperately = variantsCanBeSoldSeperately
}

// TaxGroupID returns taxGroupID.
func (b *Bundled) TaxGroupID() string {
	return b.taxGroupID
}

// SetTaxGroupID sets the taxGroupID.
func (b *Bundled) SetTaxGroupID(taxGroupID string) {
	b.taxGroupID = taxGroupID
}

// NameRepresentationID returns nameRepresentationID.
func (b *Bundled) NameRepresentationID() *string {
	return b.nameRepresentationID
}

// SetNameRepresentationID sets the nameRepresentationID.
func (b *Bundled) SetNameRepresentationID(nameRepresentationID *string) {
	b.nameRepresentationID = nameRepresentationID
}

// DescriptionRepresentationID returns descriptionRepresentationID.
func (b *Bundled) DescriptionRepresentationID() *string {
	return b.descriptionRepresentationID
}

// SetDescriptionRepresentationID sets the descriptionRepresentationID.
func (b *Bundled) SetDescriptionRepresentationID(descriptionRepresentationID *string) {
	b.descriptionRepresentationID = descriptionRepresentationID
}

// ImageRepresentationID returns imageRepresentationID.
func (b *Bundled) ImageRepresentationID() *string {
	return b.imageRepresentationID
}

// SetImageRepresentationID sets the imageRepresentationID.
func (b *Bundled) SetImageRepresentationID(imageRepresentationID *string) {
	b.imageRepresentationID = imageRepresentationID
}

func newBundled() *Bundled {
	return &Bundled{}
}

// New returns a new instance of BundledEntity.
func NewBundledEntity() BundledEntity {
	return newBundled()
}
