// Code generated by espal-store-synthesizer. DO NOT EDIT.
package product

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ BundledVariantEntity = &BundledVariant{}

type BundledVariantEntity interface {
	database.Model
	BundledID() string
	SetBundledID(bundledID string)
	VariantID() string
	SetVariantID(variantID string)
	Quantity() uint
	SetQuantity(quantity uint)
}

// ID returns id.
func (b *BundledVariant) ID() string {
	return b.id
}

// CreatedByID returns createdByID.
func (b *BundledVariant) CreatedByID() string {
	return b.createdByID
}

// SetCreatedByID sets the createdByID.
func (b *BundledVariant) SetCreatedByID(createdByID string) {
	b.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (b *BundledVariant) UpdatedByID() *string {
	return b.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (b *BundledVariant) SetUpdatedByID(updatedByID *string) {
	b.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (b *BundledVariant) CreatedAt() time.Time {
	return b.createdAt
}

// SetCreatedAt sets the createdAt.
func (b *BundledVariant) SetCreatedAt(createdAt time.Time) {
	b.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (b *BundledVariant) UpdatedAt() *time.Time {
	return b.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (b *BundledVariant) SetUpdatedAt(updatedAt *time.Time) {
	b.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (b *BundledVariant) CreatedByFirstName() *string {
	return b.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (b *BundledVariant) SetCreatedByFirstName(createdByFirstName *string) {
	b.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (b *BundledVariant) CreatedBySurname() *string {
	return b.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (b *BundledVariant) SetCreatedBySurname(createdBySurname *string) {
	b.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (b *BundledVariant) UpdatedByFirstName() *string {
	return b.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (b *BundledVariant) SetUpdatedByFirstName(updatedByFirstName *string) {
	b.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (b *BundledVariant) UpdatedBySurname() *string {
	return b.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (b *BundledVariant) SetUpdatedBySurname(updatedBySurname *string) {
	b.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (b *BundledVariant) IsUpdated() bool {
	return b.updatedByID != nil
}

// BundledID returns bundledID.
func (b *BundledVariant) BundledID() string {
	return b.bundledID
}

// SetBundledID sets the bundledID.
func (b *BundledVariant) SetBundledID(bundledID string) {
	b.bundledID = bundledID
}

// VariantID returns variantID.
func (b *BundledVariant) VariantID() string {
	return b.variantID
}

// SetVariantID sets the variantID.
func (b *BundledVariant) SetVariantID(variantID string) {
	b.variantID = variantID
}

// Quantity returns quantity.
func (b *BundledVariant) Quantity() uint {
	return b.quantity
}

// SetQuantity sets the quantity.
func (b *BundledVariant) SetQuantity(quantity uint) {
	b.quantity = quantity
}

func newBundledVariant() *BundledVariant {
	return &BundledVariant{}
}

// New returns a new instance of BundledVariantEntity.
func NewBundledVariantEntity() BundledVariantEntity {
	return newBundledVariant()
}
