// Code generated by espal-store-synthesizer. DO NOT EDIT.
package product

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ BundledReviewEntity = &BundledReview{}

type BundledReviewEntity interface {
	database.Model
	ReviewedByID() *string
	SetReviewedByID(reviewedByID *string)
	ReviewedOnDate() *time.Time
	SetReviewedOnDate(reviewedOnDate *time.Time)
	ReviewNotes() *string
	SetReviewNotes(reviewNotes *string)
	Approved() *bool
	SetApproved(approved *bool)
	Rating() float32
	SetRating(rating float32)
	Title() string
	SetTitle(title string)
	Description() string
	SetDescription(description string)
	BundledID() string
	SetBundledID(bundledID string)
}

// ID returns id.
func (bundledReview *BundledReview) ID() string {
	return bundledReview.id
}

// CreatedByID returns createdByID.
func (bundledReview *BundledReview) CreatedByID() string {
	return bundledReview.createdByID
}

// SetCreatedByID sets the createdByID.
func (bundledReview *BundledReview) SetCreatedByID(createdByID string) {
	bundledReview.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (bundledReview *BundledReview) UpdatedByID() *string {
	return bundledReview.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (bundledReview *BundledReview) SetUpdatedByID(updatedByID *string) {
	bundledReview.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (bundledReview *BundledReview) CreatedAt() time.Time {
	return bundledReview.createdAt
}

// SetCreatedAt sets the createdAt.
func (bundledReview *BundledReview) SetCreatedAt(createdAt time.Time) {
	bundledReview.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (bundledReview *BundledReview) UpdatedAt() *time.Time {
	return bundledReview.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (bundledReview *BundledReview) SetUpdatedAt(updatedAt *time.Time) {
	bundledReview.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (bundledReview *BundledReview) CreatedByFirstName() *string {
	return bundledReview.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (bundledReview *BundledReview) SetCreatedByFirstName(createdByFirstName *string) {
	bundledReview.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (bundledReview *BundledReview) CreatedBySurname() *string {
	return bundledReview.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (bundledReview *BundledReview) SetCreatedBySurname(createdBySurname *string) {
	bundledReview.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (bundledReview *BundledReview) UpdatedByFirstName() *string {
	return bundledReview.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (bundledReview *BundledReview) SetUpdatedByFirstName(updatedByFirstName *string) {
	bundledReview.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (bundledReview *BundledReview) UpdatedBySurname() *string {
	return bundledReview.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (bundledReview *BundledReview) SetUpdatedBySurname(updatedBySurname *string) {
	bundledReview.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (bundledReview *BundledReview) IsUpdated() bool {
	return bundledReview.updatedByID != nil
}

// ReviewedByID returns reviewedByID.
func (bundledReview *BundledReview) ReviewedByID() *string {
	return bundledReview.reviewedByID
}

// SetReviewedByID sets the reviewedByID.
func (bundledReview *BundledReview) SetReviewedByID(reviewedByID *string) {
	bundledReview.reviewedByID = reviewedByID
}

// ReviewedOnDate returns reviewedOnDate.
func (bundledReview *BundledReview) ReviewedOnDate() *time.Time {
	return bundledReview.reviewedOnDate
}

// SetReviewedOnDate sets the reviewedOnDate.
func (bundledReview *BundledReview) SetReviewedOnDate(reviewedOnDate *time.Time) {
	bundledReview.reviewedOnDate = reviewedOnDate
}

// ReviewNotes returns reviewNotes.
func (bundledReview *BundledReview) ReviewNotes() *string {
	return bundledReview.reviewNotes
}

// SetReviewNotes sets the reviewNotes.
func (bundledReview *BundledReview) SetReviewNotes(reviewNotes *string) {
	bundledReview.reviewNotes = reviewNotes
}

// Approved returns approved.
func (bundledReview *BundledReview) Approved() *bool {
	return bundledReview.approved
}

// SetApproved sets the approved.
func (bundledReview *BundledReview) SetApproved(approved *bool) {
	bundledReview.approved = approved
}

// Rating returns rating.
func (bundledReview *BundledReview) Rating() float32 {
	return bundledReview.rating
}

// SetRating sets the rating.
func (bundledReview *BundledReview) SetRating(rating float32) {
	bundledReview.rating = rating
}

// Title returns title.
func (bundledReview *BundledReview) Title() string {
	return bundledReview.title
}

// SetTitle sets the title.
func (bundledReview *BundledReview) SetTitle(title string) {
	bundledReview.title = title
}

// Description returns description.
func (bundledReview *BundledReview) Description() string {
	return bundledReview.description
}

// SetDescription sets the description.
func (bundledReview *BundledReview) SetDescription(description string) {
	bundledReview.description = description
}

// BundledID returns bundledID.
func (bundledReview *BundledReview) BundledID() string {
	return bundledReview.bundledID
}

// SetBundledID sets the bundledID.
func (bundledReview *BundledReview) SetBundledID(bundledID string) {
	bundledReview.bundledID = bundledID
}

func newBundledReview() *BundledReview {
	return &BundledReview{}
}

// New returns a new instance of BundledReviewEntity.
func NewBundledReviewEntity() BundledReviewEntity {
	return newBundledReview()
}
