// Code generated by espal-store-synthesizer. DO NOT EDIT.
package product_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/product"
)

func TestModelPropertyTable(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	if modelProperty.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestModelPropertyTableAlias(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	if modelProperty.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestModelPropertyIsUpdated(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	modelProperty.IsUpdated()
}

func TestModelPropertyID(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	modelProperty.ID()
}

func TestModelPropertyCreatedByID(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetCreatedByID(testValue)
	if testValue != modelProperty.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyUpdatedByID(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetUpdatedByID(&testValue)
	if &testValue != modelProperty.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyCreatedAt(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := time.Now()
	modelProperty.SetCreatedAt(testValue)
	if testValue != modelProperty.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyUpdatedAt(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := time.Now()
	modelProperty.SetUpdatedAt(&testValue)
	if &testValue != modelProperty.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyCreatedByFirstName(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetCreatedByFirstName(&testValue)
	if &testValue != modelProperty.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyCreatedBySurname(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetCreatedBySurname(&testValue)
	if &testValue != modelProperty.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyUpdatedByFirstName(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetUpdatedByFirstName(&testValue)
	if &testValue != modelProperty.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyUpdatedBySurname(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetUpdatedBySurname(&testValue)
	if &testValue != modelProperty.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyProductModelID(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetProductModelID(testValue)
	if testValue != modelProperty.ProductModelID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyPropertyID(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetPropertyID(testValue)
	if testValue != modelProperty.PropertyID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertySorting(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := uint(1e9)
	modelProperty.SetSorting(testValue)
	if testValue != modelProperty.Sorting() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestModelPropertyKey(t *testing.T) {
	modelProperty := product.NewModelPropertyEntity()
	testValue := "testValue"
	modelProperty.SetKey(&testValue)
	if &testValue != modelProperty.Key() {
		t.Fatal("Getter did not return the Set value")
	}
}
