// Code generated by espal-store-synthesizer. DO NOT EDIT.
package product_test

import (
	"github.com/espal-digital-development/espal-core/stores/product"
	"testing"
)

func TestPropertyRevisionHistoryTable(t *testing.T) {
	propertyRevisionHistory := product.NewPropertyRevisionHistoryEntity()
	if propertyRevisionHistory.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestPropertyRevisionHistoryTableAlias(t *testing.T) {
	propertyRevisionHistory := product.NewPropertyRevisionHistoryEntity()
	if propertyRevisionHistory.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestPropertyRevisionHistoryIsUpdated(t *testing.T) {
	propertyRevisionHistory := product.NewPropertyRevisionHistoryEntity()
	propertyRevisionHistory.IsUpdated()
}

func TestPropertyRevisionHistoryID(t *testing.T) {
	propertyRevisionHistory := product.NewPropertyRevisionHistoryEntity()
	propertyRevisionHistory.ID()
}
