// Code generated by espal-store-synthesizer. DO NOT EDIT.
package product

import (
	"time"

	"github.com/espal-digital-development/espal-core/database"
)

var _ VariantReviewEntity = &VariantReview{}

type VariantReviewEntity interface {
	database.Model
	ReviewedByID() *string
	SetReviewedByID(reviewedByID *string)
	ReviewedOnDate() *time.Time
	SetReviewedOnDate(reviewedOnDate *time.Time)
	ReviewNotes() *string
	SetReviewNotes(reviewNotes *string)
	Approved() *bool
	SetApproved(approved *bool)
	Rating() float32
	SetRating(rating float32)
	Title() string
	SetTitle(title string)
	Description() string
	SetDescription(description string)
	VariantID() string
	SetVariantID(variantID string)
}

// ID returns id.
func (variantReview *VariantReview) ID() string {
	return variantReview.id
}

// CreatedByID returns createdByID.
func (variantReview *VariantReview) CreatedByID() string {
	return variantReview.createdByID
}

// SetCreatedByID sets the createdByID.
func (variantReview *VariantReview) SetCreatedByID(createdByID string) {
	variantReview.createdByID = createdByID
}

// UpdatedByID returns updatedByID.
func (variantReview *VariantReview) UpdatedByID() *string {
	return variantReview.updatedByID
}

// SetUpdatedByID sets the updatedByID.
func (variantReview *VariantReview) SetUpdatedByID(updatedByID *string) {
	variantReview.updatedByID = updatedByID
}

// CreatedAt returns createdAt.
func (variantReview *VariantReview) CreatedAt() time.Time {
	return variantReview.createdAt
}

// SetCreatedAt sets the createdAt.
func (variantReview *VariantReview) SetCreatedAt(createdAt time.Time) {
	variantReview.createdAt = createdAt
}

// UpdatedAt returns updatedAt.
func (variantReview *VariantReview) UpdatedAt() *time.Time {
	return variantReview.updatedAt
}

// SetUpdatedAt sets the updatedAt.
func (variantReview *VariantReview) SetUpdatedAt(updatedAt *time.Time) {
	variantReview.updatedAt = updatedAt
}

// CreatedByFirstName returns createdByFirstName.
func (variantReview *VariantReview) CreatedByFirstName() *string {
	return variantReview.createdByFirstName
}

// SetCreatedByFirstName sets the createdByFirstName.
func (variantReview *VariantReview) SetCreatedByFirstName(createdByFirstName *string) {
	variantReview.createdByFirstName = createdByFirstName
}

// CreatedBySurname returns createdBySurname.
func (variantReview *VariantReview) CreatedBySurname() *string {
	return variantReview.createdBySurname
}

// SetCreatedBySurname sets the createdBySurname.
func (variantReview *VariantReview) SetCreatedBySurname(createdBySurname *string) {
	variantReview.createdBySurname = createdBySurname
}

// UpdatedByFirstName returns updatedByFirstName.
func (variantReview *VariantReview) UpdatedByFirstName() *string {
	return variantReview.updatedByFirstName
}

// SetUpdatedByFirstName sets the updatedByFirstName.
func (variantReview *VariantReview) SetUpdatedByFirstName(updatedByFirstName *string) {
	variantReview.updatedByFirstName = updatedByFirstName
}

// UpdatedBySurname returns updatedBySurname.
func (variantReview *VariantReview) UpdatedBySurname() *string {
	return variantReview.updatedBySurname
}

// SetUpdatedBySurname sets the updatedBySurname.
func (variantReview *VariantReview) SetUpdatedBySurname(updatedBySurname *string) {
	variantReview.updatedBySurname = updatedBySurname
}

// IsUpdated returns true if UpdatedByID is set.
func (variantReview *VariantReview) IsUpdated() bool {
	return variantReview.updatedByID != nil
}

// ReviewedByID returns reviewedByID.
func (variantReview *VariantReview) ReviewedByID() *string {
	return variantReview.reviewedByID
}

// SetReviewedByID sets the reviewedByID.
func (variantReview *VariantReview) SetReviewedByID(reviewedByID *string) {
	variantReview.reviewedByID = reviewedByID
}

// ReviewedOnDate returns reviewedOnDate.
func (variantReview *VariantReview) ReviewedOnDate() *time.Time {
	return variantReview.reviewedOnDate
}

// SetReviewedOnDate sets the reviewedOnDate.
func (variantReview *VariantReview) SetReviewedOnDate(reviewedOnDate *time.Time) {
	variantReview.reviewedOnDate = reviewedOnDate
}

// ReviewNotes returns reviewNotes.
func (variantReview *VariantReview) ReviewNotes() *string {
	return variantReview.reviewNotes
}

// SetReviewNotes sets the reviewNotes.
func (variantReview *VariantReview) SetReviewNotes(reviewNotes *string) {
	variantReview.reviewNotes = reviewNotes
}

// Approved returns approved.
func (variantReview *VariantReview) Approved() *bool {
	return variantReview.approved
}

// SetApproved sets the approved.
func (variantReview *VariantReview) SetApproved(approved *bool) {
	variantReview.approved = approved
}

// Rating returns rating.
func (variantReview *VariantReview) Rating() float32 {
	return variantReview.rating
}

// SetRating sets the rating.
func (variantReview *VariantReview) SetRating(rating float32) {
	variantReview.rating = rating
}

// Title returns title.
func (variantReview *VariantReview) Title() string {
	return variantReview.title
}

// SetTitle sets the title.
func (variantReview *VariantReview) SetTitle(title string) {
	variantReview.title = title
}

// Description returns description.
func (variantReview *VariantReview) Description() string {
	return variantReview.description
}

// SetDescription sets the description.
func (variantReview *VariantReview) SetDescription(description string) {
	variantReview.description = description
}

// VariantID returns variantID.
func (variantReview *VariantReview) VariantID() string {
	return variantReview.variantID
}

// SetVariantID sets the variantID.
func (variantReview *VariantReview) SetVariantID(variantID string) {
	variantReview.variantID = variantID
}

func newVariantReview() *VariantReview {
	return &VariantReview{}
}

// New returns a new instance of VariantReviewEntity.
func NewVariantReviewEntity() VariantReviewEntity {
	return newVariantReview()
}
