// Code generated by espal-store-synthesizer. DO NOT EDIT.
package product_test

import (
	"testing"
	"time"

	"github.com/espal-digital-development/espal-core/stores/product"
)

func TestVariantReviewTable(t *testing.T) {
	v := product.NewVariantReviewEntity()
	if v.TableName() == "" {
		t.Fatal("TableName shouldn't be empty")
	}
}

func TestVariantReviewTableAlias(t *testing.T) {
	v := product.NewVariantReviewEntity()
	if v.TableName() == "" {
		t.Fatal("TableAlias shouldn't be empty")
	}
}

func TestVariantReviewIsUpdated(t *testing.T) {
	v := product.NewVariantReviewEntity()
	v.IsUpdated()
}

func TestVariantReviewID(t *testing.T) {
	v := product.NewVariantReviewEntity()
	v.ID()
}

func TestVariantReviewCreatedByID(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetCreatedByID(testValue)
	if testValue != v.CreatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewUpdatedByID(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetUpdatedByID(&testValue)
	if &testValue != v.UpdatedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewCreatedAt(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := time.Now()
	v.SetCreatedAt(testValue)
	if testValue != v.CreatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewUpdatedAt(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := time.Now()
	v.SetUpdatedAt(&testValue)
	if &testValue != v.UpdatedAt() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewCreatedByFirstName(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetCreatedByFirstName(&testValue)
	if &testValue != v.CreatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewCreatedBySurname(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetCreatedBySurname(&testValue)
	if &testValue != v.CreatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewUpdatedByFirstName(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetUpdatedByFirstName(&testValue)
	if &testValue != v.UpdatedByFirstName() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewUpdatedBySurname(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetUpdatedBySurname(&testValue)
	if &testValue != v.UpdatedBySurname() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewReviewedByID(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetReviewedByID(&testValue)
	if &testValue != v.ReviewedByID() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewReviewedOnDate(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := time.Now()
	v.SetReviewedOnDate(&testValue)
	if &testValue != v.ReviewedOnDate() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewReviewNotes(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetReviewNotes(&testValue)
	if &testValue != v.ReviewNotes() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewApproved(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := true
	v.SetApproved(&testValue)
	if &testValue != v.Approved() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewRating(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := float32(3.14)
	v.SetRating(testValue)
	if testValue != v.Rating() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewTitle(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetTitle(testValue)
	if testValue != v.Title() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewDescription(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetDescription(testValue)
	if testValue != v.Description() {
		t.Fatal("Getter did not return the Set value")
	}
}

func TestVariantReviewVariantID(t *testing.T) {
	v := product.NewVariantReviewEntity()
	testValue := "testValue"
	v.SetVariantID(testValue)
	if testValue != v.VariantID() {
		t.Fatal("Getter did not return the Set value")
	}
}
